### ISSUE TITLE
RuntimeError: CUDA out of memory. RTX 4090

### ISSUE THREAD

**Issue by JackCloudman** [TimDettmers/bitsandbytes#102]
I have this error, i have RTX 4090. ubuntu Ubuntu 22.04.1

RuntimeError: CUDA out of memory. Tried to allocate 3.20 GiB (GPU 0; 22.20 GiB total capacity; 18.38 GiB already allocated; 2.83 GiB free; 18.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Command:

```
accelerate launch train_dreambooth.py --not_cache_latents \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="beautiful girl in xxlichxx style" \
  --class_prompt="artstyle" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
```
  --num_class_images=1 \
  --max_train_steps=4500

**Comment by jeanmichaeldiei** [comment]
You might want to turn on the 8-bit optimizers with `--use_8bit_adam`

**Comment by TimDettmers** [comment]
Please do as @jeanmichaeldiei suggested. Otherwise, it could be that you use an image that is too large (too many pixels) and you need to downsample it before you feed it into the model. Please continue discussion in this thread: #94

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
