### ISSUE TITLE
Compilation doc page is obsolete

### ISSUE THREAD

**Issue by younesbelkada** [TimDettmers/bitsandbytes#1040]
Currently the compilation guidelines in https://huggingface.co/docs/bitsandbytes/main/en/compiling are obsolete as the makefile has been deleted due to the cmake refactor. It would be great if one could re-write that documentation page so that it is up-to-date with the current way of compiling bnb from source

cc @Titus-von-Koeller

**Comment by rickardp** [comment]
Do we need to maintain the install_cuda scripts? It seems they need constant updating with new CUDA versions. Also, the way to specify CUDA version is a lot more standardized with cmake, and we could only refer to this:

https://cliutils.gitlab.io/modern-cmake/chapters/packages/CUDA.html

(Basically, set `CMAKE_CUDA_COMPILER` to the path to nvcc, version is picked up automagically if I understood the docs correctly)

Then it's only about, install the CUDA version you want, if you have multiple versions, use `-DCMAKE_CUDA_COMPILER=<path to nvcc> -DCUDA_VERSION=<cuda version>`. We can probably do away with CUDA_VERSION as it is best left to cmake to figure out

**Comment by younesbelkada** [comment]
This makes totally sense to me ! Do you want to try your hands on this? Otherwise I can do it and ping you for review

**Comment by rickardp** [comment]
I created #1048, please have a look at what you think
