### ISSUE TITLE
Fix "install from source" instructions

### ISSUE THREAD

**Issue by MatthiasKohl** [TimDettmers/bitsandbytes#1042]
### System Info

Applies to all CUDA platforms

### Reproduction

Run the following instructions as given by the error output in the latest NVIDA NGC PyTorch container:

```
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=123
python setup.py install
```

--> these instructions won't install CUDA-enabled bitsandbytes. BTW, python setup.py has been obsolete for a long time.

Run the following instructions as given by https://huggingface.co/docs/bitsandbytes/main/en/installation#from-source:
```
git clone https://github.com/TimDettmers/bitsandbytes.git && cd bitsandbytes/
cmake -B build -DBUILD_CUDA=ON -S .
pip install .
```

--> still won't give a CUDA insall, BUILD_CUDA is not a CMake option used by this project, and the build folder is useless to `pip install`

### Expected behavior

The install instructions here: https://huggingface.co/docs/bitsandbytes/main/en/installation#from-source
Are incorrect AFAICT:

Somewhat related issue: https://github.com/TimDettmers/bitsandbytes/issues/1040

1. `-DBUILD_CUDA=ON` doesn't seem to exist given CMakeLists , it should be `-DCOMPUTE_BACKEND=[cpu|cuda|mps]`
2. making the build directory `-B build` is confusing since the `setup.py` isn't looking in that folder by default. In fact, `setup.py` looks in the main repo folder by default, which is odd since this means one has to build in-place, something that's fairly rare for python extensions. If this should stay that way, at least change the default instruction to `-B .`
3. modern NVCC (I'm not sure whether this applies to all versions supported by bitsandbytes, but it should apply to most) support the "native" architecture. This is what almost every developer wants, and wastes much fewer compilation cycles than having all architectures by default. So I'd suggest adding a check in CMake for `-DCOMPUTE_CAPABILITY=native` to pass the flag `-arch=native` to NVCC, then use that as a default
4. The install instructions still lack the call to either `make` or `cmake --build`

So the final install isntructions I'd suggest at the moment is:
```
cmake -B . -DCOMPUTE_BACKEND=cuda -S .
cmake --build .
```
and ultimately, it would be nice to get to this (cannot work with the current CMakeLists):
```
cmake -B . -DCOMPUTE_BACKEND=cuda -DCOMPUTE_CAPABILITY=native -S .
cmake --build .
```

**Comment by younesbelkada** [comment]
Great catch @MatthiasKohl I can confirm this works perfect, would you be happy to fix the installation.md file on the docs? https://github.com/TimDettmers/bitsandbytes/blob/main/docs/source/installation.mdx otherwise I can do it as well

**Comment by younesbelkada** [comment]
https://github.com/TimDettmers/bitsandbytes/pull/1047 from @rickardp is fixing the commands on the docs

**Comment by MatthiasKohl** [comment]
@younesbelkada Thank you so much for fixing this so quickly ! I'd love to contribute, but I'm on CET, so I wasn't available anymore yesterday late in the evening. I'll give it a shot next time.
