### ISSUE TITLE
CUDA Setup failed despite GPU being available. Please run the following command to get more information:

### ISSUE THREAD

**Issue by c3-moutasem** [TimDettmers/bitsandbytes#1056]
### System Info

samsum) ubuntu@129-146-3-68:~/arizona-fs$ python -m bitsandbytes
/home/ubuntu/miniconda3/envs/samsum/lib/python3.12/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/ubuntu/miniconda3/envs/samsum/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/ubuntu/miniconda3/envs/samsum/lib/libcudart.so
/home/ubuntu/miniconda3/envs/samsum/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cuda112.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++ /usr/lib/x86_64-linux-gnu CUDA PATHS +++++++++++
/usr/lib/x86_64-linux-gnu/libcudart.so
/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libicudata.so
/usr/lib/x86_64-linux-gnu/stubs/libcuda.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = []
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

Torch not compiled with CUDA enabled

Above we output some debug information. Please provide this info when creating an issue via https://github.com/TimDettmers/bitsandbytes/issues/new/choose ...

`echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ubuntu/miniconda3/envs/samsum/lib/libcudart.so' > ~/miniconda3/envs/samsum/etc/conda/activate.d/set_cuda_path.sh`

### Reproduction

`conda create --name foo`
`conda activate foo`

`mv /home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so /home/ubuntu/.local/lib/python3.10/site-packages/bitsandbytes/[libbitsandbytes_cuda122.so](http://libbitsandbytes_cuda122.so/)`

`conda install cudatoolkit`

pip install "peft==0.2.0"
pip install "transformers==4.27.2" "datasets==2.9.0" "accelerate==0.17.1" "evaluate==0.4.0""bitsandbytes==0.37.1" loralib --upgrade --quiet
# # install additional dependencies needed for training
pip install rouge-score tensorboard py7zr

### Expected behavior

Should work based on this:
https://colab.research.google.com/github/ashishpatel26/LLM-Finetuning/blob/main/1.Efficiently_train_Large_Language_Models_with_LoRA_and_Hugging_Face.ipynb#scrollTo=RERkk6cCelb1

**Comment by c3-moutasem** [comment]
Hi!

I tried that before and it did not work. I managed to fix the issue with the following dependencies.

Thanks for getting back to me though!


[requirements.txt](https://github.com/TimDettmers/bitsandbytes/files/14216617/requirements.txt)

**Comment by arielgoes** [comment]
> Hi!
> 
> I tried that before and it did not work. I managed to fix the issue with the following dependencies.
> 
> Thanks for getting back to me though!
> 
> [requirements.txt](https://github.com/TimDettmers/bitsandbytes/files/14216617/requirements.txt)

It did solve my problem after recreating the virtual python environment:
![image](https://github.com/TimDettmers/bitsandbytes/assets/35307478/863cec71-2f5c-439c-9731-946618cfb874)
