### ISSUE TITLE
No errors during install via pip when can't build .so files

### ISSUE THREAD

**Issue by stilletto** [TimDettmers/bitsandbytes#108]
I installed bitsandbytes several times on different instances and sometimes I got an error only when using bitsandbytes, that builded cpu only. The only problem was that I didn't have "make" installed. So if you have errors like:
WARNING: No libcudart.so
or 
str2optimizer8bit_blockwise is not defined
or
any other missed .so files
Probably "sudo apt-get install -y make" can help you. Or "apt install build-essential -y" and "sudo apt install g++ -y"
And it is will be nice if bitsandbytes can handle this error and give solution at installation process.

**Comment by TimDettmers** [comment]
Nice catch! Would it be possible to give me a little more detail about this error? As I understand it, there seems to be some requirement to have to make installed so the right version for the CPU can be detected. Is that correct?

**Comment by stilletto** [comment]
> Nice catch! Would it be possible to give me a little more detail about this error? As I understand it, there seems to be some requirement to have to make installed so the right version for the CPU can be detected. Is that correct?
Mostly. I mean probably the bitsandbytes need build-essentials to use GPU, but no exceptions displayed when I try to install bitsandbytes with pip. Only when use it and got some errors about cpu only. It's not entirely obvious that some Linux instances don't have a make, but apparently it's needed to build a version for the correct GPU. I think is good idea to displaying a error that build-essentials is not installed.
