### ISSUE TITLE
A tutorial for windows user install bitsandbytes and triton

### ISSUE THREAD

**Issue by Scoodtone** [TimDettmers/bitsandbytes#1084]
### Feature request

I, a Chinese developer, writed this tutorial to help others who use windows system and felt difficult to use install bitsandbytes and triton without linux virtual machine.

### Motivation

It's not completely a new feature, but i can't find a zone to submit my tutorial. I sincerely wish that my tutorial can be helpful to somebody.

### Your contribution

just a link to tutorial, so not completely a feature request and no need to submit contribution, haha.
I am sorry to submit this as 'feature request', but i sincerely wish someone can reply to me.
The link based GitHub Pages, it is:
https://scoodtone.github.io/2024/02/23/laptop3060-win11-4bit-7B-opensourceLLM-InternLM/

**Comment by Titus-von-Koeller** [comment]
Closing this as I would like to move the discussion to #1095
