### ISSUE TITLE
Colab example does not lead to reduced memory footprint, leading to OOM errors when loading T5-11B on T4 GPU

### ISSUE THREAD

**Issue by f-lng** [TimDettmers/bitsandbytes#111]
Hello,

Thanks a lot for this great library and all your effort regarding it, it is much appreciated :-)

I am trying to replicate the basic example from https://colab.research.google.com/drive/1YORPWx4okIHXnjW7MSAidXN29mPVNT7F

**Error / Problem**
Loading t5-11b crashes with OOM Error and loading t5-3b works, but get_memory_footprint() returns 5300543488 instead of the expected 2884624384 . This is 1.8 times larger, leading me to believe 8bit is not used at all. However, the stacktrace at crash when loading the 11B model shows it is used after all:

> 
> Loading checkpoint shards:  67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                  | 10/15 [00:28<00:14,  2.83s/it]
> Traceback (most recent call last):
>   File "transformer_test.py", line 3, in <module>
>     model_8bit = AutoModelForSeq2SeqLM.from_pretrained("ybelkada/t5-11b-sharded", device_map="auto", load_in_8bit=True)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 463, in from_pretrained
>     return model_class.from_pretrained(
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2476, in from_pretrained
>     ) = cls._load_pretrained_model(
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2788, in _load_pretrained_model
>     new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 665, in _load_state_dict_into_meta_model
>     set_module_8bit_tensor_to_device(model, param_name, param_device, value=param)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/utils/bitsandbytes.py", line 71, in set_module_8bit_tensor_to_device
>     new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weights=has_fp16_weights).to(device)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 202, in to
>     return self.cuda(device)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 166, in cuda
>     CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/bitsandbytes/functional.py", line 1529, in double_quant
>     out_row = torch.zeros(A.shape, device=device, dtype=torch.int8)
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 14.56 GiB total capacity; 14.05 GiB already allocated; 16.44 MiB free; 14.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 

**The code**
```

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import torch
model_8bit = AutoModelForSeq2SeqLM.from_pretrained("ybelkada/t5-3b-sharded", device_map="auto", load_in_8bit=True)
print(model_8bit.get_memory_footprint())
```

**My setup** 

I am testing on a freshly setup Ubuntu 18.04 LTS with a T4 GPU, the 510 nvidia drivers, CUDA 11.6 and PyTorch 1.13.1. cuDNN is v8.6 as v8.7 did not have a Ubuntu 18.04 installer. Python version is 3.8

**Comment by younesbelkada** [comment]
Thanks for the report. It seems that there is some sort of incompatibility between the main branch of `transformers` and the latest version of `accelerate` that I need to investigate more. 
To temporary fix that you can either install the latest release of `transformers` & `accelerate` (i.e. not the lib from source) or install both of them from source 
```
pip install git+https://github.com/huggingface/transformers.git
pip install git+https://github.com/huggingface/accelerate.git

```
I have also updated the colab accordingly: https://colab.research.google.com/drive/1YORPWx4okIHXnjW7MSAidXN29mPVNT7F?usp=sharing 
Let me know if this works!

**Comment by younesbelkada** [comment]
Actually this is related to a recent PR that has been merged for T5 models
For very large T5 models, it appeared that some models led to inconsistent results / output when using them in half precision (float16), therefore - only for T5 - we had to manually cast some layers in full precision (fp32) to ensure stability at inference. This also affects int8 models since now for T5, by default all `wo` layers are upcasted to float32 (therefore not converted in 8bit)
Since the inference was already stable for t5-3b and t5-11b, you can disable this behaviour for the models provided on the examples and get the expected results with the following modifications:
```
from transformers import T5ForConditionalGeneration, AutoTokenizer
import torch

# T5-3b and T5-11B are supported!
# We need sharded weights otherwise we get CPU OOM errors
model_id=f"ybelkada/{model_name}"

tokenizer = AutoTokenizer.from_pretrained(model_id)
T5ForConditionalGeneration._keep_in_fp32_modules = None
model_8bit = T5ForConditionalGeneration.from_pretrained(model_id, device_map="auto", load_in_8bit=True)
```

Related issue: https://github.com/huggingface/transformers/issues/20287

**Comment by f-lng** [comment]
@younesbelkada 

Thank you so much for your in-detail response :-)

Actually the issue you referenced was the reason I was installing transformers from source, as the model I am trying to use is Flan-T5-XXL. 

Did I understand correctly that it should work when installing transformers and accelerate from source? 
And that, for the "vanilla" T5 models, installation from source is not needed, but _keep_in_fp32_modules should be set?

I will try to and report back later today or tomorrow

**Comment by younesbelkada** [comment]
Thank you for your reply!

- So for using `flan-t5-xxl`, installing `transformers` & `accelerate` should just work fine indeed (but I suspect the GPU RAM on Colab might be not enough)
- for the vanilla T5 models you can either:
1- install `transformers` & `accelerate` from source but add `T5ForConditionalGeneration._keep_in_fp32_modules = None` if you want to have the same memory footprint as the one stated on the Colab. Otherwise it'll run with the memory footprint that you have shared (around 4-5GB instead of 3GB)
2- or just install these libraries using `pip` and no additional code should be added (at this time of writing)

Note again that if you want to use vanilla T5 with minimal GPU memory (i.e. with the same memory footprint as the one on the colab), upcasting the layers in full precision seems to be not needed at all. 
The issue seems to appear only for large T5 models, more particularly `flan-t5-xxl` that we advice users to upcast the `wo` layers in full precision for maximal precision.

**Comment by f-lng** [comment]
@younesbelkada 

After installing the libraries from source (getting accelerate==0.15.0.dev0, transformers==4.26.0.dev0) the t5-11b model indeed loads fine on a T4 as long as T5ForConditionalGeneration._keep_in_fp32_modules = None is set. Thank you for that!

For the FLAN version, however, the following code crashes:

```
from transformers import T5ForConditionalGeneration, AutoTokenizer 
import torch

T5ForConditionalGeneration._keep_in_fp32_modules = None # WITHOUT THIS A T4 GPU WILL RUN INTO OOM

model = T5ForConditionalGeneration.from_pretrained("chenz16/flan-xxl-sharded-fp16", device_map="auto", load_in_8bit=True)
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-xxl")

input_ids = tokenizer("translate English to German: Hello my name is Younes and I am a Machine Learning Engineer at Hugging Face", return_tensors="pt").to("cuda").input_ids  
outputs = model.generate(input_ids, max_new_tokens=128)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
```

with

> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:18<00:00,  1.52s/it]
> /root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py:231: UserWarning: MatMul8bitLt: inputs will be cast from torch.int8 to float16 during quantization
>   warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
> Traceback (most recent call last):
>   File "fintest.py", line 10, in <module>
>     outputs = model.generate(input_ids, max_new_tokens=128)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/generation/utils.py", line 1199, in generate
>     model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/generation/utils.py", line 608, in _prepare_encoder_decoder_kwargs_for_generation
>     model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/accelerate/hooks.py", line 156, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 1053, in forward
>     layer_outputs = layer_module(
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/accelerate/hooks.py", line 156, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 737, in forward
>     hidden_states = self.layer[-1](hidden_states)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/accelerate/hooks.py", line 156, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 334, in forward
>     forwarded_states = self.DenseReluDense(forwarded_states)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/accelerate/hooks.py", line 156, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py", line 317, in forward
>     hidden_states = self.wo(hidden_states)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/accelerate/hooks.py", line 156, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 260, in forward
>     out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 403, in matmul
>     return MatMul8bitLt.apply(A, B, out, bias, state)
>   File "/root/miniconda3/envs/HugEnv/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 321, in forward
>     output += torch.matmul(subA, state.subB)
> RuntimeError: "addmm_cuda" not implemented for 'Char'


Any further help is much appreciated, thank you in advance.

**Comment by f-lng** [comment]
@younesbelkada Any update on this? :-)

**Comment by ryan-caesar-ramos** [comment]
Ran into the same error when running the same code. If I'm interpreting this right, before passing input to a `wo` layer (or at least one type of them, specifically `T5DenseGatedActDense`), the `transformers` library moves it to the same dtype as the `wo` layer (see [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L314)) which is expected to be in `torch.float32` to avoid the whole non-sensical output [issue](https://github.com/huggingface/transformers/issues/20287). But if you keep `wo` layers in 8bit to avoid OOM errors, then the input is moved to `torch.int8`, which `wo` layers apparently just cannot handle (`"addmm_cuda" not implemented for 'Char'`). Keeping the `wo` layers in 8bit and forcing its input to be `torch.float16` can avoid runtime errors but this approach still leads to non-sensical output that upcasting to `torch.float32` was supposed to solve in the first place.

I'm assuming this means that `T5ForConditionalGeneration._keep_in_fp32_modules = None` is really a no-go for Flan T5 XXL. Any workarounds for this? I assume `device_map="auto"` isn't supposed to come into play when loading Flan T5 XXL with some modules kept in fp32? Though that's probably a question for `accelerate`, not `bitsandbytes`.

**Comment by younesbelkada** [comment]
Hi @ryan-caesar-ramos @f-lng 
your intrepretation is right and this is a bug. It should be addressed in https://github.com/huggingface/transformers/pull/21281 and you'll be able to run the script without the issue described above
However as stated in https://github.com/TimDettmers/bitsandbytes/issues/111#issuecomment-1368873766 , you will most likely get inconsistent output if you disable `_keep_in_fp32_modules`

**Comment by f-lng** [comment]
@younesbelkada Thanks. According to the mentioned PR, which has been merged into main yesterday, that means that now Flan-T5 should work in 8bit when installing from source? Thats how I understood it, would be great for a confirmation, as I am currently not able to access my test machine.

**Comment by younesbelkada** [comment]
Hi @f-lng 
Yes, but if you use flan-xxl, you will most likely get gibberish output as stated in my previous comments.

**Comment by f-lng** [comment]
@younesbelkada So I understood it wrong, I thought https://github.com/huggingface/transformers/pull/21281 would also address this issue. 
Is there any ongoing issue I could follow regarding this or is it not expected to be fixed anytime soon? 
So right now for FLAN-XXL the only way to properly run it is using half precision not 8bit, correct?

**Comment by f-lng** [comment]
I figured out that the neccessary `T5ForConditionalGeneration._keep_in_fp32_modules = None` breaks the model, and on top of that having both the encoder and the decoder fully in 8bit also makes the runtime very slow. 

So the only method of running T5-11B while still maintaining its prediction quality and performance is to get another T4, I think there is no way around this if you want to do proper sequence generation (perhaps with small inputs and as an encoder-only model its different).

Anyway, for reference if someone stumbles upon this issue in the future, this is what I ended up with in the end: https://github.com/TimDettmers/bitsandbytes/issues/142#issuecomment-1431258698
