### ISSUE TITLE
LAMB missing in str2optimizer32bit?

### ISSUE THREAD

**Issue by Xynonners** [TimDettmers/bitsandbytes#1118]
### System Info

Python 3.11 venv, Arch Linux

### Reproduction

```
import torch
import bitsandbytes as bnb

a = [torch.rand(1), torch.rand(1)]
opt = bnb.optim.LAMB8bit(a)
a[0].grad = torch.rand(1)
opt.step()
```

venv/lib/python3.11/site-packages/bitsandbytes/functional.py", line 1211, in optimizer_update_32bit
    optim_func = str2optimizer32bit[optimizer_name][0]
                 ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'lamb'


### Expected behavior

it steps the optimizer?

**Comment by EtienneDosSantos** [comment]
Ran into this KeyError as well and you're absolutely correct with your assumption that it's missing in `str2optimizer32bit = {},`. I've opened a pull request #1222 to address this issue.

**Comment by Titus-von-Koeller** [comment]
Thanks for raising this and helping with the fix ❤️ Situation is fixed in the upcoming patch release.
