### ISSUE TITLE
Quantized 4-bit models use more memory than 16-bit models

### ISSUE THREAD

**Issue by LechengKong** [TimDettmers/bitsandbytes#1141]
### System Info

Python 3.9.16
CUDA 11.6
bitsandbytes 0.44.0.dev0

Nvidia A100 80GB

### Reproduction

Here is the code snippet that I used to test inference time memory consumption.
```python
from transformers import AutoModelForCausalLM
import torch
from peft import (
    get_peft_model, prepare_model_for_kbit_training
)

from transformers import BitsAndBytesConfig

batch_size = 32
model_name = "mistralai/Mistral-7B-v0.1" # "mistralai/Mistral-7B-v0.1" and "meta-llama/Llama-2-7b-chat-hf" tested
is_quantization = True

bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_use_double_quant=True, bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16)

def get_model(quantization):
    if quantization:
        model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=bnb_config)
        model = prepare_model_for_kbit_training(model)
    else:
        model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)
    return model



tokens = torch.randint(1000, (batch_size, 384))
tokens = {"input_ids": tokens.to("cuda")}

if is_quantization:
    model = get_model(is_quantization)
else:
    model = get_model(is_quantization).to("cuda")

with torch.no_grad():
    model(**tokens)
print(torch.cuda.max_memory_allocated()/(1024**3))
```

The peak memory usage I got was 
|         mistal-7b           |  quantized |  not quantized |
| --------- | ---------- | ----------- |
| batch_size= 32 |    10.55   |   17.77   |
| batch_size= 250 |  49.51  |  43.50  |

|         Llama-2-7b           |  quantized |  not quantized |
| --------- | ---------- | ----------- |
| batch_size= 32 |    18.46   |   20.90   |
| batch_size= 90 |  44.31  |   35.93 |
| batch_size= 128 |  OOM  |   45.77 |

while quantization seems to save some memory when the batch size small (potentially due to the reduced model size), it actually causes (much) more memory usage when the batch size is large (seems like each sample is using more memory than in the non-quantized version).

### Expected behavior

From my understanding, this is not expected, as quantization should at least be comparable to the non-quantized version memory-wise (minus some overhead). Appreciate any help and pointers to what went wrong and how can I solve this.

**Comment by LechengKong** [comment]
Hi @matthewdouglas , thanks for the prompt reply! Removing `prepare_model_for_kbit_training` indeed solves the problem. I was just curious which part of the function causes large memory consumption? Since I am setting global no_grad. Thanks. Marking the issue as closed.

**Comment by wenzhifang** [comment]
It actually confused me for a few days. I am using quantized base model (NF4) and do LoRA fine-tuning. When i call prepare_model_for_kbit_training, the memory consumption is even higher than the bf16 counterpart. So strange.

**Comment by hychiang-git** [comment]
I have the same question and just came across this possibly related issue. I profiled a model quantized to 4‑bit with `bitsandbytes`. It shows roughly a 4× reduction in model size compared with the FP16 model, but the run still uses about 8 GB of GPU memory. I’m not sure why...

<img width="774" height="130" alt="Image" src="https://github.com/user-attachments/assets/f0c8f3ef-c778-4ec2-8a69-4e15890770f1" />

```python
import os
import torch
from transformers import AutoModelForCausalLM

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

def get_size(module, return_storage=True):
    if module is None:
        return 0
    if isinstance(module, torch.nn.Parameter) or isinstance(module, torch.Tensor):
        return module.nelement() * module.element_size()
    param_size = 0
    buffer_size = 0
    for param in module.parameters():
        if return_storage:
            param_size += param.nelement() * param.element_size()
        else:
            param_size += param.nelement()
    for buffer in module.buffers():
        if return_storage:
            buffer_size += buffer.nelement() * buffer.element_size()
        else:
            buffer_size += buffer.nelement()
    return param_size + buffer_size

model_id = "meta-llama/Meta-Llama-3-8B"

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",  # or device_map={"": 0} for single GPU
    load_in_4bit=True,  # enables 4-bit quantization
    torch_dtype=torch.float16,  # required for mixed-precision inference
)

torch.cuda.empty_cache() # clear the unused temp memory used in quantization 
print(get_size(model) / 1000**3)  #  5.591539968 roughly 4x memory reduction compared to the fp16 model
print(torch.cuda.max_memory_allocated()/(1024**3)) # 7.478763580322266
```

I am reading the cuda [implementation](https://github.com/bitsandbytes-foundation/bitsandbytes/blob/main/csrc/kernels.cu#L370) but still no clues on this issue. Am I missing something?

**Comment by hychiang-git** [comment]
I found `transformers==v4.52.0` fixed my issue (see this [line](https://github.com/huggingface/transformers/blob/113424bcd53b92600f77d82f48add0a60fb41556/src/transformers/modeling_utils.py#L4989))

**Comment by weathon** [comment]
I had the same problem
It was very weird that I tried to finetune Qwen3-VL-30B-A3B on Google Colab, and found that using 4-bit version actually raised VRAM OOM error, and if I use bf16 it runs fine. 
```
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=False,
        bnb_4bit_quant_type='nf4',
)

# processor = AutoProcessor.from_pretrained("google/gemma-3-270m")

model = AutoModelForImageTextToText.from_pretrained(
    "Qwen/Qwen3-VL-30B-A3B-Instruct", torch_dtype=torch.bfloat16, device_map="auto"#, quantization_config=bnb_config
)
```
If I added quantization_config=bnb_config it will have OOM
