### ISSUE TITLE
Dequantizing int8 models to fp16

### ISSUE THREAD

**Issue by raunaks13** [TimDettmers/bitsandbytes#1142]
I have loaded an LLM in huggingface with `load_in_8bit=True`.
I noticed the objects in the state_dict are structured something like

1. `model.layers.18.self_attn.k_proj.weight`
2. `model.layers.18.self_attn.k_proj.SCB`
3. `model.layers.18.self_attn.k_proj.weight_format`

The `SCB` and `weight_format` are present only in the quantized model. I think `SCB` refers to scale and bias that can help us in recreating the original tensor? `weight_format` is a string that says “row”. The [huggingface integration guide](https://huggingface.co/blog/hf-bitsandbytes-integration) mentions a `.CB` field in addition to the `.SCB` field, but I could not find it in the state_dict. Not sure if the codebase has changed since that was written?

Anyway, I am not sure about the exact method to dequantize the tensor to get back the original, but I tried the following:
`(weight_SCB.unsqueeze(1) * weight)/127`
This is giving a tensor that is close to the original model (what I get without adding the parameter `load_in_8bit=True`), but not the same.
I am not sure whether I am following the correct approach for dequantization. Would be great if someone could point me to some code or documentation on how I can recreate the exact original tensor from the weights.

As a follow up question, I know that for some models there are outlier values that are not quantized even though other values in the tensor are quantized. However I could not find this information in the state_dict. How can we find and handle these values during the dequantization process?

**Comment by LuckMonkeys** [comment]
Hello, I came across the issue you posted about tensor dequantization and was wondering if there has been any progress since it was initially raised. Specifically, are you still using the method `(weight_SCB.unsqueeze(1) * weight)/127` for dequantizing the tensor? If so, has it proved to be effective, or have you encountered any problems? I am facing a similar challenge and any insights you could share would be greatly appreciated.

**Comment by raunaks13** [comment]
I think dequantizing the tensor to recover the exact original is not possible, since the quantization process involves rounding.  When dequantization is used, however, I don't think the error matters that much based on the results I have seen in papers.
I haven't tested the impact of using the above formula on training/inference myself.

**Comment by exhyy** [comment]
`bitsandbytes.functional.int8_vectorwise_dequant` is implemented as follows:
```python
def int8_vectorwise_dequant(A: torch.Tensor, stats: torch.Tensor):
    """Dequantizes a tensor with dtype `torch.int8` to `torch.float32`.

    Args:
        A (`torch.Tensor` with dtype `torch.int8`): The quantized int8 tensor.
        stats (`torch.Tensor` with dtype `torch.float32`): The row-wise quantization statistics.

    Returns:
        `torch.Tensor` with dtype `torch.float32`: The dequantized tensor.
    """
    # To dequantize we divide by 127, or multiply by the reciprocal.
    return A * stats.view(-1, 1) * 7.874015718698502e-3
```
Therefore, I think `(weight_SCB.unsqueeze(1) * weight)/127` is a correct way to dequantize int8 parameters.
