### ISSUE TITLE
NVIDIA TX2+jetpack 5+Ubuntu20.4：No matching distribution found for bitsandbytes==0.43.0

### ISSUE THREAD

**Issue by qxpBlog** [TimDettmers/bitsandbytes#1151]
### System Info

cuda                           11.8
asn1crypto                0.24.0                   py37_0    c4aarch64
bzip2                     1.0.6                h7b6447c_6    c4aarch64
ca-certificates           2018.03.07                    0    c4aarch64
certifi                   2018.10.15               py37_0    c4aarch64
cffi                      1.11.5           py37hc365091_1    c4aarch64
chardet                   3.0.4                    py37_1    c4aarch64
conda                     4.5.12                   py37_0    c4aarch64
conda-env                 2.6.0                         1    c4aarch64
cryptography              2.5              py37h9d9f1b6_1    conda-forge
filelock                  3.12.2                    <pip>
fsspec                    2023.1.0                  <pip>
huggingface-hub           0.16.4                    <pip>
idna                      2.7                      py37_0    c4aarch64
importlib-metadata        6.7.0                     <pip>
libffi                    3.2.1                h71b71f5_5    c4aarch64
libgcc-ng                 7.3.0                h5c90dd9_0    c4aarch64
libstdcxx-ng              7.3.0                h5c90dd9_0    c4aarch64
ncurses                   6.1                  h71b71f5_0    c4aarch64
numpy                     1.21.6                    <pip>
openssl                   1.1.1a            h14c3975_1000    conda-forge
packaging                 24.0                      <pip>
pip                       24.0                      <pip>
pip                       10.0.1                   py37_0    c4aarch64
pycosat                   0.6.3            py37h7b6447c_0    c4aarch64
pycparser                 2.19                     py37_0    c4aarch64
pyopenssl                 18.0.0                   py37_0    c4aarch64
pysocks                   1.6.8                    py37_0    c4aarch64
python                    3.7.1             h39be038_1002    conda-forge
PyYAML                    6.0.1                     <pip>
readline                  7.0                  h7ce4240_5    c4aarch64
regex                     2023.12.25                <pip>
requests                  2.19.1                   py37_0    c4aarch64
ruamel_yaml               0.15.64          py37h7b6447c_0    c4aarch64
safetensors               0.4.2                     <pip>
setuptools                40.4.3                   py37_0    c4aarch64
six                       1.11.0                   py37_1    c4aarch64
sqlite                    3.26.0            h1a3e907_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tokenizers                0.13.3                    <pip>
torch                     1.13.1                    <pip>
tqdm                      4.66.2                    <pip>
transformers              4.30.2                    <pip>
typing_extensions         4.7.1                     <pip>
urllib3                   1.23                     py37_0    c4aarch64
wheel                     0.32.1                   py37_0    c4aarch64
xz                        5.2.4                h7ce4240_4    c4aarch64
yaml                      0.1.7                h7ce4240_3    c4aarch64
zipp                      3.15.0                    <pip>
zlib                      1.2.11               h7b6447c_2    c4aarch64

### Reproduction

ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.0 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes==0.43.0

### Expected behavior

@kashif @stephenroller @akx @jbn @why i can not get the latest version ```bitsandbytes```

**Comment by matthewdouglas** [comment]
Hi @qxpBlog,

`bitsandbytes` is not currently built with support for aarch64 platforms. Releases prior to 0.43.0 to PyPI were tagged as supporting all platforms, but moving forward the wheels are tagged appropriately for the platforms they support. As of right now, that is just Windows and Linux on x86-64.

You can follow #997 for more information on plans to support additional platforms.

**Comment by qxpBlog** [comment]
> 嗨，
> 
> `bitsandbytes`当前不支持 aarch64 平台。PyPI 的 0.43.0 之前的版本被标记为支持所有平台，但今后轮子会针对它们支持的平台进行适当的标记。截至目前，这只是 x86-64 上的 Windows 和 Linux。
> 
> 您可以关注 #997 以获取有关支持其他平台的计划的更多信息。

thanks for your help.

**Comment by cemiu** [comment]
I had the same issue of bitandbytes 0.42.0 being available, but not 0.43+ on RHEL 7 (centOS 7 and other older distros should also be affected):

The pip release of bitsandbytes 0.43.0+ requires glibc 0.24+, while some older distros don't have it. You can verify by running: `ldd --version`

If you run into this issue, you can either use the conda-forge instead (supports glibc 2.17+) or build from source.
