### ISSUE TITLE
HTTP ERROR 403. It says: 127.0.0.1 refused^

### ISSUE THREAD

**Issue by HowKing66** [TimDettmers/bitsandbytes#1174]
### System Info

Macbook Pro 14 2021 version with 16gb ram and 512gb.

### Reproduction

https://colab.research.google.com/github/TavernAI/TavernAI/blob/main/colab/GPU.ipynb#scrollTo=kzzNdltKQsY3

### Expected behavior

I thought there may be a popup of the webui for me to use. Sorry, I'm a noobie in this field, I don't know too much about coding.

**Comment by Titus-von-Koeller** [comment]
The info provided is very scarce and the error provided is clearly not related to BNB as our library does not establish any HTTP connection whatsoever.

Closing as unrelated. Wish you the best in your endeavor!
