### ISSUE TITLE
NameError: name 'cuda_setup' is not defined

### ISSUE THREAD

**Issue by w-firm** [TimDettmers/bitsandbytes#124]
![image](https://user-images.githubusercontent.com/50365787/212640194-16504719-a91a-4a59-a23e-1dea17e11319.png)

**Comment by evelinedurom** [comment]
@w-firm I think Its an issue with the GPU. Make sure you are using a Turing or Ampere GPU.

**Comment by snail2lzq** [comment]
this issue because the GPU Compute capability < 7.5 , you can try A4-A100
