### ISSUE TITLE
Running BLOOM-175B on 8x RTX 3090 GPUs

### ISSUE THREAD

**Issue by bai-generally-intelligent** [TimDettmers/bitsandbytes#137]
I'm trying to run the `bigscience/bloom` model (175B params) on 8x RTX 3090 GPUs which should be possible according to the paper. I'm following [this notebook](https://colab.research.google.com/github/huggingface/blog/blob/main/notebooks/HuggingFace_int8_demo.ipynb), but I'm getting an out of memory error:

> RuntimeError: CUDA out of memory. Tried to allocate 784.00 MiB (GPU 0; 23.70 GiB total capacity; 21.25 GiB already allocated; 521.69 MiB free; 22.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

At time of crashing, the first GPU is out of capacity while the other 7 GPUs only have 810MB used up according to nvidia-smi. I am able to run smaller models (such as bloom-3b and opt-66b) with no problems. What could be wrong here?

**Comment by JohnnyRacer** [comment]
> I'm trying to run the `bigscience/bloom` model (175B params) on 8x RTX 3090 GPUs which should be possible according to the paper. I'm following [this notebook](https://colab.research.google.com/github/huggingface/blog/blob/main/notebooks/HuggingFace_int8_demo.ipynb), but I'm getting an out of memory error:
> 
> > RuntimeError: CUDA out of memory. Tried to allocate 784.00 MiB (GPU 0; 23.70 GiB total capacity; 21.25 GiB already allocated; 521.69 MiB free; 22.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> At time of crashing, the first GPU is out of capacity while the other 7 GPUs only have 810MB used up according to nvidia-smi. I am able to run smaller models (such as bloom-3b and opt-66b) with no problems. What could be wrong here?

@bai-generally-intelligent 

I am having the same issue training a large GPT model, where only one GPU's VRAM is filled up and it encounters OOM. I believe it's because the `transformers` library doesn't properly implement model sharding on multi GPUs currently. I think it's better to open an issue in the `transformers` repo and ask the Huggingface team why this is happening.

**Comment by younesbelkada** [comment]
Yeah sometimes you may encounter some corner cases and have issues like the one you just described

When you use `device_map="auto"` it should automatically compute the best device_map that fits all your available GPUs. I would advise to either:

1- a custom `device_map` : you don't need to write the whole path to your modules, in case of `bloom` you can do something like (following the keys from the bloom source code: https://github.com/huggingface/transformers/blob/c836f77266be9ace47bff472f63caf71c0d11333/src/transformers/models/bloom/modeling_bloom.py#L821):
```
device_map = {
"transformer.word_embeddings":0,
"transformer.word_embeddings_layer_norm":0,
"transformer.h.0": 0, 
"transformer.h.1": 1,
...
}
```

2- use different  `device_map` strategies such as `device_map='balanced'`
