### ISSUE TITLE
CUDA SETUP: Required library version not found: libbitsandbytes_cuda102.so.

### ISSUE THREAD

**Issue by chenmingjiong** [TimDettmers/bitsandbytes#138]
import failed on 2080ti, cuda10.2, ubuntu 18.04.

`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/chenmingrui/miniconda3/lib/python3.7/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/chenmingrui/miniconda3 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA version lower than 11 are currently not supported for LLM.int8(). You will be only to use 8-bit optimizers and quantization routines!!
CUDA SETUP: CUDA runtime path found: /data/cuda/cuda-10.2/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 102
CUDA SETUP: Required library version not found: libbitsandbytes_cuda102.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=102
python setup.py install
CUDA SETUP: CUDA version lower than 11 are currently not supported for LLM.int8(). You will be only to use 8-bit optimizers and quantization routines!!
CUDA SETUP: CUDA runtime path found: /data/cuda/cuda-10.2/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 102
CUDA SETUP: Required library version not found: libbitsandbytes_cuda102.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=102
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: CUDA version lower than 11 are currently not supported for LLM.int8(). You will be only to use 8-bit optimizers and quantization routines!!
CUDA SETUP: CUDA runtime path found: /data/cuda/cuda-10.2/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 102
CUDA SETUP: Required library version not found: libbitsandbytes_cuda102.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=102
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=102
python setup.py install`

Tried compile from source `CUDA_VERSION=102 make cuda10x`but failed:
`make: *** No rule to make target 'cuda10x'.  Stop.`
 Should I use `CUDA_VERSION=102 make cuda10x_nomatmul` ?

**Comment by ZeyadWaell** [comment]
how did u solve this problem ?

**Comment by norabelrose** [comment]
I'm having this same problem

**Comment by visago** [comment]
My required file was already in /usr/local/lib/python3.10/dist-packages/bitsandbytes/ but somehow not detected. Anyone knows the environment variable used to set the path ?

**Comment by XiaoYee** [comment]
Have you solved it? I met the same problem

**Comment by XiaoYee** [comment]
@ZeyadWaell Thanks for your reply. I still fail even do this.
After changing my cuda version from 10.2 to 11.5, I succeed.

**Comment by someshfengde** [comment]
CUDA SETUP: Required library version not found: libbitsandbytes_cuda113_nocublaslt.so. Maybe you need to compile it from source?


same error

**Comment by kbmlcoding** [comment]
@someshfengde i am also getting same error 

`DEBUG: Possible options found for libcudart.so: {PosixPath('/home/kadu/local/cuda-11.7/lib64/libcudart.so'), PosixPath('/home/kadu/local/cuda-11.7/lib64/libcudart.so.11.0')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 7.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/home/kadu/bitsandbytes/bitsandbytes/cuda_setup/main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

`
Has anyone have any suggestions

**Comment by kbmlcoding** [comment]
Got same error

CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?

Has anyone have any suggestion to fix it?

**Comment by DianeBouchacourt** [comment]
Same problem here

**Comment by ysanimals** [comment]
after rewrite the LIB_PATH still can''t solve the problem

**Comment by kiran-prajapati** [comment]
Has anyone solved this issue?

**Comment by someshfengde** [comment]
@kiran-prajapati nope i tried to find a solution but I wasn't able to so I moved to a different library

**Comment by juiceSea** [comment]
可能当时cuda不是装在conda虚拟环境的原因，导致找不到，也可能是bitsandbytes版本不对应
尝试在当前环境更新一下bitsandbytes
pip install -U bitsandbytes

**Comment by danpe** [comment]
same here

**Comment by chen1234520** [comment]
python环境中的bitsandbytes与cuda的版本不一致，cuda版本较高的话，升级一下bitsandbytes的版本。
