### ISSUE TITLE
Finding outliers

### ISSUE THREAD

**Issue by barasamit** [TimDettmers/bitsandbytes#143]
I would greatly appreciate your assistance in gaining a better understanding of the code. Specifically, I would like to inquire about the MatMul8bitLt function, wherein a line located under the Quantize B section searches for outliers (outliers = F.extract_outliers(state.CxB, state.SB, state.idx.int())). Based on my understanding, it appears that outliers are being looked for on the weights,  as far as I understand it should be on the input. I would be grateful for any insight you may have on this aspect of the code, as well as any clarification you can provide on the meaning and purpose of CB, CxB, SB, and other relevant variables.
Thank you for your time and assistance.

**Comment by zachzzc** [comment]
Hi @barasamit  I also have the same questions when looking at the code. Can you share the answer if you find it ?

**Comment by zachzzc** [comment]
Thanks @barasamit  

My first question is also the meaning and purpose of CB, CxB and SB ?

Second question is in the state.CxB case, we rely on CxB and SB to find the outliers, instead of the outlier information from matrix A. What is the purpose here? 

```
            if state.CxB is not None:
                outliers = F.extract_outliers(state.CxB, state.SB, state.idx.int())
            else:
                outliers = state.CB[:, state.idx.long()].clone()
```
