### ISSUE TITLE
Lion optimizer

### ISSUE THREAD

**Issue by christallire** [TimDettmers/bitsandbytes#150]
Could we have a chance to test Lion optimizer? 🥇  (https://github.com/lucidrains/lion-pytorch)

**Comment by lucidrains** [comment]
@christallire hey Chris, decided to [start working on this](https://github.com/TimDettmers/bitsandbytes/pull/188)

feel free to test it or help out

**Comment by christallire** [comment]
@lucidrains cool cool, thanks. will test.
