### ISSUE TITLE
Any changes to the function "optim.AdamW8bit"?

### ISSUE THREAD

**Issue by arceus-jia** [TimDettmers/bitsandbytes#152]
When I use version 0.37.0 of AdamW8bit as an optimizer, the loss calculation quickly becomes nan, (which is problematic when training dreambooth or Lora) but when I fall back to version 0.35.4, these problems will no longer exist

**Comment by ArrowM** [comment]
Bump. (plus I think this is a dup of #121)

**Comment by ArrowM** [comment]
This is a total shot in the dark, but I wonder if bitsandbytes/functional.py:218 was accidentally indented in 2f2063bac212bcd6a515a88a12a9530b5730dabe

**Comment by LiBromine** [comment]
Additionally, I think the arguments should be max_exponent_bits=6, total_bits=7 for unsigned case in this function, which really creates a map of length 256.

**Comment by rationalism** [comment]
@ArrowM @arceus-jia This should be fixed by 0.41.1
