### ISSUE TITLE
0.37 pip and pkg release does not have gpu support compiled in

### ISSUE THREAD

**Issue by Qubitium** [TimDettmers/bitsandbytes#176]
On Ubuntu 22.04 with latest anaconda and pytorch 2.0 nightly.  I tried pip and the github 0.37 release pkg with exact same error below.

```
/root/anaconda3/lib/python3.9/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. `
```

**Comment by neuhaus** [comment]
Right. This was a problem for me also, luckily i found this issue and then uninstalled the package in pip.

**Comment by diegomontoya** [comment]
@neuhaus how did you work around this?

**Comment by neuhaus** [comment]
pip uninstall bitsandbytes
python setup.py install

**Comment by Vasanthengineer4949** [comment]
Another error is arising followed by doing this like cuda not installed any suggestions like create environment from first?

> pip uninstall bitsandbytes python setup.py install

**Comment by Vitor-Almeida** [comment]
Got the same problem, using pip I'm getting: 
```UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support.
``` 
Tried python setup.py install and getting a multitude of other erros.

**Comment by diegomontoya** [comment]
My issue was resolved after installing cuda-toolkit-11-8 in the lxd conttainer. For some reason, the host did not pass the libcudart.so link to the container correctly. 

So it may appear the error message ``` warn("The installed version of bitsandbytes was compiled without GPU support.``` is contextually wrong in the message. It actually means the following:

1) pkg not compiled for gpu
2) pkg compiled for gpu but unable to link to cuda (gpu) library

Better error messaging should fix all the confusion.
