### ISSUE TITLE
Everything seems a real mess

### ISSUE THREAD

**Issue by nextdimension** [TimDettmers/bitsandbytes#185]
I'm using linux and I have installed version 0.37 from pip and it is not compiled with gpu support.
I tried every version of b&b and combination of cuda versions and I either get not compiled with gpu support error
or AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'

I can also find no version specifically compiled for cuda 12.0 or 11.8 but they are mentioned as having better cuda detection in the 0.37 release notes.

At this point I give up. Why is the versioning and compiled versions such a mess?

**Comment by TimDettmers** [comment]
Can you please post the output of `python -m bitsandbytes`. This will help me to debug.

**Comment by calhounpaul** [comment]
Might've just installed the og repo because you're in a docker image that's a bit out of date. Also, I'd try to avoid 12.0 for a few more months (weeks?), even though I'm sure NVIDIA would love for you to switch yesterday. Have you tried [compiling+installing from this repo, specifically](https://github.com/TimDettmers/bitsandbytes/blob/main/compile_from_source.md)? Ignore pip for a moment.

**Comment by scotter1995** [comment]
> Can you please post the output of `python -m bitsandbytes`. This will help me to debug.

I'm getting the same issue
the output of python -m bitsandbytes is the following:
Traceback (most recent call last):
  File "/home/yes/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yes/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yes/anaconda3/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 30, in <module>
    from . import COMPILED_WITH_CUDA, PACKAGE_GITHUB_URL
ImportError: cannot import name 'COMPILED_WITH_CUDA' from 'bitsandbytes' (/home/yes/anaconda3/lib/python3.9/site-packages/bitsandbytes/__init__.py)

I'm not sure what needs to be updated but I'm just trying to run alpaca-lora-30b-int4 and running into a ton of issue. Any help would be appreciated.

**Comment by jprobichaud** [comment]
I have the same situation on linux, I installed using `pip install bitsandbytes-cuda117` and `python -m bitsandbytes` yields : 

```
==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++ DEBUG INFORMATION +++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "/home/jp/miniconda3/envs/lora/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jp/miniconda3/envs/lora/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jp/miniconda3/envs/lora/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 30, in <module>
    from . import COMPILED_WITH_CUDA, PACKAGE_GITHUB_URL
ImportError: cannot import name 'COMPILED_WITH_CUDA' from 'bitsandbytes' (/home/jp/miniconda3/envs/lora/lib/python3.9/site-packages/bitsandbytes/__init__.py)
```

**Comment by jsoyee** [comment]
same issue, not just linux, Wndows too. 
PS C:\Users\PC\Downloads\AI\LLM\gpt4all\nomic> python -m bitsandbytes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++ DEBUG INFORMATION +++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bitsandbytes\__main__.py", line 30, in <module>
    from . import COMPILED_WITH_CUDA, PACKAGE_GITHUB_URL
ImportError: cannot import name 'COMPILED_WITH_CUDA' from 'bitsandbytes' (unknown location)
PS C:\Users\PC\Downloads\AI\LLM\gpt4all\nomic> $

**Comment by dlcvag** [comment]
I having this issue too. Just ran python -m bitsandbytes this is what I got:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/gomesd/miniconda3/envs/alpaca3/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x_nomatmul
python setup.py install
CUDA SETUP: CUDA runtime path found: /home/gomesd/miniconda3/envs/alpaca3/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: CUDA runtime path found: /home/gomesd/miniconda3/envs/alpaca3/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: CUDA runtime path found: /home/gomesd/miniconda3/envs/alpaca3/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x_nomatmul
python setup.py install
Traceback (most recent call last):
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/gomesd/miniconda3/envs/alpaca3/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

**Comment by BayramAnnakov** [comment]
Any updates on this issue please?

**Comment by samarthsarin** [comment]
Any updates. Please help!

**Comment by jprobichaud** [comment]
I managed to get go forward with `pip install bitsandbytes` and installing
the `cudatoolkit` package with conda.

**Comment by sjhyeon2** [comment]
I too get the error after installing cudatoolkit.

**Comment by Thireus** [comment]
This worked for me:
```
pip uninstall bitsandbytes
pip install bitsandbytes
```

**Comment by sjhyeon2** [comment]
I found the answer, but I don't know why this is happening.

Don't install from jupyter notebook.
If you install from the console, it works fine. 

(As far as I can tell, both versions are the same, but if you install from notebook, there is no Linear8bitLt).

thank you @Thireus

**Comment by afogarty85** [comment]
I am also faced with this issue:

``` 
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'
```

Using:

```
WSL
11.8 Toolkit (nvcc -V)
pip install bitsandbytes
```

**Comment by donote** [comment]
> I have the same issue

I have resolved this problem. 
see the issue: https://github.com/TimDettmers/bitsandbytes/issues/305#issuecomment-1507841745

**Comment by nextdimension** [comment]
> > I have the same issue
> 
> 
> 
> I have resolved this problem. 
> 
> see the issue: https://github.com/TimDettmers/bitsandbytes/issues/305#issuecomment-1507841745

No you haven't. The issue still persists. 

Reinstalling cuda may have worked for you but you assume people are using conda, I am not.

I have worked around this issue but it still happens.

One of the problems is that the library does not look in all the right file paths for cuda, specifically on arch it looks on the wrong place. 

So you need to set the environment variable to point to the right cuda path.

Super annoying, as the error messages are miss leading.

**Comment by chintan-donda** [comment]
> Any updates. Please help!
> 
> AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'

I'm also facing the same issue. Any fix?

**Comment by smokey42** [comment]
Uninstall `bitsandbytes` and compile it from scratch (might be a bit elaborate, depending on your setup). This solved it for me though.

**Comment by keunwoochoi** [comment]
i am having the same issue after `pip install bitsandbytes-cu117`.

but perhaps @TimDettmers is not the one to blame here..

**Comment by bbecausereasonss** [comment]
Same issue here, tried everything you can imagine including compiling bitsandbytes from here, following your instructions. Cuda 117, WSL...  Textgen UI complains it's not compiled with CUDA... Or it fails with attribute error (no linear8bit bla bla bla....

AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'

**Comment by afogarty85** [comment]
Doing a wipe of nvidia-* and reinstalling fixed the issue for me. The below documentation is for WSL Linux but it should also work for most other distros; consider the following steps:

https://github.com/afogarty85/AzureDataEngineering-DeepLearning/blob/main/DeepLearning/LinuxCUDASetup.sh

**Comment by keunwoochoi** [comment]
on ec2 / v100 / cuda11.4. 

i once tried simply `pip` and it didn't work.

i uninstalled it, compiled as in README, and `python setup.py install`. it worked.

**Comment by bbecausereasonss** [comment]
Tried wiping and re-installing Nvidia, tried compiling python setup.py install, nothing worked.

**Comment by maadnfritz** [comment]
trying on colab and also getting 
module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'

**Comment by SimonBenhamou** [comment]
Same... any update on this ? On a fresh GCP VM it makes installing bitsandbytes close to impossible...

**Comment by nextdimension** [comment]
You need to set your cuda directory so it know where to find the cuda binaries when it runs as it doesn’t look in every possible place they can be installed

**Comment by curtiskeisler** [comment]
> You need to set your cuda directory env var, so it knows where to find the cuda binaries when it runs as it doesn’t look in every possible place they can be installed

What specifically is the environment variable you're talking about? I'm new at this. So, I have no idea what variable you're talking about. Thanks!

**Comment by difficulttopickaname** [comment]
Any updates? I've tried installing bitsandbytes with cuda 116 first, caused a Runtime Error, then uninstalling it and reinstalling without cuda, a slightly different Runtime Error, then uninstalling and reinstalling bitsandbytes-windows, works a little bit more but has "module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'". I'm messing with all the versions trying to solve the problem, but nothing good turns out.

**Comment by ihongxx** [comment]
$ sudo apt install gcc-10 g++-10
$ export CC=/usr/bin/gcc-10
$ export CXX=/usr/bin/g++-10
$ export CUDA_ROOT=/usr/local/cuda
$ ln -s /usr/bin/gcc-10 $CUDA_ROOT/bin/gcc
$ ln -s /usr/bin/g++-10 $CUDA_ROOT/bin/g++
$ git clone https://github.com/timdettmers/bitsandbytes.git
$ cd bitsandbytes
$ CUDA_HOME=/usr/local/cuda-11.6 CUDA_VERSION=116 make cuda11x
$ python setup.py install
I succeeded！

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by apurvgandhwani** [comment]
Any update on this? I am getting the same error
