### ISSUE TITLE
Typo In Shared Library CPU Fallback Name?

### ISSUE THREAD

**Issue by gs-hopkiz** [TimDettmers/bitsandbytes#191]
Should lib<ins>**s**</ins>bitsandbytes_cpu below be libbitsandbytes_cpu?

https://github.com/TimDettmers/bitsandbytes/blob/2c8352e316d5428f57f47ec8b557dc9c9caf427f/bitsandbytes/cuda_setup/main.py#L368

I was looking into the messages printed out when using the CPU-only bitsandbytes build and noticed this:

```
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
```

There are 2 other places in cuda_setup/main.py that reference `libbitsandbytes_cpu.so`. So that other lib name looks like a typo possibly?

**Comment by josejuanmartinez** [comment]
Same problem here.

**Comment by seandearnaley** [comment]
+1
