### ISSUE TITLE
Multiple GPUs not detected in WSL

### ISSUE THREAD

**Issue by TrainzLuvr** [TimDettmers/bitsandbytes#202]
Using github version
WSL2 Ubuntu 22.04.2 LTS (under Windows 10)
Python 3.10
CUDA 11.8

nvidia-smi output:
```
NVIDIA-SMI 530.30.04 | Driver Version: 531.29 | CUDA Version: 12.1
0  NVIDIA GeForce GTX TITAN X      
1  NVIDIA GeForce RTX 3090
```

I keep getting the warning that my CC < 7.5 and I believe it's because the GPUs are not detected correctly, namely only device 0 is detected/CC checked, and so my CC ends up being 5.2.

Also, cuda_setup/main.py: get_compute_capabilities(cuda) does not look for ENV var CUDA_VISIBLE_DEVICES. I believe the ENV var should take precedence over what cuDeviceGetCount reports, because if the user has set it, then they clearly know what hardware they want to use.

I admit though that this is probably not an issue with bitsandbytes, but with CUDA Toolkit and cuDeviceGetCount running under WSL. Though, using the ENV var CUDA_VISIBLE_DEVICES should still be supported by bitsandbytes when checking CC.

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
