### ISSUE TITLE
Questions about the quantization implementation

### ISSUE THREAD

**Issue by zachzzc** [TimDettmers/bitsandbytes#206]
Hi @TimDettmers 

First of all, very impressive work! I do have some questions about the details:

1. If we set the `has_fp16_weights=False`, the weights will be pre-quantized into 8 bits beforehand so we don't need to quantize the weights during the inference. To calculate the outlier parts, we up-cast the sub weight into bf16 and do the matmul. Is my understanding correct? And the results in the paper is with `has_fp16_weights=False` ? 

2. Another alternative of the quantization is to keep weights in 8 bits and always keep activation values in fp16 so each time we just need to de-quantize the weight values. Compared to this approach, the gain of LLM.int8 is that we compute some vectors in int8 gemm so it is faster in very big matmul. Is that correct ?

**Comment by Shuai-Xie** [comment]
@zachzzc Hi, bro. You can read this paper for more details: [LLM.int8(): 8-bit Matrix Multiplication for Transformers at Scale](https://arxiv.org/abs/2208.07339).

If I understand correctly, `LLM.int8()` use a `llm_int8_threshold` (default is 6.0) to filter FP16 channels as below. 
- The core insight is that **outliers are limited to some specific hidden dims**. For these dims, activation and weights well be computed with FP16_GEMM, while the rest dims use INT8_GEMM.
- And the authors found that the number of **outlier feature dimensions is not larger than 7 (|O| ≤ 7)** for transformers up to 13B parameters, this INT8/FP16 GEMM decomposition operation only **consumes about 0.1% additional memory.**

<img width="868" alt="image" src="https://github.com/TimDettmers/bitsandbytes/assets/18352713/c094604c-da21-4d4b-aff4-551c8ba50b09">

Thes configs can be set with `BitsAndBytesConfig` of this bitsandbytes lib.

```python
default_config = {
    # 4bits
    "load_in_4bit": False,
    "bnb_4bit_compute_dtype": "float32",       # float16, bfloat16, float32
    "bnb_4bit_quant_type": "fp4",              # fp4, np4
    "bnb_4bit_use_double_quant": False,
    # 8bits
    "load_in_8bit": False,
    "llm_int8_enable_fp32_cpu_offload": False,
    "llm_int8_has_fp16_weight": False,
    "llm_int8_skip_modules": None,
    "llm_int8_threshold": 6.0,  # In our work, we find that α = 6.0 is sufficient to reduce transformer performance degradation close to zero
}
```
