### ISSUE TITLE
pip install bitsandbytes installs CPU only

### ISSUE THREAD

**Issue by ironharvy** [TimDettmers/bitsandbytes#208]
`pip install --ignore-installed bitsandbytes
Collecting bitsandbytes
  Using cached bitsandbytes-0.37.2-py3-none-any.whl (84.2 MB)
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.37.2`

> Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
> Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
> CUDA SETUP: CUDA runtime path found: /home/lameradze/miniconda3/envs/sd2/lib/libcudart.so
> /home/lameradze/miniconda3/envs/sd2/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...  warn(msg)
> CUDA SETUP: Detected CUDA version 117
> CUDA SETUP: Loading binary /home/lameradze/miniconda3/envs/sd2/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
> /home/lameradze/miniconda3/envs/sd2/lib/python3.9/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
> warn("The installed version of bitsandbytes was compiled without GPU support. "

which results in
> NameError: name 'str2optimizer8bit_blockwise' is not defined

`pip install bitsandbytes-cuda117
Collecting bitsandbytes-cuda117
  Downloading bitsandbytes_cuda117-0.26.0.post2-py3-none-any.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 27.2 MB/s eta 0:00:00
Installing collected packages: bitsandbytes-cuda117
Successfully installed bitsandbytes-cuda117-0.26.0.post2`
Running this that version only yields 
> ==============================WARNING: DEPRECATED!==============================
> WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: > https://github.com/TimDettmers/bitsandbytes
> ==============================WARNING: DEPRECATED!==============================

I'm running on WSL , cuda-11.8,

**Comment by Gitterman69** [comment]
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /home/user/anaconda3/envs/llama/lib/libcudart.so
/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary /home/user/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/user/anaconda3/envs/llama/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by yuyq96** [comment]
have the same problem

**Comment by woshicqy** [comment]
the same problem here

**Comment by Gitterman69** [comment]
The „add to path“ solution works ( in wsl) but you gotta do it everytime you restart your terminal :)

**Comment by Vitor-Almeida** [comment]
> The „add to path“ solution works ( in wsl) but you gotta do it everytime you restart your terminal :) Sent from Proton Mail for iOS

Can you explain the ,,add to path" solution?

**Comment by Gitterman69** [comment]
On WSL, you might need to install CUDA manually by following[these steps](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local), then running the following before you launch:

export LD_LIBRARY_PATH=/usr/lib/wsl/lib

From the manual, see above

**Comment by ZizoAdam** [comment]
>export LD_LIBRARY_PATH=/usr/lib/wsl/lib

Instead of running it every time, add it to your .bashrc file

**Comment by Gitterman69** [comment]
thanks!

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by wisamidris7** [comment]
No it seemed like when installing the latest version of it it would install the cpu version and also old version
So that install from url worked
