### ISSUE TITLE
about the requirements of GPU

### ISSUE THREAD

**Issue by louisinhit** [TimDettmers/bitsandbytes#21]
Currently I only have two types of GPUs:
 GP102 [GeForce GTX 1080 Ti] 
and
GM200GL [Tesla M40]

In this case I cannot use this library right?
Or could anyone tell me is this okay?

**Comment by louisinhit** [comment]
i fixed this problem thx.

**Comment by cipri-tom** [comment]
Can you please tell us how you solved it ? Thanks !
