### ISSUE TITLE
is is possible to perform accelerated int8 on pascal P4/P40 GPUs?

### ISSUE THREAD

**Issue by draplater** [TimDettmers/bitsandbytes#211]
according to https://developer.nvidia.com/blog/new-pascal-gpus-accelerate-inference-in-the-data-center/ , P4/P40 has IDP2A and IDP4A instructions provide 8-bit integer (INT8) 2- and 4-element vector dot product computations.

**Comment by shesung** [comment]
it would be great to ultilize the int8 acceleration on pascal cards. INT8 TOPS is 4x as of FP32 for 1080ti.
