### ISSUE TITLE
Improve documentation for conda installation and CUDA 11.8

### ISSUE THREAD

**Issue by JonasGeiping** [TimDettmers/bitsandbytes#212]
Hi, great repo!

I see a number of issues that other people have when trying to install bnb with CUDA support, and also had a small hick-up when installing this package from pip this week. 
I didn't see a solution mentioned in these issues when I looked at the problem, so here is one: 

The anaconda installation for PyTorch doesn't include `cudatoolkit` anymore, the official instructions are now 
```conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia```
This installation does not actually include nvcc and libcudart and so cannot install bitsandbytes. 

But installing the cudatoolkit in addition, directly from nvidia:
```
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
```
fixes any installation issues (or atleast mine on two machines).

This is in contrast to the current installation instructions, 
```The requirements can best be fulfilled by installing pytorch via anaconda. You can install PyTorch by following the ["Get Started"](https://pytorch.org/get-started/locally/) instructions on the official website.```
which describe that the basic pytorch installation should be enough.

**Comment by neilbGH** [comment]
I had the same problem and JonasGeiping's solution fixed it for me on Ubuntu.

**Comment by AkideLiu** [comment]
Though my issue is not directly related to this repository, I require cudatoolkit-dev==11.8 for package compilation. It seems NVIDIA has discontinued support for this package, and this thread is a perfect solution to my situation.

**Comment by JinhuaLiang** [comment]
that helps me a lot. Many thanks @JonasGeiping . It is caused by the difference between cudatoolkit v.s.s cuda-toolkit.

**Comment by Sid630** [comment]
> [JonasGeiping](/JonasGeiping)

thanks a lot man

**Comment by angadbajwa23** [comment]
Big help! Thanks!

**Comment by hungtrieu07** [comment]
Thanks a lot man
