### ISSUE TITLE
8BitAdamW and bitsandbytes.functional.create_dynamic_map

### ISSUE THREAD

**Issue by ArrowM** [TimDettmers/bitsandbytes#227]
Hello! 8BitAdamW has stopped working for Dreambooth since 0.36.0 (loss NaNs very quickly). I took a stab at reviewing [the differences between the releases](https://github.com/TimDettmers/bitsandbytes/compare/0.35.0...0.36.0). The if-block around `functional.py:218` in 2f2063bac212bcd6a515a88a12a9530b5730dabe may have been accidentally indented. `tests.test_functional.test_few_bit_quant` doesn't cover the inside of the if block, so maybe this was missed (or it was intentional and it'd be great to have confirmation). I'm hoping one of the maintainers can take a quick look. Thanks!

**Comment by feffy380** [comment]
I wonder if this is why I get loss=nan with the rocm port (which does include this commit). Have you tried un-indenting the block in question? It's in the python code so it shouldn't require recompilation.

**Comment by ArrowM** [comment]
Oh wow, you're right - I can test it pretty easily. It seemed to fix it!

**Comment by rationalism** [comment]
This should be fixed by 0.41.1
