### ISSUE TITLE
Required library version not found: libsbitsandbytes_cpu.so

### ISSUE THREAD

**Issue by Hazingoo** [TimDettmers/bitsandbytes#228]
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?

**Comment by ballix22** [comment]
Same problem
