### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'presets/Pygmalion.txt'

### ISSUE THREAD

**Issue by TachiG** [TimDettmers/bitsandbytes#242]
I don't know how any of this works, sorry if it doesn't help.

python server.py --share --model waifu-workshop_pygmalion-6b_sharded --settings settings-colab.json --no-stream --cai-chat --extensions gallery

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /usr/lib64-nvidia did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events')}
  warn(msg)
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('--listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https'), PosixPath('//colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-t4-s-2nwy7017in524 --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true')}
  warn(msg)
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
  warn(msg)
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('module'), PosixPath('//ipykernel.pylab.backend_inline')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /usr/local/lib/python3.9/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
2023-03-30 21:36:18.479034: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading settings from settings-colab.json...
Loading waifu-workshop_pygmalion-6b_sharded...
Loading checkpoint shards: 100% 7/7 [00:02<00:00,  3.10it/s]
Loaded the model in 65.06 seconds.
Loading the extension "gallery"... Ok.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/text-generation-webui/server.py:517 in <module>                     │
│                                                                              │
│   514 │   else:                                                              │
│   515 │   │   shared.gradio['interface'].launch(prevent_thread_lock=True, sh │
│   516                                                                        │
│ ❱ 517 create_interface()                                                     │
│   518                                                                        │
│   519 while True:                                                            │
│   520 │   time.sleep(0.5)                                                    │
│                                                                              │
│ /content/text-generation-webui/server.py:358 in create_interface             │
│                                                                              │
│   355 │   │   │   │   │   │   │   shared.gradio['chat_generation_attempts']  │
│   356 │   │   │   │   │   │   │   shared.gradio['check'] = gr.Checkbox(value │
│   357 │   │   │   │                                                          │
│ ❱ 358 │   │   │   │   create_settings_menus(default_preset)                  │
│   359 │   │   │                                                              │
│   360 │   │   │   function_call = 'chat.cai_chatbot_wrapper' if shared.args. │
│   361 │   │   │   shared.input_params = [shared.gradio[k] for k in ['textbox │
│                                                                              │
│ /content/text-generation-webui/server.py:163 in create_settings_menus        │
│                                                                              │
│   160 │   shared.gradio['save_prompt'].click(save_prompt, [shared.gradio['te │
│   161                                                                        │
│   162 def create_settings_menus(default_preset):                             │
│ ❱ 163 │   generate_params = load_preset_values(default_preset if not shared. │
│   164 │                                                                      │
│   165 │   with gr.Row():                                                     │
│   166 │   │   with gr.Column():                                              │
│                                                                              │
│ /content/text-generation-webui/server.py:94 in load_preset_values            │
│                                                                              │
│    91 │   │   'no_repeat_ngram_size': 0,                                     │
│    92 │   │   'early_stopping': False,                                       │
│    93 │   }                                                                  │
│ ❱  94 │   with open(Path(f'presets/{preset_menu}.txt'), 'r') as infile:      │
│    95 │   │   preset = infile.read()                                         │
│    96 │   for i in preset.splitlines():                                      │
│    97 │   │   i = i.rstrip(',').strip().split('=')                           │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'presets/Pygmalion.txt'

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
