### ISSUE TITLE
The following directories listed in your path were found to be non-existent [WSL2]

### ISSUE THREAD

**Issue by ZizoAdam** [TimDettmers/bitsandbytes#243]
Following https://github.com/tloen/alpaca-lora

When I attempt to run the finetuning code from it

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
\================================================================================
/home/USERNAME/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/USERNAME/.conda/envs/textgen/lib')}
  warn(msg)
/home/USERNAME/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/USERNAME/.conda/envs/textgen did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/USERNAME/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
/home/USERNAME/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary /home/USERNAME/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/USERNAME/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "

CUDA seems to be working as I followed nvidia's installation instructions and ran the sample program listed here https://ubuntu.com/tutorials/enabling-gpu-acceleration-on-ubuntu-on-wsl2-with-the-nvidia-cuda-platform#4-compile-a-sample-application

My card showed up as expected in the sample test so I would assume CUDA is working (version 12.1 was listed)

**Comment by JaredS215** [comment]
I am having a very similar issue, using WSL2.
/home/USERNAME/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/USERNAME/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
  warn(
/home/USERNAME/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /home/USERNAME/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/USERNAME/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!

CUDA is installed and works just fine with my Stable Diffusion install.

**Comment by JaredS215** [comment]
Looks like it's because of an issue with either WSL2 or Nvidia's CUDA installer.  https://github.com/microsoft/WSL/issues/5663
I was able to fix it by making a softlink.
`sudo ln -s /usr/lib/wsl/lib/libcuda.so /usr/local/cuda/lib64/libcuda.so`
