### ISSUE TITLE
Please help me in installing 7B my knowledge is not enough to solve this error.

### ISSUE THREAD

**Issue by RichardTLabble** [TimDettmers/bitsandbytes#254]
Installed via GPU and CPU. Please help me in installing 7B my knowledge is not enough to solve this error.

**Gpu - started, but gives an error**

File "E:\AI\oobabooga-windows\text-generation-webui\modules\[chat.py](https://chat.py/)", line 173, in cai_chatbot_wrapper

for _history in chatbot_wrapper(text, max_new_tokens, do_sample, temperature, top_p, typical_p, repetition_penalty, encoder_repetition_penalty, top_k, min_length, no_repeat_ngram_size, num_beams, penalty_alpha, length_penalty, early_stopping, seed, name1, name2, context, check, chat_prompt_size, chat_generation_attempts):

File "E:\AI\oobabooga-windows\text-generation-webui\modules\[chat.py](https://chat.py/)", line 144, in chatbot_wrapper

cumulative_reply = reply

UnboundLocalError: local variable 'reply' referenced before assignment

**CPU - ran but says no module.**

Running with the following flag call python [server.py](https://server.py/) --auto-devices --cai-chat --model alpaca-native-4bit --wbits 4 --groupsize 128 --no-stream

Please help.

Starting the web UI...

===================================BUG REPORT===================================

Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================

CUDA SETUP: Loading binary E:\AI\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...

E:\AI\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\[cextension.py:31](https://cextension.py:31/): UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.

warn("The installed version of bitsandbytes was compiled without GPU support. "

Loading alpaca-native-4bit...

Traceback (most recent call last):

File "E:\AI\one-click-installers-oobabooga-windows\text-generation-webui\[server.py](https://server.py/)", line 275, in <module>

shared.model, shared.tokenizer = load_model(shared.model_name)

File "E:\AI\one-click-installers-oobabooga-windows\text-generation-webui\modules\[models.py](https://models.py/)", line 100, in load_model

from modules.GPTQ_loader import load_quantized

File "E:\AI\one-click-installers-oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 13, in <module>

import llama_inference_offload

ModuleNotFoundError: No module named 'llama_inference_offload'

Press any key to continue . . .

**Comment by Mu2u** [comment]
hi how did you close this?
