### ISSUE TITLE
(1 min change) Could CUDA setup use logging instead of printing?

### ISSUE THREAD

**Issue by JulesGM** [TimDettmers/bitsandbytes#261]
Right now https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/cuda_setup/main.py#L138 prints instead of using standard logging, making it impossible to lower the verbosity of the library. It would be an easy change to implement.

**Comment by TimDettmers** [comment]
This would be a great feature! I would love to get a PR for this. Would you be able to work on this?
