### ISSUE TITLE
bug: OS call failed or operation not supported on NGC PyTorch

### ISSUE THREAD

**Issue by rapsealk** [TimDettmers/bitsandbytes#264]
Hello bitsandbytes!

Trying to import `bitsandbytes` on a docker container(which has been spawned from [nvcr.io/nvidia/pytorch:22.05-py3](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags)), it fails with errors.

Here is a full log:
```sh
======================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/extras/CUPTI/lib64'), PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/cuda/lib'), PosixPath('/usr/local/cuda-11.6/include')}
warn(msg)
CUDA exception! Error code: OS call failed or operation not supported on this OS
CUDA exception! Error code: initialization error
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
warn(msg)
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
warn("The installed version of bitsandbytes was compiled without GPU support. "
```

The first CUDA exception(`OS call failed or operation not supported on this OS`) is raised from:
https://github.com/TimDettmers/bitsandbytes/blob/49a04253fb1f3e195cb0e9e79bdb01db7a490774/bitsandbytes/cuda_setup/main.py#L313
and the other one(`initialization error`) is raised from:
https://github.com/TimDettmers/bitsandbytes/blob/49a04253fb1f3e195cb0e9e79bdb01db7a490774/bitsandbytes/cuda_setup/main.py#L335

To reproduce, just run the commands below:
```sh
$ pip install --upgrade pip
$ pip install bitsandbytes
$ python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitsandbytes
```

**Comment by TimDettmers** [comment]
Thank you for your report on this issues. Please install the newest version of bitsandbytes with `pip install -U bitsandbytes`. If that does not solve your error, please provide the output of `python -m bitsandbytes` so I can help you. Thank you!

**Comment by rapsealk** [comment]
@TimDettmers Thanks for the response! I tested with `bitsandbytes==0.38.0.post1` but it shows the same error.
I found something weird -- using `types.CDLL("libcudart.so")` for initialization raises an error but [`cuda-python`](https://github.com/NVIDIA/cuda-python) works fine.

```python
# Using libcudart.so
import ctypes

libcuda = ctypes.CDLL("libcuda.so")
libcudart = ctypes.CDLL("libcudart.so")

count = ctypes.c_int()

print(libcuda.cuInit(0))  # 0
print(libcudart.cudaGetDeviceCount(ctypes.byref(count)))  # 304
print(count.value)  # 0
```

```python
# Using cuda-python
from cuda import cuda, cudart

cuda.cuInit(0) # (<CUresult.CUDA_SUCCESS: 0>,)
cudart.cudaGetDeviceCount()  # (<cudaError_t.cudaSuccess: 0>, 1)
```

Question: Do you have a plan to use `cuda-python` inside `bitsandbytes`?

Here is a full log:
```sh
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cextension.py:29: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda-11.6/include'), PosixPath('/usr/local/cuda/extras/CUPTI/lib64'), PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/cuda/lib')}
  warn(msg)
CUDA exception! Error code: OS call failed or operation not supported on this OS
CUDA exception! Error code: initialization error
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
```

```sh
$ python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cextension.py:29: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/extras/CUPTI/lib64'), PosixPath('/usr/local/nvidia/lib64'), PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/cuda-11.6/include'), PosixPath('/usr/local/cuda/lib')}
  warn(msg)
CUDA exception! Error code: OS call failed or operation not supported on this OS
CUDA exception! Error code: initialization error
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.7/compat/lib.real/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/work/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
++++++++ /usr/local/cuda/compat/lib.real CUDA PATHS ++++++++
/usr/local/cuda/compat/lib.real/libcuda.so
+++++++++ /usr/include/x86_64-linux-gnu CUDA PATHS +++++++++

++++++++++ /usr/local/cuda/compat/lib CUDA PATHS +++++++++++

 /opt/conda/lib/python3.8/site-packages/torch_tensorrt/lib CUDA PATHS 

 /opt/conda/lib/python3.8/site-packages/torch/lib CUDA PATHS 
/opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so
/opt/conda/lib/python3.8/site-packages/torch/lib/libc10_cuda.so
/opt/conda/lib/python3.8/site-packages/torch/lib/libc10d_cuda_test.so
/opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++


++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = []
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

name 'str2optimizer32bit' is not defined

Above we output some debug information. Please provide this info when creating an issue via https://github.com/TimDettmers/bitsandbytes/issues/new/choose ...
```

**Comment by nbollman** [comment]
Sir I am also struggling with this issue, trying to run oobabooga 4bit quantized, but bitsandbytes doesn't seem to be installing with GPU support...  TheWall needs support from the oncoming corporate AI monsters...

(base) jonsnow@TheWall:~/Desktop/oobabooga_linux/text-generation-webui$ pip install -U bitsandbytes
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: bitsandbytes in /home/jonsnow/miniconda3/lib/python3.10/site-packages (0.38.1)
(base) jonsnow@TheWall:~/Desktop/oobabooga_linux/text-generation-webui$ python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /home/jonsnow/miniconda3 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: :/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/ did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/1986,unix/TheWall'), PosixPath('local/TheWall')}
  warn(msg)
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
  warn(msg)
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
  warn(msg)
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/7de58ba9_4e94_4f59_bada_cd52ed1c9126')}
  warn(msg)
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('path=/run/user/1000/bus,guid=a7cd23833d7dd2eee18d995e64516452'), PosixPath('unix')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(msg)
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/jonsnow/miniconda3/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/jonsnow/miniconda3/pkgs/pytorch-2.0.0-py3.10_cuda11.7_cudnn8.5.0_0/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/jonsnow/miniconda3/pkgs/pytorch-2.0.0-py3.10_cuda11.7_cudnn8.5.0_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/jonsnow/miniconda3/pkgs/pytorch-2.0.0-py3.10_cuda11.7_cudnn8.5.0_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/jonsnow/miniconda3/pkgs/icu-58.2-he6710b0_3/lib/libicudata.so
/home/jonsnow/miniconda3/pkgs/nsight-compute-2022.2.0.13-0/nsight-compute/2022.2.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/home/jonsnow/miniconda3/pkgs/nsight-compute-2022.2.0.13-0/nsight-compute/2022.2.0/target/linux-desktop-t210-a64/libcuda-injection.so
/home/jonsnow/miniconda3/pkgs/nsight-compute-2022.2.0.13-0/nsight-compute/2022.2.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/home/jonsnow/miniconda3/pkgs/cuda-cudart-dev-11.7.60-h6a7c232_0/lib/libcudart.so
/home/jonsnow/miniconda3/pkgs/cuda-driver-dev-11.7.60-0/lib/stubs/libcuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++


+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/jonsnow/Desktop/oobabooga_linux/text-generation-webui/repositories/GPTQ-for-LLaMa/build/lib.linux-x86_64-cpython-310/quant_cuda.cpython-310-x86_64-linux-gnu.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
 /home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/ CUDA PATHS 
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/jonsnow/miniconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = ['8.6']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

name 'str2optimizer32bit' is not defined

Above we output some debug information. Please provide this info when creating an issue via https://github.com/TimDettmers/bitsandbytes/issues/new/choose ...

**Comment by rapsealk** [comment]
@nbollman Have you installed CUDA Toolkit? It seems that your machine has no `libcudart.so`.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
