### ISSUE TITLE
Running on Docker

### ISSUE THREAD

**Issue by SupreethRao99** [TimDettmers/bitsandbytes#265]
Hello,

Trying to get bitsandbytes running on docker containers from Nvidia-container-registry has been an arduous experiment at best. Any tips to get bitsandbytes running on a container? I have tried installing from pip as well as from source to no avail

**Comment by krylm** [comment]
I had same problem: https://github.com/TimDettmers/bitsandbytes/issues/105

I was lucky with custom `deepspeed docker image` ( https://zzhou.info/2022/11/22/deepspeed_docker/ ) and even with `nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu20.04`
