### ISSUE TITLE
"TypedStorage is deprecated" What to do?

### ISSUE THREAD

**Issue by Jadiac5** [TimDettmers/bitsandbytes#267]
While setting up the web ui this is the text I get:

Starting the web UI...

CUDA SETUP: CUDA runtime path found: C:\Users\jadia\Desktop\P AI\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
C:\Users\jadia\Desktop\P AI\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary C:\Users\jadia\Desktop\P AI\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll...
Loading vicuna-13b-GPTQ-4bit-128g...
Loading model ...
C:\Users\jadia\Desktop\P AI\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\jadia\Desktop\P AI\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\jadia\Desktop\P AI\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Press any Button......

I get I don't have the newest GPU as seen by the Warning but what do I do to get rid of the "use tensor.untyped_storage() instead of tensor.storage()" and how do I fix this?

Thanks for any help in advance :)

Edit:
Weirdly this Crash dissapears and the program works as soon as I have more then one model downloaded...?
The Message still appears but now the programm starts.

**Comment by JustMentalMatt** [comment]
getting the same issue here, downloading another model however does not work for me.

**Comment by kanosy88** [comment]
same it does not work for me.
