### ISSUE TITLE
Could you give a code example on how to reproduce the results of  c4 perplexity as in the LLM.int8 paper?

### ISSUE THREAD

**Issue by MGLiXu** [TimDettmers/bitsandbytes#27]
I'm new to hugging face,  and I would be grateful if you can give me some hints on evaluate the c4 dataset or other dataset in you paper.

**Comment by TimDettmers** [comment]
I did the C4 evaluation in fairseq. More information on how to download the data you can find here: https://github.com/allenai/allennlp/discussions/5056

I used the last shard of the validation set. However, I believe for models that have not been trained on C4, you can use within HuggingFace transformers the [dataset streaming](https://huggingface.co/docs/datasets/v1.10.1/dataset_streaming.html) mode to stream arbitrary C4 data for the evaluation.

Let me know if you need more information.
