### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision'

### ISSUE THREAD

**Issue by candirsky** [TimDettmers/bitsandbytes#270]
Lama cleaner doesn't run after installing from the downloaded Windows installer.
Attaching the errors I get. Please help!
![01](https://user-images.githubusercontent.com/53260715/230657454-63d3bfb6-ef22-4dec-8b0e-f96e82bea3d2.png)
![02](https://user-images.githubusercontent.com/53260715/230657462-c7f4c982-82ba-4dbc-8260-4c44408751d8.png)

**Comment by TimDettmers** [comment]
Thank you for your report. This does not seem to be a problem with bitsandbytes, because bitsandbytes loads without any error. The error lies with another library. It seems the problem is related to not having installed the torchvision library. Please install it before you proceed.
