### ISSUE TITLE
SOLVED

### ISSUE THREAD

**Issue by mybloodywinter** [TimDettmers/bitsandbytes#272]
Sorry i'm not able to delete this

**Comment by lizelive** [comment]
just a note about how to use issues. deleteing a solved issue is a crime against humanity. what you do is add solution and mark it as closed. :cake:

**Comment by mybloodywinter** [comment]
> just a note about how to use issues. deleteing a solved issue is a crime against humanity. what you do is add solution and mark it as closed. 🍰

yes i'm sorry, i actually thought i was just being dumb and i missed dependencies so i got embarrassed and wanted to delete the issue lol... sorry.
but actually it wasn't that and it seems like i'm not the only one getting the same error so i'll create another issue for it later
