### ISSUE TITLE
Vicuna "typed storage deprecated" wont start up. How do i fix this? i am not very tech savvy. 

### ISSUE THREAD

**Issue by Bravenjbb** [TimDettmers/bitsandbytes#274]
When i start the bot using a start-web-ui.bat i get this: Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: C:\Users\dab1k\OneDrive\Desktop\New folder\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\dab1k\OneDrive\Desktop\New folder\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Loading model ...
C:\Users\dab1k\OneDrive\Desktop\New folder\oobabooga-windows\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\dab1k\OneDrive\Desktop\New folder\oobabooga-windows\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\dab1k\OneDrive\Desktop\New folder\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Press any key to continue . . .

After i press a button to continue, The program closes. Any help would be greatly appreciated.
![image_2023-04-08_140826816](https://user-images.githubusercontent.com/130245095/230736494-ab549280-c706-4044-92f2-f85e1f64a431.png)

**Comment by mugdul** [comment]
have that problem as well, anyone to help?

**Comment by LanSeDiQiu** [comment]
i have the same problem,how to fix it?
