### ISSUE TITLE
CUDA SETUP: Loading binary F:\Program Files (x86)\kohya\kohya_ss\venv\lib\site-

### ISSUE THREAD

**Issue by TYF369** [TimDettmers/bitsandbytes#275]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary F:\Program Files (x86)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 4000
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 4000
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 4000
steps:   0%|                                                                                  | 0/4000 [00:00<?, ?it/s]epoch 1/1
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Program Files (x86)\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\Program Files (x86)\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\Program Files (x86)\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\Program Files (x86)\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\Program Files (x86)\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=F:/Program Files (x86)/novelai-webui/novelai-webui-aki-v3/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=F:/Program Files (x86)/kohya/tyf_a', '--resolution=512,512', '--output_dir=F:/Program Files (x86)/kohya/out_model', '--logging_dir=', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=400', '--train_batch_size=1', '--max_train_steps=4000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bipolarisabuff** [comment]
i have this problem too

**Comment by dragononly** [comment]
同样的问题

**Comment by TYF369** [comment]
> D:\ai\tool\bitsandbytes\csrc\ops.cu 我电脑并没有这个路径， 但是报错显示这个路径？
如果是跟我一样的问题，把8位优化器那个 1改成0就行；如果是网页的那个训练的就该一个选项改成第一个就行。

**Comment by TYF369** [comment]
> 

把8位优化器那个 1改成0就行；如果是网页的那个训练的就该一个选项改成第一个就行。

**Comment by wanglingbusi** [comment]
> > 
> 
> 把8位优化器那个 1改成0就行；如果是网页的那个训练的就该一个选项改成第一个就行。

> # 优化器设置
$optimizer_type = "AdamW8bit" # Optimizer type | 优化器类型 默认为 8bitadam，可选：AdamW AdamW8bit Lion SGDNesterov SGDNesterov8bit DAdaptation AdaFactor

# LyCORIS 训练设置
/
/没有你说的那个选项啊

**Comment by TYF369** [comment]
> > > 
> > 
> > 
> > 把8位优化器那个 1改成0就行；如果是网页的那个训练的就该一个选项改成第一个就行。
> 
> > # 优化器设置
> 
> $optimizer_type = "AdamW8bit" # Optimizer type | 优化器类型 默认为 8bitadam，可选：AdamW AdamW8bit Lion SGDNesterov SGDNesterov8bit DAdaptation AdaFactor
> 
> # LyCORIS 训练设置
> / /没有你说的那个选项啊

另外一个网页的是这个选项
![QQ截图20230417231250](https://user-images.githubusercontent.com/65675024/232531314-98e6f931-8135-4e28-ad90-ccc84466b321.png)

**Comment by svip306666** [comment]
非常感谢

TYF369 ***@***.***> 於 2023年4月17日週一 下午10:16寫道：
