### ISSUE TITLE
No module named 'llama_inference_offload'

### ISSUE THREAD

**Issue by khanfar** [TimDettmers/bitsandbytes#286]
PLEASE HELP I GOT THIS ERROR :
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Traceback (most recent call last):
  File "E:\vicuna-chatgpt4\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\vicuna-chatgpt4\oobabooga-windows\text-generation-webui\modules\models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "E:\vicuna-chatgpt4\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
Press any key to continue . . .

**Comment by GeeksHaveBigDisks** [comment]
I've got the same problem. 
In case that would help the diagnostic : I've got a Win10 Pc with an AMD Ryzen proc and an AMD Radeon GPU too... so I've not chosen the "NVIDIA" option at the beginning of the installation.

**Comment by TimDettmers** [comment]
This is not a bitsandbytes issue. Please see #298 and #293.
