### ISSUE TITLE
 TypedStorage is deprecated.

### ISSUE THREAD

**Issue by LanSeDiQiu** [TimDettmers/bitsandbytes#291]
![无标题](https://user-images.githubusercontent.com/121764616/230965740-5513fa01-299b-4ab7-9ae4-125e44b11cde.png)

**Comment by TimDettmers** [comment]
Thank you for this report. bitsandbytes does not use `tensor.storage()` and as such it is likely an issue with a dependency. Maybe its related to a dependency in vicuna?
