### ISSUE TITLE
No module named 'llama_inference_offload'

### ISSUE THREAD

**Issue by AwesomeSmileee** [TimDettmers/bitsandbytes#293]
CUDA SETUP: Loading binary C:\Game\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
C:\Game\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading gpt4-x-alpaca-13b-native-4bit-128g...
Traceback (most recent call last):
  File "C:\Game\oobabooga-windows\text-generation-webui\server.py", line 347, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Game\oobabooga-windows\text-generation-webui\modules\models.py", line 101, in load_model
    from modules.GPTQ_loader import load_quantized
  File "C:\Game\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
Pressione qualquer tecla para continuar. . .

**Comment by AwesomeSmileee** [comment]
Windows 11
No GPU
i5 9500
24GB RAM

**Comment by TimDettmers** [comment]
Thank you for your report. This does not seem to be a problem with bitsandbytes, because bitsandbytes loads without any error. The error lies with another library. It seems the problem is related to `llama_inference_offload`. Please file an issue here: https://github.com/qwopqwop200/GPTQ-for-LLaMa
