### ISSUE TITLE
my error trace

### ISSUE THREAD

**Issue by Hulkhao** [TimDettmers/bitsandbytes#297]
CUDA SETUP: Loading binary C:\AIGC\kohya_ss_2023-03-02\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 120
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 65
  num epochs / epoch数: 5
  batch size per device / バッチサイズ: 2
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 300
steps:   0%|                                                                                   | 0/300 [00:00<?, ?it/s]epoch 1/5
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AIGC\kohya_ss_2023-03-02\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AIGC\kohya_ss_2023-03-02\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\AIGC\kohya_ss_2023-03-02\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\AIGC\kohya_ss_2023-03-02\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\AIGC\\kohya_ss_2023-03-02\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/AIGC/LoraPra/realisticVisionV20_v20.safetensors', '--train_data_dir=C:/AIGC/LoraPra/ddddyson_style/image', '--resolution=512,512', '--output_dir=C:/AIGC/LoraPra/ddddyson_style/model', '--logging_dir=C:/AIGC/LoraPra/ddddyson_style/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=ddddyson', '--lr_scheduler_num_cycles=5', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=30', '--train_batch_size=2', '--max_train_steps=300', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by TimDettmers** [comment]
You run a bitsandbytes version that is not compatible with your GPU. This can happen if you have multiple GPUs with different capabilities or multiple CUDA versions. Please follow this guide to solve the problem: https://github.com/TimDettmers/bitsandbytes/blob/main/errors_and_solutions.md

If you are still having a problem, try to remove multiple CUDA versions by looking at `python -m bitsandbytes` for multiple CUDA versions.

If you are still having problems after this, please open another issue.

**Comment by Hulkhao** [comment]
My cuda version is 121. Isn't it backward compatible with 116?

![image](https://img.gejiba.com/images/633bc901ac563dbaa5d4a6c45a786cad.png)

**Comment by Hulkhao** [comment]
<img src="https://img.gejiba.com/images/633bc901ac563dbaa5d4a6c45a786cad.png" alt="管理员 Windows PowerShe 230412 234312" border="0">

**Comment by Hulkhao** [comment]
Thank you for your enthusiastic reply.
I uninstalled all nVidia drivers, installed cuda11.6, and still reported an error.😔

![image](https://img.gejiba.com/images/3babd4d61490abd2a46db092c110717e.png)
