### ISSUE TITLE
RuntimeError: Unrecognized CachingAllocator option: max_split_size_mb=8000

### ISSUE THREAD

**Issue by Eikewi** [TimDettmers/bitsandbytes#306]
Hey, i get this error trying to start oobabooga/text-generation-webui can you help me to fix it? I have a RTX 3070 ti so i think Vram shouldn´t be a problem. But i am just guessing here.
![230769899-3a060055-9347-4001-9f6e-44784713f071](https://user-images.githubusercontent.com/107319316/231567774-05e69f46-ad7a-4507-ba88-a32e32a78779.png)

**Comment by TimDettmers** [comment]
This is not an error related to bitsandbytes since bitsandbytes load normally without any error. Please see here for more information: https://stackoverflow.com/questions/73747731/runtimeerror-cuda-out-of-memory-how-setting-max-split-size-mb

**Comment by Eikewi** [comment]
Thanks for the answer! Sadly the post didn´t help. I asked on the oobabooga github but they couldn´t help me neither. Do you have any other Tipp where i could find someone who knows how to deal with this?

**Comment by xiaocai2011** [comment]
I guess this should be an issue with the cache allocator, which I'm also running into when deploying other language models. I don't know exactly how to fix it, but I hope this will give you a direction.
