### ISSUE TITLE
CUDA out off memory  ?  What happen ? System full new ..

### ISSUE THREAD

**Issue by Mirkulix** [TimDettmers/bitsandbytes#307]
variance = hidden_states.to(torch.float32).pow(2).mean(-1, keepdim=True)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 7.06 GiB already allocated; 0 bytes free; 7.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 0.28 seconds (0.00 tokens/s, 0 tokens, context 500, seed 1597093298)

**Comment by TimDettmers** [comment]
Without more context, it is very difficult to say if this is a bitsandbytes problem or not. Can you post the full stack track?

**Comment by Mirkulix** [comment]
Also das Problem ist, wenn ich die die *.bat für die GPU starten reicht der zugewiesene Speicher der Grafikkarte nicht aus. 
Die entsprechende Zeile für ist die nachfolgende.  
call python server.py --auto-devices --chat --model anon8231489123_vicuna-13b-GPTQ-4bit-128g --wbits 4 --groupsize 128. 

Frage wie muss die Zeile  modifiziert werden das 2 x RTX 2070 super mit 8 GB angesteuert werden damit es nicht zu einem Speicherdefizit führt ?
