### ISSUE TITLE
CUDA setup fails when called by Kohya_ss, but looks fine when running python -m bitsandbytes on its own

### ISSUE THREAD

**Issue by ostapiuk** [TimDettmers/bitsandbytes#308]
I successfully built bitsandbytes from source to work with CUDA 12.1 using:
```
CUDA_VERSION=121 make cuda12x
CUDA_VERSION=121 make cuda12x_nomatmul
```
Then, with the kohya_ss venv active, I installed bitsandbytes using `python setup.py install`.  The directories and files were created within the venv hierarchy as expected.

When I try to train a LoRA using Kohya_ss, I get the following:
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================
bin /opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cpu.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Setup Failed!
```
I have already done everything suggested at the end of the error report and I only have CUDA 12.1 installed on my system and have never installed another version.  It is working with other applications.

However, if I run `python -m bitsandbytes` on its own from within the venv I get the following instead:
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================
bin /opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/opt/kohya_ss/bitsandbytes/bitsandbytes/libbitsandbytes_cuda121.so
/opt/kohya_ss/bitsandbytes/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/opt/kohya_ss/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda121.so
/opt/kohya_ss/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cu.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.0.post2-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121.so
/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.0.post2-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++


++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.9']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

I understand that this could be a Kohya_ss issue, but would appreciate any insight you might have as to why bitsandbytes would think I have no GPU support when called by Kohya_ss' scripts.  If it is something with bitsandbytes, I'd be happy to run any test you need.

**Comment by TimDettmers** [comment]
The solution is to add cuda to your `LD_LIBRARY_PATH`. Add this to your .bashrc.
```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<PATH to CUDA>/lib64
export PATH=$PATH:<PATH to CUDA>/bin
```

**Comment by ostapiuk** [comment]
I already had that in my .bashrc:

```
export LD_LIBRARY_PATH="/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export CUDA_HOME="/usr/local/cuda"
export CUDA_PATH="${CUDA_HOME}/bin"
export PATH="${CUDA_PATH}${PATH:+:${PATH}}"
export CUDA_VISIBLE_DEVICES=0
```

**Comment by svip306666** [comment]
我的也是这种情况
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary G:\ChromeD\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 5700
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 2850
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 2850
steps:   0%|                                                                                  | 0/2850 [00:00<?, ?it/s]epoch 1/1
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\ChromeD\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "G:\ChromeD\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "G:\ChromeD\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "G:\ChromeD\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\ChromeD\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=G:/ChromeD/stable-diffusion-webui-master/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors', '--train_data_dir=G:/ChromeD/kohya/loratrain/image', '--resolution=512,512', '--output_dir=G:/ChromeD/kohya/loratrain/model', '--logging_dir=G:/ChromeD/kohya/loratrain/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=285', '--train_batch_size=2', '--max_train_steps=2850', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by FrankChu0229** [comment]
same here

**Comment by ostapiuk** [comment]
Just a little more information - if I invoke the Python interactive shell from within the Kohya venv and I import bitsandbytes, it correctly picks up on my environment variables:
```python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

================================================================================
bin /opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121.so
```
So clearly my environment variables are setup correctly and can be read from the venv and it recognizes that I've compiled bitsandbytes against CUDA 12.1.  The question is why bitsandbytes is failing when called from Kohya?  It should be noted that I'm having the exact same problem when trying to run oobabooga.

I'm setting up Kohya to run in PyCharm to do a deep dive as time allows.  If I find out anything more I'll pass it on...

**Comment by ostapiuk** [comment]
I found something interesting.  If I enter the python interpreter from within the kohya venv and ask `torch` whether CUDA is available I get:
```python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```
However, when running kohya I set a breakpoint in bitsandbytes/cextension.py on line 11 just after `setup` is initialized and stepped through code until I ended up in bitsandbytes/cuda_setup/main.py on line 379.  In the python debugger I checked what torch has to say about CUDA and I get:
```python
> /opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/cuda_setup/main.py(379)evaluate_cuda_setup()
-> if not torch.cuda.is_available(): return 'libbitsandbytes_cpu.so', None, None, None, None
(Pdb) p torch.cuda.is_available()
False
```
So `torch` *might* be the culprit here.  But I still have no idea why it would report differently in these two scenarios within the same venv.

To be sure I was using the same version of `torch` I ran `print(torch.__version__)` in both scenarios and in both cases it returned `1.12.1+cu116`.

**Comment by ostapiuk** [comment]
I never found the problem with the code I started with.  However, in the last week there were updates to bitsandbytes, kohya-ss/sd-scripts, and bmaltais/kohya-ss.  So I started with a fresh install of bmaltais/kohya-ss.

Here is how I got things working on my system (Kubuntu 22.04):

## Prerequisites
I'm not sure if all these elements are required, but just in case, here is what I have installed on my system:
* Nvidia driver 530.30.02
* [CUDA 12.1](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local)
* [cuDNN 8.9](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html)

## Install Kohya-ss GUI
1. Remove or rename old installation of Kohya-ss GUI or sd-scripts.  Then clone the current version of the repository.
```shell
git clone https://github.com/bmaltais/kohya_ss
```

2. Go to the kohya-ss directory created by the last step and activate the Python virtual environment:
```shell
source venv/bin/activate
```

*The next steps are different from the instructions on [bmaltais/kohya_ss](https://github.com/bmaltais/kohya_ss)*.

3. Install PyTorch.  Since PyTorch doesn't yet directly support CUDA 12.1 (cu121), I chose the latest version which supports CUDA 11.8 (cu118).
```shell
pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
```

4. Install Dependencies
```shell
pip install --upgrade -r requirements.txt
```
You will see the following error in red text. It is safe to ignore as it will be corrected after installing xformers:
```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.14.dev0 requires pyre-extensions==0.0.23, which is not installed.
```

5. Install `xformers`
```shell
pip install -U xformers
```

6. Configure `accelerate`
```shell
accelerate config
```
These are the answers I gave to the questions:
* *In which compute environment are you running?* => **This machine**
* *Which type of machine are you using?* => **No distributed training**
* *Do you want to run your training on CPU only (even if a GPU is available)?* => **no**
* *Do you wish to optimize your script with torch dynamo?* => **no**
* *Do you want to use DeepSpeed?* => **no**
* *What GPU(s) (by id) should be used for training on this machine as a comma-seperated list?* => **0** (rather than `all`, I provided the specific ID of my GPU, which can be found by running `nvidia-smi`, though it will typically be `0` for most consumer systems.
* **Do you wish to use FP16 or BF16 (mixed precision)?** => **bf16**


7. Ensure that there is a compatible version of `bitsandbytes` installed.  The latest bmaltais/kohya_ss appears to have pre-built binaries for everything up to CUDA 12.1.  Look in the directory *kohya-ss/venv/lib/python3.10/site-packages/bitsandbytes* and ensure that you have `libbitsandbytes_cuda121.so` and `libbitsandbytes_cuda121_nocublaslt.so`.  If not, you will have to [build them](https://github.com/TimDettmers/bitsandbytes#compile-from-source) and copy the files over to kohya-ss.


I hope this helps anyone else struggling to get this working.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by sesopenko** [comment]
>     7. Ensure that there is a compatible version of `bitsandbytes` installed.  The latest bmaltais/kohya_ss appears to have pre-built binaries for everything up to CUDA 12.1.  Look in the directory _kohya-ss/venv/lib/python3.10/site-packages/bitsandbytes_ and ensure that you have `libbitsandbytes_cuda121.so` and `libbitsandbytes_cuda121_nocublaslt.so`.  If not, you will have to [build them](https://github.com/TimDettmers/bitsandbytes#compile-from-source) and copy the files over to kohya-ss.
> 
> 
> I hope this helps anyone else struggling to get this working.

I'm also running into this issue, compiled bitsandbytes, installed it in the venv.  But when I run gui.sh it overwrites the bitsandbytes compiled from scratch:

```
15:00:33-987391 INFO     Version: v22.4.0                                                    
                                                                                             
15:00:33-990830 INFO     nVidia toolkit detected                                             
15:00:34-833778 INFO     Torch 2.1.2+cu121                                                   
15:00:34-843372 INFO     Torch backend: nVidia CUDA 12.1 cuDNN 8902                          
15:00:34-852517 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10007 Arch (8, 6)  
                         Cores 68                                                            
15:00:34-853589 INFO     Verifying modules installation status from                          
                         /home/sean/kohya_ss/requirements_linux.txt...                       
15:00:34-854791 WARNING  Package wrong version: xformers 0.0.23.post1 required 0.0.21        
15:00:34-855615 INFO     Installing package: xformers==0.0.21 bitsandbytes==0.41.1           
15:01:33-096359 INFO     Installing package: tensorboard==2.14.1 tensorflow==2.14.0          
15:01:59-363350 INFO     Verifying modules installation status from requirements.txt...      
15:02:01-260980 INFO     headless: False                                                     
15:02:01-263940 INFO     Load CSS...                  
```

**Comment by sesopenko** [comment]
@ostapiuk 's advice mostly worked, but I had to comment out the lines in `gui.sh` which attempt to install the requirements because it was downgrading various packages.  

```bash
# don't validate the requirements because the environment needs to be a little special. This is commented out:
## Validate the requirements and run the script if successful
#if python "$SCRIPT_DIR/setup/validate_requirements.py" -r "$REQUIREMENTS_FILE"; then
#    "${STARTUP_CMD}" $STARTUP_CMD_ARGS "$SCRIPT_DIR/kohya_gui.py" "$@"
#fi

# just go straight to starting up.
"${STARTUP_CMD}" $STARTUP_CMD_ARGS "$SCRIPT_DIR/kohya_gui.py" "$@"
```

**Comment by LoRAMilkshake** [comment]
> I never found the problem with the code I started with. However, in the last week there were updates to bitsandbytes, kohya-ss/sd-scripts, and bmaltais/kohya-ss. So I started with a fresh install of bmaltais/kohya-ss.
> 
> Here is how I got things working on my system (Kubuntu 22.04):
> ## Prerequisites
> 
> I'm not sure if all these elements are required, but just in case, here is what I have installed on my system:
> 
>     * Nvidia driver 530.30.02
> 
>     * [CUDA 12.1](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local)
> 
>     * [cuDNN 8.9](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html)
> 
> 
> ## Install Kohya-ss GUI
> 
>     1. Remove or rename old installation of Kohya-ss GUI or sd-scripts.  Then clone the current version of the repository.
> 
> 
> ```shell
> git clone https://github.com/bmaltais/kohya_ss
> ```
> 
>     2. Go to the kohya-ss directory created by the last step and activate the Python virtual environment:
> 
> 
> ```shell
> source venv/bin/activate
> ```
> 
> _The next steps are different from the instructions on [bmaltais/kohya_ss](https://github.com/bmaltais/kohya_ss)_.
> 
>     3. Install PyTorch.  Since PyTorch doesn't yet directly support CUDA 12.1 (cu121), I chose the latest version which supports CUDA 11.8 (cu118).
> 
> 
> ```shell
> pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
> ```
> 
>     4. Install Dependencies
> 
> 
> ```shell
> pip install --upgrade -r requirements.txt
> ```
> 
> You will see the following error in red text. It is safe to ignore as it will be corrected after installing xformers:
> 
> ```shell
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> xformers 0.0.14.dev0 requires pyre-extensions==0.0.23, which is not installed.
> ```
> 
>     5. Install `xformers`
> 
> 
> ```shell
> pip install -U xformers
> ```
> 
>     6. Configure `accelerate`
> 
> 
> ```shell
> accelerate config
> ```
> 
> These are the answers I gave to the questions:
> 
>     * _In which compute environment are you running?_ => **This machine**
> 
>     * _Which type of machine are you using?_ => **No distributed training**
> 
>     * _Do you want to run your training on CPU only (even if a GPU is available)?_ => **no**
> 
>     * _Do you wish to optimize your script with torch dynamo?_ => **no**
> 
>     * _Do you want to use DeepSpeed?_ => **no**
> 
>     * _What GPU(s) (by id) should be used for training on this machine as a comma-seperated list?_ => **0** (rather than `all`, I provided the specific ID of my GPU, which can be found by running `nvidia-smi`, though it will typically be `0` for most consumer systems.
> 
>     * **Do you wish to use FP16 or BF16 (mixed precision)?** => **bf16**
> 
> 
>     7. Ensure that there is a compatible version of `bitsandbytes` installed.  The latest bmaltais/kohya_ss appears to have pre-built binaries for everything up to CUDA 12.1.  Look in the directory _kohya-ss/venv/lib/python3.10/site-packages/bitsandbytes_ and ensure that you have `libbitsandbytes_cuda121.so` and `libbitsandbytes_cuda121_nocublaslt.so`.  If not, you will have to [build them](https://github.com/TimDettmers/bitsandbytes#compile-from-source) and copy the files over to kohya-ss.
> 
> 
> I hope this helps anyone else struggling to get this working.

I'm using CUDA 12.0 on my Debian 12 installation, but when I run the setup.sh script, Kohya install 11.8 libraries and after I try to run the GUI, a legend on the console says "Could not find cuda drivers on your machine, GPU will not be used"
