### ISSUE TITLE
Has anyone tried this library with stablediffusion? 

### ISSUE THREAD

**Issue by amrrs** [TimDettmers/bitsandbytes#31]
I'm just curious if anyone's tried this library for quantization with stable diffusion models?

**Comment by TimDettmers** [comment]
I believe people use it to fine-tune diffusion models, but stable diffusion would not benefit from LLM.int8() much since most of its memory comes from the activation and not from the 16-bit weights.

**Comment by amrrs** [comment]
Thank you Tim
