### ISSUE TITLE
Does anyone have any idea on the llama library

### ISSUE THREAD

**Issue by mynewopportunities** [TimDettmers/bitsandbytes#312]
I have a pending installation, it has blocked my disk space and I have an unsorted  / unresolved issue. Can someone please give me more info on the llama library?

How to download it? Where to install it? Etc.

I opened an issue yesterday, but it was abruptly closed, without even taking a confirmation from me. Please kindly suggest, what exactly needs to be done.
[Error.File.txt](https://github.com/TimDettmers/bitsandbytes/files/11221152/Error.File.txt)

**Comment by maria-mh07** [comment]
I don't have much idea but bitsandbytes requires a Linux distribution, maybe part of your problem is there. 

In this link https://helpdesk.microsurvey.com/index.php?/Knowledgebase/Article/View/1631/209/loadlibrary-failed-with-error-1114-a-dynamic-link-library-dll-initialization-routine-failed `OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed` error was explained.

**Comment by moiziom786110** [comment]
Hi Maria-mh07, thanks for the reply, but I am afraid it didn't work at all. I changed the settings of the graphic card to best performance, but it gave me an additional error which I have attached hereby. Pleaser review it and let me know if you have any inputs.

Thank You.
[Vicuna Error File.txt](https://github.com/TimDettmers/bitsandbytes/files/11232126/Vicuna.Error.File.txt)

**Comment by moiziom786110** [comment]
This is the error what I get and the model does not start -

Traceback (most recent call last):
File “C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py”, line 54, in _load_shared_library
return ctypes.CDLL(str(lib_path))
File "C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\installer_files\env\lib\ctypes_init.py", line 374, in init
self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\text-generation-webui\[server.py](http://server.py/)”, line 84, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 107, in load_model
from modules.llamacpp_model_alternative import LlamaCppModel
File “C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\text-generation-webui\modules\llamacpp_model_alternative.py”, line 9, in
from llama_cpp import Llama
File “C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp_init_.py”, line 1, in
from .llama_cpp import *
File “C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py”, line 67, in
_lib = _load_shared_library(_lib_base_name)
File “C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py”, line 56, in _load_shared_library
raise RuntimeError(f"Failed to load shared library ‘{_lib_path}’: {e}")
RuntimeError: Failed to load shared library ‘C:\Users\Moiz Contractor\Desktop\AI\oobabooga-windows\installer_files\env\Lib\site-packages\llama_cpp\llama.dll’: [WinError 1114] A dynamic link library (DLL) initialization routine failed
