### ISSUE TITLE
ModuleNotFoundError: No module named 'triton.ops.matmul_perf_model'

### ISSUE THREAD

**Issue by remarkableJ** [TimDettmers/bitsandbytes#328]
![image](https://user-images.githubusercontent.com/45261220/233063722-b61b9ce2-c7a7-41fc-b8ed-0115221a95c7.png)
![image](https://user-images.githubusercontent.com/45261220/233063860-c9c68977-9574-4e84-93ab-7d4b28245b03.png)
![image](https://user-images.githubusercontent.com/45261220/233063934-c6fc1c5a-6d94-4893-92b2-6c386999b898.png)

**Comment by sfernandes-gim** [comment]
Hi , is there a resolution on this?

**Comment by geekinglcq** [comment]
The problelm is caused by the low-version triton. `triton.ops.matmul_perf_model` only support the `trition>=v1.1.1`. 
Upgrading it by `pip install -U triton` could fix it.

**Comment by AbhayGoyal** [comment]
still need to be addressed

**Comment by candlewill** [comment]
I have met the same error when using triton 3.2.0

**Comment by candlewill** [comment]
Update: I downgrade triton to 3.1.0, solved the problem.

**Comment by seyyaw** [comment]
> Update: I downgrade triton to 3.1.0, that solved the problem.

Yes, Thank you @candlewill this helps.
This is what I specifically did:

```pip install --force-reinstall -v "triton==3.1.0"```

**Comment by hychiang-git** [comment]
triton 3.1.0 works for me, but pytorch 2.6 now requires triton 3.2.0. Would this be fixed? Is there a workaround for this issue in triton 3.2.0?

**Comment by hychiang-git** [comment]
> triton 3.1.0 works for me, but pytorch 2.6 now requires triton 3.2.0. Would this be fixed? Is there a workaround for this issue in triton 3.2.0?

I found a merged PR https://github.com/bitsandbytes-foundation/bitsandbytes/pull/1413  that addresses the issue.

**Comment by flankechen** [comment]
> triton 3.1.0 works for me, but pytorch 2.6 now requires triton 3.2.0. Would this be fixed? Is there a workaround for this issue in triton 3.2.0?

same issue, currently cant found a way to solve. downgrade to 3.1.0 and hopefully other packages not complaining.
