### ISSUE TITLE
BUG REPORT INFORMATION

### ISSUE THREAD

**Issue by z0911k** [TimDettmers/bitsandbytes#344]
bin /home/zhanglijun/anaconda3/envs/LLM/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/zhanglijun/anaconda3/envs/LLM/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /home/zhanglijun/anaconda3/envs/LLM did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/zhanglijun/anaconda3/envs/LLM/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('$ LD_LIBRARY_PATH ')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.3/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 5.2
CUDA SETUP: Detected CUDA version 113
/home/zhanglijun/anaconda3/envs/LLM/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/zhanglijun/anaconda3/envs/LLM/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so...

**Comment by lizelive** [comment]
set your LD_LIBRARY_PATH

**Comment by z0911k** [comment]
How should I set up LD_LIBRARY_PATH

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
