### ISSUE TITLE
add support for CUDA 11.8 in windows wheel

### ISSUE THREAD

**Issue by wqp89324** [TimDettmers/bitsandbytes#356]
I installed bitsandbytes with the windows wheel from here: https://github.com/acpopescu/bitsandbytes/releases

However, it is clear from release notes and error messages after running "python -m bitsandbytes" that CUDA 11.8 is not yet supported. Could you please add support for CUDA 11.8 in the windows wheel? Many thanks!

**Comment by ShanGor** [comment]
May you try to build from source on Windows, this post has a guide and fork that can be built on windows to fit your machine and CUDA version
ref to https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1595924414
