### ISSUE TITLE
Does LoRA + 8bit support multi GPU (single node) training?

### ISSUE THREAD

**Issue by shreyansh26** [TimDettmers/bitsandbytes#366]
I am trying to finetune a FlanT5-Large model on a dataset using LoRA + INT8. I was able to run my training script fine using a single GPU with `load_in_8bit=True, device_map="auto"`. 

I am using HF Trainer, so I just used `python -m torch.distributed.launch` with my script and other params to make it work with multiple GPUs but it gave an error

```
ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [1], output_device 1, and module parameters {device(type='cuda', index=0), device(type='cuda', index=1)}.
```

If I try using only LoRA (without 8-bit) and a smaller model - FlanT5-Base - I was able to run multi GPU training just fine with my script and  `python -m torch.distributed.launch`.

I don't see any other difference between the two runs except `load_in_8bit=True, device_map="auto"` and the smaller model. So is it something to do with `load_in_8bit=True, device_map="auto"`?

Edit: Doing LoRA and INT8 using PEFT.

**Comment by GeneZC** [comment]
The same applies with llama.

**Comment by SparkJiao** [comment]
Hi, may I know have you solved the problem? Thanks very much!

**Comment by shreyansh26** [comment]
Nope

**Comment by cassianlewis** [comment]
Not just a LORA problem - I've had the same problem when trying to use `load_in_8bit=True, device_map="auto"` by itself when multi-GPU training. I believe it's to do with which devices are specified during loading of the model (ie device_map = 'auto' not working correctly)

**Comment by simhallq** [comment]
Any fixes for this issues yet?

**Comment by Suelimbo** [comment]
I'm having the same issue too. Any solution so far?

**Comment by Vincent-Li-9701** [comment]
I think it has been addressed in a recent update with https://github.com/huggingface/transformers/issues/21736. But in this case, you are only running on naive model parallel which is very slow. Distributed Data Parallel with torchrun works but the trainer seems to have some issues with saving checkpoint when I tried it. The ckpt it saves doesn't match the performance so you have to write your own saving method.

**Comment by prince-css** [comment]
does anyone have any solution for this issue?

**Comment by tedbrun1** [comment]
Any update ?

**Comment by vampirismtrueblood** [comment]
Same issue here
