### ISSUE TITLE
Please Add Support For Windows

### ISSUE THREAD

**Issue by MilesQLi** [TimDettmers/bitsandbytes#373]
Because my supervisor don't plan to install Linux on our servers.

**Comment by Timotheeee** [comment]
You can try this https://github.com/acpopescu/bitsandbytes/releases
although I have no idea what cuda version it needs, and it's not 11.8

**Comment by ShanGor** [comment]
May you try to build from source on Windows, this post has a guide and fork that can be built on windows to fit your machine and CUDA version
ref to https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1595924414
