### ISSUE TITLE
Please clarify scope of this repository

### ISSUE THREAD

**Issue by rickardp** [TimDettmers/bitsandbytes#376]
I just noticed that all the portability PRs were closed and the main branch was forced pushed to some other branch yesterday. @TimDettmers  From issue #252:

> [...] It would be good to hear from the maintainers that they are at all interested in making this package cross-platform. It is very much CUDA focused at the moment.

It seems there are a few possible contributors who could help with ensuring portability, but I believe @TimDettmers  you are the sole maintainer of this repository and it is your decision how portable you want this library to be. I take the closing of the PRs as kind of statement you are not interested in supporting Windows/macOS here (as well as no AMD GPUs etc)? If you find some time, maybe just clarifying this would be good.

As a person who is interested in the portable version of the code, I would obviously prefer it we could collaborate on a port here, but if you are not interested it is totally understandable, and I'll just go ahead breaking out the stuff I need to a new library and porting it to M1 (which I already started BTW). @TheStoneMX, @acpopescu and others if you are interested on collaborating on this I'm very open to this, just know it's not my day job to work with this :)

**Comment by AiswaryaSrinivas** [comment]
Hi @rickardp , Just wanted to check, if a library that supports macOs would be released any time soon?? It would be great to have support for Apple Silicon
