### ISSUE TITLE
Confusing project homepage

### ISSUE THREAD

**Issue by tomaarsen** [TimDettmers/bitsandbytes#38]
Hello!

The `bitsandbytes` Project Homepage as displayed on https://pypi.org/project/bitsandbytes/ does not make much sense: it points to http://packages.python.org/bitsandbytes, which is not accessible.

I would expect this URL to point to either https://github.com/TimDettmers/bitsandbytes or https://bitsandbytes.readthedocs.io/en/latest/ (although the latter feels like it's left over from the outdated facebookresearch repo).

It would involve changing this line:
https://github.com/TimDettmers/bitsandbytes/blob/9b5f2eda8fbd3f042c4af7ed1b870525d4668f2a/setup.py#L27

- Tom Aarsen

**Comment by TimDettmers** [comment]
Thanks for pointing this out!
