### ISSUE TITLE
"No GPU detected!" Error Content

### ISSUE THREAD

**Issue by LuckyyySTA** [TimDettmers/bitsandbytes#381]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /home/path/to/username/.conda/envs/panda did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/lib/wsl/lib'), PosixPath('/home/path/to/cuda_path/cuda/11.6.0/libnsight'), PosixPath('/home/path/to/cuda_path/cuda/11.6.0/libnvvp')}
  warn(msg)
Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
CUDA SETUP: CUDA runtime path found: /home/path/to/cuda_path/cuda/11.6.0/lib64/libcudart.so.11.0
/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x_nomatmul
python setup.py install
Traceback (most recent call last):
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/path/to/username/.conda/envs/panda/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**my detailed env is below(run `python -m torch.utils.collect_env`):**
PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Kylin Linux Advanced Server V10 (Sword) (aarch64)
GCC version: (gcc for openEuler 2.3.3) 10.3.1
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.9.16 (main, Mar  8 2023, 10:36:36)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.90-24.4.v2101.ky10.aarch64-aarch64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB

Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.2.4
/usr/lib64/libcudnn_adv_infer.so.8.2.4
/usr/lib64/libcudnn_adv_train.so.8.2.4
/usr/lib64/libcudnn_cnn_infer.so.8.2.4
/usr/lib64/libcudnn_cnn_train.so.8.2.4
/usr/lib64/libcudnn_ops_infer.so.8.2.4
/usr/lib64/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**my .bashrc**
export CUDA_HOME=/home/path/to/cuda_path/cuda/cuda-11.6
export PATH=$PATH:$CUDA_HOME/bin
export LD_LIBRARY_PATH=$CUDA_HOME/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

**Comment by dayL-W** [comment]
I run 
export CUDA_HOME=/home/path/to/cuda_path/cuda/cuda-11.6
export PATH=$PATH:$CUDA_HOME/bin
export LD_LIBRARY_PATH=$CUDA_HOME/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}} 

but error still appear

help

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
