### ISSUE TITLE
CUDA Setup failed despite GPU being available. Please run the following command to get more information

### ISSUE THREAD

**Issue by GromZhang** [TimDettmers/bitsandbytes#387]
# python -m bitsandbytes

===================================BUG REPORT=================================== 
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes
 
 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbyt
es/issues
================================================================================
bin /home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/cuda_setup/main.py:145: UserWarning: /root/anaconda
3/envs/glm-lora did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! S
earching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.1/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 121
/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: Compu
te capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU! 
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda121_nocublaslt.so. Maybe you need to 
compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so... 

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed 
2. CUDA not installed
3. You have multiple conflicting CUDA libraries 
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for exa 
mple, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via 
 `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source: 
git clone git@github.com:TimDettmers/bitsandbytes.git 
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install 
CUDA SETUP: Setup Failed! 
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes 
CUDA_VERSION=121_nomatmul 
python setup.py install
Traceback (most recent call last):
  File "/root/anaconda3/envs/glm-lora/lib/python3.8/runpy.py", line 185, in _run_module_as_main 
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error) 
  File "/root/anaconda3/envs/glm-lora/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/root/anaconda3/envs/glm-lora/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name) 
  File "/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn 
  File "/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/research/nn/__init__.py", line 1, in <modul
e>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/research/nn/modules.py", line 8, in <module
>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/grom/llm/GLM/GLM-LoRA/bitsandbytes/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more infor
mation:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add
 them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsand
bytes 
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by GromZhang** [comment]
please help me

**Comment by hicaoc** [comment]
Perhaps bitsandbytes does not support CUDA 12.1

**Comment by shhuangcoder** [comment]
I use cuda==113 is work

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
