### ISSUE TITLE
HFValidationError: Repo id must be in the form 'repo_name' or  'namespace/repo_name': '/path/to/vicuna/weights/'. Use `repo_type` argument if  needed.

### ISSUE THREAD

**Issue by explorerJi** [TimDettmers/bitsandbytes#398]
HFValidationError: Repo id must be in the form 'repo_name' or 
'namespace/repo_name': '/path/to/vicuna/weights/'. Use `repo_type` argument if 
needed.
<img width="1270" alt="image" src="https://github.com/TimDettmers/bitsandbytes/assets/126233847/33727fd9-f4a0-4de2-b13d-ff3fd01bd828">

**Comment by lealdino** [comment]
Also the same error here.
