### ISSUE TITLE
Cannot detect cuda and ModuleNotFoundError: No module named 'triton.ops.matmul_perf_model'

### ISSUE THREAD

**Issue by SingL3** [TimDettmers/bitsandbytes#401]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /mnt/data/conda/envs/pythia_ft/lib/libcudart.so.11.0
/mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary /mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "/mnt/data/conda/envs/pythia_ft/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/mnt/data/conda/envs/pythia_ft/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/mnt/data/conda/envs/pythia_ft/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 15, in <module>
    from .nn import modules
  File "/mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/mnt/data/conda/envs/pythia_ft/lib/python3.9/site-packages/bitsandbytes/triton/dequantize_rowwise.py", line 12, in <module>
    from triton.ops.matmul_perf_model import early_config_prune, estimate_matmul_time
ModuleNotFoundError: No module named 'triton.ops.matmul_perf_model'

**Comment by SingL3** [comment]
I created another conda env and ran successfully. I think this is caused by the version of triton, which is not specified in requirement or code.

**Comment by l241025097** [comment]
’triton.ops.matmul_perf_model‘ is part of triton == 2.0.0，please check your triton version.

**Comment by SingL3** [comment]
I see, I am using deepspeed and that need triton==1.0.0
