### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by psych0v0yager** [TimDettmers/bitsandbytes#415]
Good evening.

I was running the jupyter notebook found here inside huggingface peft. I have a Tesla P40 24gb
https://github.com/huggingface/peft/blob/main/examples/int8_training/Finetune_opt_bnb_peft.ipynb

I received the following traceback:

RuntimeError                              Traceback (most recent call last)
Cell In[6], line 22
      6 trainer = transformers.Trainer(
      7     model=model, 
      8     train_dataset=data['train'],
   (...)
     19     data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False)
     20 )
     21 model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
---> 22 trainer.train()

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/transformers/trainer.py:1664](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/transformers/trainer.py:1664), in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1659     self.model_wrapped = self.model
   1661 inner_training_loop = find_executable_batch_size(
   1662     self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size
   1663 )
-> 1664 return inner_training_loop(
   1665     args=args,
   1666     resume_from_checkpoint=resume_from_checkpoint,
   1667     trial=trial,
   1668     ignore_keys_for_eval=ignore_keys_for_eval,
   1669 )

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/transformers/trainer.py:1940](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/transformers/trainer.py:1940), in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1938         tr_loss_step = self.training_step(model, inputs)
   1939 else:
-> 1940     tr_loss_step = self.training_step(model, inputs)
   1942 if (
   1943     args.logging_nan_inf_filter
   1944     and not is_torch_tpu_available()
   1945     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   1946 ):
   1947     # if loss is nan or inf simply add the average of previous logged losses
   1948     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/transformers/trainer.py:2745](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/transformers/trainer.py:2745), in Trainer.training_step(self, model, inputs)
   2742     loss = loss / self.args.gradient_accumulation_steps
   2744 if self.do_grad_scaling:
-> 2745     self.scaler.scale(loss).backward()
   2746 elif self.use_apex:
   2747     with amp.scale_loss(loss, self.optimizer) as scaled_loss:

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/_tensor.py:487](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/_tensor.py:487), in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/__init__.py:200](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/__init__.py:200), in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/function.py:274](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/function.py:274), in BackwardCFunction.apply(self, *args)
    270     raise RuntimeError("Implementing both 'backward' and 'vjp' for a custom "
    271                        "Function is not allowed. You should only implement one "
    272                        "of them.")
    273 user_fn = vjp_fn if vjp_fn is not Function.vjp else backward_fn
--> 274 return user_fn(self, *args)

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/utils/checkpoint.py:157](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/utils/checkpoint.py:157), in CheckpointFunction.backward(ctx, *args)
    153 if len(outputs_with_grad) == 0:
    154     raise RuntimeError(
    155         "none of output has requires_grad=True,"
    156         " this checkpoint() is not necessary")
--> 157 torch.autograd.backward(outputs_with_grad, args_with_grad)
    158 grads = tuple(inp.grad if isinstance(inp, torch.Tensor) else None
    159               for inp in detached_inputs)
    161 return (None, None) + grads

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/__init__.py:200](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/__init__.py:200), in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/function.py:274](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/torch/autograd/function.py:274), in BackwardCFunction.apply(self, *args)
    270     raise RuntimeError("Implementing both 'backward' and 'vjp' for a custom "
    271                        "Function is not allowed. You should only implement one "
    272                        "of them.")
    273 user_fn = vjp_fn if vjp_fn is not Function.vjp else backward_fn
--> 274 return user_fn(self, *args)

File [~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:476](https://vscode-remote+ssh-002dremote-002b10-002e0-002e0-002e69.vscode-resource.vscode-cdn.net/home/server_runner/Desktop/IanPrograms/IanTests/LangchainAgents/~/anaconda3/envs/bullshitenv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:476), in MatMul8bitLt.backward(ctx, grad_output)
    474 elif state.CB is not None:
    475     CB = state.CB.to(ctx.dtype_A, copy=True).mul_(state.SCB.unsqueeze(1).mul(1.0 / 127.0))
--> 476     grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx.dtype_A)
    477 elif state.CxB is not None:
    478     CB = (
    479         undo_layout(state.CxB, state.tile_indices)
    480         .to(ctx.dtype_A)
    481         .mul_(state.SCB.unsqueeze(1).mul(1.0 / 127.0))
    482     )

RuntimeError: expected scalar type Half but found Float

**Comment by tathagata-raha** [comment]
Got the same error from this notebook: https://huggingface.co/dfurman/falcon-7b-chat-oasst1/blob/main/finetune_falcon7b_oasst1_with_bnb_peft.ipynb

Can anyone help?
