### ISSUE TITLE
Could not find module 'C:\Users\bruno\anaconda3\envs\gpu-env\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by brunoedcf** [TimDettmers/bitsandbytes#424]
My log:

binary_path: C:\Users\bruno\anaconda3\envs\gpu-env\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\bruno\anaconda3\envs\gpu-env\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'C:\Users\bruno\anaconda3\envs\gpu-env\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Loading binary C:\Users\bruno\anaconda3\envs\gpu-env\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'C:\Users\bruno\anaconda3\envs\gpu-env\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
C:\Users\bruno\anaconda3\envs\gpu-env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
  
  
  
But when I run "nvcc --version" 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:15:10_Pacific_Standard_Time_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

My environment variables are:

CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2'

I am using anaconda navigator + jupyterLab and Windows OS

**Comment by jllllll** [comment]
Windows uses CUDA_PATH. Ensure that variable is set to your toolkit version. Also make sure that you do not have the 11.6 `cudart64_110.dll` installed in your Conda env.
