### ISSUE TITLE
unexpected keyword argument 'load_in_4bit' 

### ISSUE THREAD

**Issue by cosimoiaia** [TimDettmers/bitsandbytes#428]
I'm trying to replicate the results from the qlora repo, I have the latest version of bitsandbites but it seems the option is not available yes, I even compiled from source.

CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/cosimo/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
loading base model pythia-1b...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/cosimo/projects/LLM/qlora/qlora.py:758 in <module>                                         │
│                                                                                                  │
│   755 │   │   │   fout.write(json.dumps(all_metrics))                                            │
│   756                                                                                            │
│   757 if __name__ == "__main__":                                                                 │
│ ❱ 758 │   train()                                                                                │
│   759                                                                                            │
│                                                                                                  │
│ /home/cosimo/projects/LLM/qlora/qlora.py:590 in train                                            │
│                                                                                                  │
│   587 │   if completed_training:                                                                 │
│   588 │   │   print('Detected that training was already completed!')                             │
│   589 │                                                                                          │
│ ❱ 590 │   model = get_accelerate_model(args, checkpoint_dir)                                     │
│   591 │   training_args.skip_loading_checkpoint_weights=True                                     │
│   592 │                                                                                          │
│   593 │   model.config.use_cache = False                                                         │
│                                                                                                  │
│ /home/cosimo/projects/LLM/qlora/qlora.py:263 in get_accelerate_model                             │
│                                                                                                  │
│   260 │                                                                                          │
│   261 │   print(f'loading base model {args.model_name_or_path}...')                              │
│   262 │   compute_dtype = (torch.float16 if args.fp16 else (torch.bfloat16 if args.bf16 else t   │
│ ❱ 263 │   model = AutoModelForCausalLM.from_pretrained(                                          │
│   264 │   │   args.model_name_or_path,                                                           │
│   265 │   │   load_in_4bit=args.bits == 4,                                                       │
│   266 │   │   load_in_8bit=args.bits == 8,                                                       │
│                                                                                                  │
│ /home/cosimo/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:467 in │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   464 │   │   │   )                                                                              │
│   465 │   │   elif type(config) in cls._model_mapping.keys():                                    │
│   466 │   │   │   model_class = _get_model_class(config, cls._model_mapping)                     │
│ ❱ 467 │   │   │   return model_class.from_pretrained(                                            │
│   468 │   │   │   │   pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs,   │
│   469 │   │   │   )                                                                              │
│   470 │   │   raise ValueError(                                                                  │
│                                                                                                  │
│ /home/cosimo/.local/lib/python3.10/site-packages/transformers/modeling_utils.py:2611 in          │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   2608 │   │   │   init_contexts.append(init_empty_weights())                                    │
│   2609 │   │                                                                                     │
│   2610 │   │   with ContextManagers(init_contexts):                                              │
│ ❱ 2611 │   │   │   model = cls(config, *model_args, **model_kwargs)                              │
│   2612 │   │                                                                                     │
│   2613 │   │   # Check first if we are `from_pt`                                                 │
│   2614 │   │   if use_keep_in_fp32_modules:                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: GPTNeoXForCausalLM.__init__() got an unexpected keyword argument 'load_in_4bit'

**Comment by cosimoiaia** [comment]
Additional Info:

I made sure to have the latest version: 

cosimo@prometheus:~/projects/LLM/qlora$ pip3 install -U bitsandbytes
Requirement already satisfied: bitsandbytes in /home/cosimo/.local/lib/python3.10/site-packages (0.39.0)

**Comment by Sap98** [comment]
I am also getting error while using load_in_4bit=True using bitsandbytes
