### ISSUE TITLE
cuda11.2 and bitsandbytes-0.39 or 0.26 are not compatible??

### ISSUE THREAD

**Issue by Nicole19960319** [TimDettmers/bitsandbytes#429]
if i installed bitsandbytes_cuda112-0.26.0.post2-py3-none-any.whl

The error would be "AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'"

Then if i installed bitsandbytes-0.39.0-py3

The error would be "CUDA Setup failed despite GPU being available #396"

Please help!

**Comment by bbecausereasonss** [comment]
I'm on Cuda 117 in WSl and getting same error. 

AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'
