### ISSUE TITLE
I'm trying to use bitandbytes with hugginface but get this error

### ISSUE THREAD

**Issue by david-hung** [TimDettmers/bitsandbytes#439]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ubuntu/VIPR/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ubuntu/VIPR/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/lib/wsl/lib')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 115
/home/ubuntu/VIPR/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/ubuntu/VIPR/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.5/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.5/nsight-compute-2021.3.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.5/nsight-compute-2021.3.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.5/nsight-compute-2021.3.1/target/linux-desktop-t210-a64/libcuda-injection.so

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/VIPR/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/ubuntu/VIPR/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 60, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*so')
  File "/home/ubuntu/VIPR/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by s-ahmad461** [comment]
Hi @TimDettmers,

Getting this error even after upgrading bitsandbytes.
I am using bitsandbytes==0.41.1

**OS Information:**
    NAME="Amazon Linux"
    VERSION="2"
    ID="amzn"
    ID_LIKE="centos rhel fedora"
    VERSION_ID="2"
    PRETTY_NAME="Amazon Linux 2"
    ANSI_COLOR="0;33"
    CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
    HOME_URL="https://amazonlinux.com/"


```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.7/nsight-compute-2022.2.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.7/nsight-compute-2022.2.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.7/nsight-compute-2022.2.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.6/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.6/nsight-compute-2022.1.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.6/nsight-compute-2022.1.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.6/nsight-compute-2022.1.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.5/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.5/nsight-compute-2021.3.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.5/nsight-compute-2021.3.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.5/nsight-compute-2021.3.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.4/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.4/nsight-compute-2021.2.2/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.4/nsight-compute-2021.2.2/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.4/nsight-compute-2021.2.2/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.3/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.3/nsight-compute-2021.1.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.3/nsight-compute-2021.1.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.3/nsight-compute-2021.1.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.2/nsight-compute-2020.3.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.2/nsight-compute-2020.3.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.2/nsight-compute-2020.3.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.1/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.1/nsight-compute-2020.2.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.1/nsight-compute-2020.2.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.1/nsight-compute-2020.2.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.0/nsight-compute-2020.1.2/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.0/nsight-compute-2020.1.2/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.0/nsight-compute-2020.1.2/target/linux-desktop-t210-a64/libcuda-injection.so

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 96, in <module>
    generate_bug_report_information()
  File "/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 60, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*so')
  File "/home/ec2-user/anaconda3/envs/trials.ai/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?
```

**Comment by 202030481266** [comment]
@s-ahmad461 I fix this question by running as root because the script will use the command "find" so if you are not root then it will return error.

**Comment by s-ahmad461** [comment]
@202030481266 , thanks this worked...

**Comment by cristianohello** [comment]
@202030481266 
你好，我在V100下量化百川2-13B的int8量化，还是报错？用了root权限。
File "/home/ec2-user/anaconda3/envs/<env>/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by cristianohello** [comment]
@s-ahmad461 
hi, How do you solve it?

**Comment by Christoph-XJ** [comment]
mark

**Comment by s-ahmad461** [comment]
Hi... @cristianohello.
You can either run 
```shell
python -m bitsandbytes
``` 
in a directory having no system files. Like create a directory navigate into it and then run the command or you can run the command as superuser as suggested by @202030481266

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
