### ISSUE TITLE
4090 gpu 10%

### ISSUE THREAD

**Issue by songkea** [TimDettmers/bitsandbytes#441]
python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda121.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda121.so...
Loading THUDM/chatglm-6b...

The GPU only uses 10%, and the inference operation feels that the CPU is running. After checking the CPU and memory, the CPU occupies 1%, the single logic core is 100%, and the mem 128g only uses 40g. Have you ever encountered such a problem

**Comment by TimDettmers** [comment]
What workload are you running? For inference with batch size 1, it is typically that the GPU only uses 0.1% of the max FLOPS of a tensor core. It seems you are also running a small model with 6B parameters. As such, these numbers are in line with usual utilization.
