### ISSUE TITLE
Incorrect compute capability for A6000 GPU

### ISSUE THREAD

**Issue by petersandev** [TimDettmers/bitsandbytes#448]
Hi,
On my rack I have two GPUs: A6000 and GT1030,  Nevertheless, I got the warning "Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!" 

Also, during run I receive the following print:
CUDA SETUP: Highest compute capability among GPUs detected: 6.1

But the A6000 compute capability is 8.6. 

Is this the reason I cannot train a model, which runs on 15GB T4? I receive CUDA out of memory with batch size of 1 although I have 48GB memory.

Thank you very much.

Here is the debug report:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/access/venvs/nlp_311/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/access/venvs/nlp_311/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/access/miniconda3/lib/libcudart.so.11.0'), PosixPath('/home/access/miniconda3/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/access/miniconda3/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 118
/home/access/venvs/nlp_311/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/access/venvs/nlp_311/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/access/miniconda3/lib/libcudart.so
/home/access/miniconda3/envs/ffcv_310/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/envs/ffcv_310/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/envs/ffcv_310/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/envs/ffcv_310/lib/libcudart.so
/home/access/miniconda3/envs/ffcv_310/lib/libicudata.so
/home/access/miniconda3/envs/dbnet/lib/libcudart.so
/home/access/miniconda3/envs/ffcv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cu.so
/home/access/miniconda3/envs/ffcv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/envs/ffcv/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/envs/ffcv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/access/miniconda3/envs/ffcv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/envs/ffcv/lib/libcudart.so
/home/access/miniconda3/envs/ffcv/lib/libicudata.so
/home/access/miniconda3/envs/ffcv_py39/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cu.so
/home/access/miniconda3/envs/ffcv_py39/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/envs/ffcv_py39/lib/python3.9/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/envs/ffcv_py39/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/access/miniconda3/envs/ffcv_py39/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/envs/ffcv_py39/lib/libcudart.so
/home/access/miniconda3/envs/ffcv_py39/lib/libicudata.so
/home/access/miniconda3/pkgs/cuda-cudart-dev-11.7.99-0/lib/libcudart.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-cuda112py39hb0b7ed5_200/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-cuda112py39hb0b7ed5_200/lib/python3.9/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-cuda112py39hb0b7ed5_200/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/pkgs/cudatoolkit-11.7.0-hd8887f6_11/lib/libcudart.so
/home/access/miniconda3/pkgs/icu-58.2-he6710b0_3/lib/libicudata.so
/home/access/miniconda3/pkgs/cudatoolkit-11.8.0-h37601d7_11/lib/libcudart.so
/home/access/miniconda3/pkgs/cudatoolkit-11.3.1-h9edb442_11/lib/libcudart.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cu.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/pkgs/rmm-23.02.00-cuda11_py310_g48e8f2a8_0/lib/python3.10/site-packages/rmm/_lib/cuda_stream.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cudatoolkit-11.3.1-h2bc3f7f_2/lib/libcudart.so
/home/access/miniconda3/pkgs/icu-70.1-h27087fc_0/lib/libicudata.so
/home/access/miniconda3/pkgs/cuda-driver-dev-11.7.99-0/lib/stubs/libcuda.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/_cuda/ccuda.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/_lib/ccudart/ccudart.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/ccuda.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/ccudart.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/cudart.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/cuda.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/tests/test_ccudart.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cuda-python-11.8.1-py310h01a121a_2/lib/python3.10/site-packages/cuda/tests/test_ccuda.cpython-310-x86_64-linux-gnu.so
/home/access/miniconda3/pkgs/cudatoolkit-11.6.0-hecad31d_10/lib/libcudart.so
/home/access/miniconda3/pkgs/cudatoolkit-11.2.2-hbe64b41_10/lib/libcudart.so
/home/access/miniconda3/pkgs/cudatoolkit-11.3.1-h9edb442_10/lib/libcudart.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.10_cuda11.3_cudnn8.3.2_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cu.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.10_cuda11.3_cudnn8.3.2_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.10_cuda11.3_cudnn8.3.2_0/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.10_cuda11.3_cudnn8.3.2_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.10_cuda11.3_cudnn8.3.2_0/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.9_cuda11.3_cudnn8.3.2_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cu.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.9_cuda11.3_cudnn8.3.2_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.9_cuda11.3_cudnn8.3.2_0/lib/python3.9/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.9_cuda11.3_cudnn8.3.2_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/access/miniconda3/pkgs/pytorch-1.12.1-py3.9_cuda11.3_cudnn8.3.2_0/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-cuda112py310he33e0d6_200/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-cuda112py310he33e0d6_200/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/access/miniconda3/pkgs/pytorch-1.13.1-cuda112py310he33e0d6_200/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/access/miniconda3/pkgs/nsight-compute-2022.4.1.6-0/nsight-compute/2022.4.1/target/linux-desktop-t210-a64/libcuda-injection.so
/home/access/miniconda3/pkgs/nsight-compute-2022.4.1.6-0/nsight-compute/2022.4.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/home/access/miniconda3/pkgs/nsight-compute-2022.4.1.6-0/nsight-compute/2022.4.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/home/access/miniconda3/pkgs/cudatoolkit-10.1.243-h6bb024c_0/lib/libcudart.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
++++++++++ /usr/local/cuda-11.8/lib64 CUDA PATHS +++++++++++

++ /home/access/Downloads/TensorRT-8.5.2.2/lib CUDA PATHS ++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.6', '6.1']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!

(nlp_311) (base) access@TRX40:/data1/peter_projects/llm_tolkien$ python
Python 3.11.3 (main, Apr  5 2023, 14:15:06) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> for i in range(torch.cuda.device_count()):
...    print(torch.cuda.get_device_properties(i).name)
... 
NVIDIA RTX A6000
NVIDIA GeForce GT 1030
>>>

**Comment by petersandev** [comment]
I was just able to run the code on another machine with a single 3090 GPU. On it I got the right compute capability: 8.6.  It has CUDA 11.7 installed, though I do not think that is the issue. I think the dual GPU is the issue.

**Comment by USBhost** [comment]
I have one A6000 pared with a A4000 and I do not have this problem. But then again both have the same compute version.

**Comment by TimDettmers** [comment]
I believe this is fixed in the newest bitsandbytes release. Could you please check if it works without setting CUDA_VISIBLE_DEVICES?
