### ISSUE TITLE
problem with wsl and cuda 12.1

### ISSUE THREAD

**Issue by gutama** [TimDettmers/bitsandbytes#449]
Hi, 

I have tried to check all my config,  I am running ubuntu 22.04 on WSL2

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/libbitsandbytes_cpu.so
False
Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

ginanjar@alfarabi:~/gitrepo/bitsandbytes$ ldconfig -p | grep libcuda
        libcudart.so.12 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12
        libcudart.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so
        libcuda.so.1 (libc6,x86-64) => /usr/lib/wsl/lib/libcuda.so.1
        libcuda.so (libc6,x86-64) => /usr/lib/wsl/lib/libcuda.so

ginanjar@alfarabi:~/gitrepo/bitsandbytes$ echo $LD_LIBRARY_PATH
:/usr/local/cuda-12.1/targets/x86_64-linux/lib/:/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/

ginanjar@alfarabi:~/gitrepo/bitsandbytes$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
ginanjar@alfarabi:~/gitrepo/bitsandbytes$ nvidia-smi
Sun May 28 10:51:53 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 531.14       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060 w...    On | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P8                5W /  N/A|     10MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        32      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+

ginanjar@alfarabi:~/repositories/cuda-samples/Samples/1_Utilities/deviceQuery$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA GeForce RTX 2060 with Max-Q Design"
  CUDA Driver Version / Runtime Version          12.1 / 12.1
  CUDA Capability Major/Minor version number:    7.5
  Total amount of global memory:                 6144 MBytes (6442123264 bytes)
  (030) Multiprocessors, (064) CUDA Cores/MP:    1920 CUDA Cores
  GPU Max Clock rate:                            1185 MHz (1.18 GHz)
  Memory Clock rate:                             5501 Mhz
  Memory Bus Width:                              192-bit
  L2 Cache Size:                                 3145728 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 

And I still got the following error when running text-generation-webui

ginanjar@alfarabi:~/gitrepo/text-generation-webui$ python3 server.py
INFO:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:NumExpr defaulting to 8 threads.
INFO:Gradio HTTP request redirected to localhost :)
bin /home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

the folder already contains all the lib, but it is not loaded
ginanjar@alfarabi:~/.local/lib/python3.10/site-packages/bitsandbytes$ ls -l
total 272208
-rw-r--r-- 1 ginanjar ginanjar      670 May 28 10:12 __init__.py
-rw-r--r-- 1 ginanjar ginanjar     3992 May 28 10:12 __main__.py
drwxr-xr-x 2 ginanjar ginanjar     4096 May 28 10:12 __pycache__
drwxr-xr-x 3 ginanjar ginanjar     4096 May 28 10:12 autograd
-rw-r--r-- 1 ginanjar ginanjar     1633 May 28 10:12 cextension.py
drwxr-xr-x 3 ginanjar ginanjar     4096 May 28 10:12 cuda_setup
-rw-r--r-- 1 ginanjar ginanjar    77332 May 28 10:12 functional.py
-rwxr-xr-x 1 ginanjar ginanjar    45456 May 28 10:12 libbitsandbytes_cpu.so
-rwxr-xr-x 1 ginanjar ginanjar  7968480 May 28 10:12 libbitsandbytes_cuda111.so
-rwxr-xr-x 1 ginanjar ginanjar 20566416 May 28 10:12 libbitsandbytes_cuda111_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar  8152704 May 28 10:12 libbitsandbytes_cuda112.so
-rwxr-xr-x 1 ginanjar ginanjar 21090608 May 28 10:12 libbitsandbytes_cuda112_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar  8267392 May 28 10:12 libbitsandbytes_cuda113.so
-rwxr-xr-x 1 ginanjar ginanjar 21401904 May 28 10:12 libbitsandbytes_cuda113_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar  8357840 May 28 10:12 libbitsandbytes_cuda115.so
-rwxr-xr-x 1 ginanjar ginanjar 21496448 May 28 10:12 libbitsandbytes_cuda115_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar  8189904 May 28 10:12 libbitsandbytes_cuda116.so
-rwxr-xr-x 1 ginanjar ginanjar 21328512 May 28 10:12 libbitsandbytes_cuda116_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar  8157448 May 28 10:12 libbitsandbytes_cuda117.so
-rwxr-xr-x 1 ginanjar ginanjar 21304240 May 28 10:12 libbitsandbytes_cuda117_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar 13318712 May 28 10:12 libbitsandbytes_cuda118.so
-rwxr-xr-x 1 ginanjar ginanjar 23164136 May 28 10:12 libbitsandbytes_cuda118_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar 12945784 May 28 10:12 libbitsandbytes_cuda120.so
-rwxr-xr-x 1 ginanjar ginanjar 22422568 May 28 10:12 libbitsandbytes_cuda120_nocublaslt.so
-rwxr-xr-x 1 ginanjar ginanjar  7954832 May 28 10:14 libbitsandbytes_cuda121.so
-rwxr-xr-x 1 ginanjar ginanjar 22426664 May 28 10:12 libbitsandbytes_cuda121_nocublaslt.so
drwxr-xr-x 3 ginanjar ginanjar     4096 May 28 10:12 nn
drwxr-xr-x 3 ginanjar ginanjar     4096 May 28 10:12 optim
drwxr-xr-x 5 ginanjar ginanjar     4096 May 28 10:12 research
drwxr-xr-x 3 ginanjar ginanjar     4096 May 28 10:12 triton
-rw-r--r-- 1 ginanjar ginanjar     7499 May 28 10:12 utils.py

I am also able to run make cuda12x

ginanjar@alfarabi:~/gitrepo/bitsandbytes/build/lib/bitsandbytes$ ls -l
total 7892
-rw-r--r-- 1 root root     670 May 27 10:27 __init__.py
-rw-r--r-- 1 root root    3992 May 18 16:27 __main__.py
drwxr-xr-x 2 root root    4096 May 27 11:59 autograd
-rw-r--r-- 1 root root    1633 May 27 10:27 cextension.py
drwxr-xr-x 2 root root    4096 May 27 11:59 cuda_setup
-rw-r--r-- 1 root root   77332 May 27 10:27 functional.py
-rwxr-xr-x 1 root root 7954832 May 28 09:14 libbitsandbytes_cuda121.so
drwxr-xr-x 2 root root    4096 May 27 11:59 nn
drwxr-xr-x 2 root root    4096 May 27 11:59 optim
drwxr-xr-x 4 root root    4096 May 27 11:59 research
drwxr-xr-x 2 root root    4096 May 27 11:59 triton
-rw-r--r-- 1 root root    7499 May 27 10:27 utils.py

Any clue to make the lib loaded?  
Thank you very much

**Comment by gutama** [comment]
Solved the problem just by asking chatgpt,  this is wierd   :)

If you're experiencing issues with the CUDA library shared object not being loaded in your Ubuntu 22.04 environment running on WSL2, there are a few steps you can take to troubleshoot and resolve the problem. Here's what you can try:

1. Verify CUDA Installation: Make sure CUDA is properly installed on your system. You can check if the CUDA toolkit is installed by running the following command in your terminal:
   ```
   nvcc --version
   ```

   If CUDA is installed, you should see the version information. If it's not installed, you'll need to install the CUDA toolkit appropriate for your system.

2. Verify CUDA Environment Variables: Ensure that the necessary environment variables are correctly set. Open your shell configuration file (e.g., `~/.bashrc`, `~/.zshrc`, etc.) and check if the following lines are present:
   ```
   export PATH=/usr/local/cuda/bin:$PATH
   export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
   ```

   If they are missing, add them to the file and save it. Then, reload the shell configuration by running:
   ```
   source ~/.bashrc
   ```

   Alternatively, you can manually set the environment variables in your terminal session by running the `export` commands mentioned above.

3. Verify CUDA Library Path: Confirm that the CUDA library path is correct. In your terminal, run the following command:
   ```
   echo $LD_LIBRARY_PATH
   ```

   This command will display the current value of the `LD_LIBRARY_PATH` environment variable. Ensure that it includes the path to the CUDA libraries (e.g., `/usr/local/cuda/lib64`). If it's missing, you can set it using the `export` command mentioned in the previous step.

4. Check Library Compatibility: Ensure that the CUDA library version you're trying to load is compatible with your CUDA toolkit version. If you're using a third-party library or application that requires CUDA, make sure it's built against the same CUDA version you have installed.

5. Restart WSL: Sometimes, restarting the WSL2 instance can help resolve issues related to library loading. You can do this by closing your WSL2 terminal and then reopening it.

6. Update CUDA: If you have an older version of CUDA installed, consider updating to the latest version. You can download the CUDA toolkit from the official NVIDIA website and follow the installation instructions.

7. Verify WSL2 Compatibility: Ensure that your WSL2 installation is properly configured and compatible with CUDA. Check the official Microsoft documentation for any known issues or limitations related to CUDA in WSL2.

By following these steps, you should be able to resolve issues related to the CUDA library shared object not being loaded in your Ubuntu 22.04 environment running on WSL2.




================================


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/ginanjar/.triton/cache/218fc9fb29e449716291a4bf5f858920/cuda_utils.so
/home/ginanjar/gitrepo/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda121.so
/home/ginanjar/gitrepo/bitsandbytes/bitsandbytes/libbitsandbytes_cuda121.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/cudart.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/tests/test_ccuda.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/tests/test_ccudart.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/ccudart.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/_lib/ccudart/ccudart.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/cuda.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/_cuda/ccuda.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/cuda/ccuda.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/.local/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/ginanjar/.local/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/ginanjar/.local/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ginanjar/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/ginanjar/.local/lib/python3.10/site-packages/quant_cuda-0.0.0-py3.10-linux-x86_64.egg/quant_cuda.cpython-310-x86_64-linux-gnu.so
/home/ginanjar/repositories/GPTQ-for-LLaMa/build/lib.linux-x86_64-3.10/quant_cuda.cpython-310-x86_64-linux-gnu.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++


++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['7.5']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
