### ISSUE TITLE
Crash on training

### ISSUE THREAD

**Issue by Airburner** [TimDettmers/bitsandbytes#45]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.0
CUDA SETUP: Detected CUDA version 111
CUDA SETUP: Loading binary /usr/local/lib/python3.7/dist-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so...
Steps:   2% 21/1400 [00:48<45:43,  1.99s/it, loss=0.0183, lr=5e-6]Traceback (most recent call last):
  File "train_dreambooth.py", line 606, in <module>
    main()
  File "train_dreambooth.py", line 527, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 357, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "train_dreambooth.py", line 268, in __getitem__
    instance_image = Image.open(self.instance_images_path[index % self.num_instance_images])
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/content/data/Paula/.ipynb_checkpoints'
Steps:   2% 21/1400 [00:48<53:19,  2.32s/it, loss=0.0183, lr=5e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/content/data/Paula', '--class_data_dir=/content/data/woman', '--output_dir=/content/models/PaulaOut', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=Paulina Gajewska', '--class_prompt=woman', '--seed=1393795', '--resolution=512', '--center_crop', '--train_batch_size=1', '--mixed_precision=no', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=12', '--sample_batch_size=4', '--max_train_steps=1400']' returned non-zero exit status 1.

**Comment by ZeroCool22** [comment]
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64... CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so CUDA SETUP: Highest compute capability among GPUs detected: 6.0 CUDA SETUP: Detected CUDA version 111 CUDA SETUP: Loading binary /usr/local/lib/python3.7/dist-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so... Steps: 2% 21/1400 [00:48<45:43, 1.99s/it, loss=0.0183, lr=5e-6]Traceback (most recent call last): File "train_dreambooth.py", line 606, in main() File "train_dreambooth.py", line 527, in main for step, batch in enumerate(train_dataloader): File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 357, in **iter** next_batch = next(dataloader_iter) File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in **next** data = self._next_data() File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data data = self._dataset_fetcher.fetch(index) # may raise StopIteration File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "train_dreambooth.py", line 268, in **getitem** instance_image = Image.open(self.instance_images_path[index % self.num_instance_images]) File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open fp = builtins.open(filename, "rb") IsADirectoryError: [Errno 21] Is a directory: '/content/data/Paula/.ipynb_checkpoints' Steps: 2% 21/1400 [00:48<53:19, 2.32s/it, loss=0.0183, lr=5e-6] Traceback (most recent call last): File "/usr/local/bin/accelerate", line 8, in sys.exit(main()) File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main args.func(args) File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command simple_launcher(args) File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/content/data/Paula', '--class_data_dir=/content/data/woman', '--output_dir=/content/models/PaulaOut', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=Paulina Gajewska', '--class_prompt=woman', '--seed=1393795', '--resolution=512', '--center_crop', '--train_batch_size=1', '--mixed_precision=no', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=12', '--sample_batch_size=4', '--max_train_steps=1400']' returned non-zero exit status 1.

Same error and no one helps...

**Comment by TimDettmers** [comment]
This does not seem to be a bitsandbytes error. The stack trace points to accelerate. Am I missing something?

**Comment by TimDettmers** [comment]
Please continue the discussion in #46.
