### ISSUE TITLE
Will bitsandbytes implement QLoRA?

### ISSUE THREAD

**Issue by taomanwai** [TimDettmers/bitsandbytes#455]
QLORA: Efficient Finetuning of Quantized LLMs
https://arxiv.org/abs/2305.14314

**Comment by tabacof** [comment]
QLoRA is already implemented in bitsandbytes. If you refer to QLoRA's [repository](https://github.com/artidoro/qlora), you will see it's essentially just combining bitsandbytes + PEFT + transformers + accelerate, the latter three being libraries by Hugging Face.

**Comment by tabacof** [comment]
>can I use bitsandbytes with out huggingface or transfermers(package)? could you provide more docs resources for using bitsandbytes in other model?

I'm not involved in any way with bitsandbytes but my understanding is that that's not possible unless you make some changes yourself to whatever framework you want to use. I'm saying this because bitsandbytes's made changes to Hugging Face (hence why you need to install the latest version on the repo).

**Comment by TimDettmers** [comment]
QLoRA is the following  method: 
1. Replace Linear layers with `bnb.nn.Linear4bit`
2. Use PEFT or another LoRA implementation to apply LoRA adapters to all layers of a transformer
3. Train your model.

As such, bitsandbytes has all the components. As @tabacof correctly says, the qlora repo implements all these steps. These steps cannot be broken down further. One can change the abstractions by not using huggingface transformers and accelerate and by not using PEFT. But you can create such an implementation yourself with the steps above.

There are currently no plans to support another implementation than transformers + PEFT together with bitsandbytes to implement qlora. As such, I will close this issue.
