### ISSUE TITLE
Cuda setup failing on 0.39.0 (was working on 0.38.1)

### ISSUE THREAD

**Issue by cassianlewis** [TimDettmers/bitsandbytes#458]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
False
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/ec2-user/anaconda3/envs/JupyterSystemEnv did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:/usr/local/lib:/usr/lib:/lib:/opt/amazon/efa/lib64:/opt/amazon/openmpi/lib64:/usr/local/lib:/usr/lib:/lib: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('8443'), PosixPath('//ip-172-16-74-147.eu-west-2.compute.internal')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Required library version not found: libbitsandbytes_cuda110.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=110 make cuda110
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by s1ghhh** [comment]
same issues on A40

**Comment by AlexiaJM** [comment]
Same here:

> bin /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
> False
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/jolicoea')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('-10')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/sshauth.OuK2UZM70Qq464w')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('1;/cvmfs/soft.computecanada.ca/easybuild/modules/2020/CUDA/cuda11.4'), PosixPath('1;/cvmfs/soft.computecanada.ca/easybuild/modules/2020/avx2/Core'), PosixPath('1;/cvmfs/soft.computecanada.ca/easybuild/modules/2020/Core'), PosixPath('1;/cvmfs/soft.computecanada.ca/easybuild/modules/2020/avx2/Compiler/gcc9'), PosixPath('1;/home/jolicoea/.local/easybuild/modules/2020/avx2/Core'), PosixPath('1;/cvmfs/soft.computecanada.ca/easybuild/modules/2020/avx2/CUDA/gcc9/cuda11.4'), PosixPath('1;/cvmfs/soft.computecanada.ca/custom/modules'), PosixPath('2;/cvmfs/soft.computecanada.ca/easybuild/modules/2020/avx2/CUDA/cuda11.4'), PosixPath('1'), PosixPath('1;/home/jolicoea/.local/easybuild/modules/2020/Core'), PosixPath('1;/cvmfs/soft.computecanada.ca/easybuild/modules/2020/avx2/MPI/gcc9/cuda11.4/openmpi4')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('openmpi/4.0.3'), PosixPath('rust/1.65.0'), PosixPath('pmix/3.1.5'), PosixPath('imkl/2020.1.217'), PosixPath('gcc/9.3.0'), PosixPath('StdEnv/2020'), PosixPath('ipykernel/2023a'), PosixPath('gdrcopy/2.1'), PosixPath('gcccore/.9.3.0'), PosixPath('scipy-stack/2023a'), PosixPath('cudnn/8.2.0'), PosixPath('mii/1.1.2'), PosixPath('cudacore/.11.4.2'), PosixPath('CCconfig'), PosixPath('cuda/11.4'), PosixPath('blis/0.8.1'), PosixPath('ucx/1.8.0'), PosixPath('python/3.9.6'), PosixPath('arrow/11.0.0'), PosixPath('thrift/0.18.1'), PosixPath('flexiblas/3.0.4'), PosixPath('libfabric/1.10.1'), PosixPath('libffi/3.3'), PosixPath('gentoo/2020')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/jolicoea/.local/easybuild/modules/2020/avx2/Core'), PosixPath('/home/jolicoea/.local/easybuild/modules/2020/Core')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//debuginfod.centos.org/ '), PosixPath('https')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('() {  ( alias;\n eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@\n}')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('() {  eval "$($LMOD_DIR/ml_cmd "$@")"\n}')}
>   warn(msg)
> /scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.4.2/lib/libcudart.so'), PosixPath('/cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.4.2/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
> Either way, this might cause trouble in the future:
> If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
>   warn(msg)
> CUDA SETUP: CUDA runtime path found: /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.4.2/lib/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.0
> CUDA SETUP: Detected CUDA version 114
> CUDA SETUP: Required library version not found: libbitsandbytes_cuda114.so. Maybe you need to compile it from source?
> CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
> 
> ================================================ERROR=====================================
> CUDA SETUP: CUDA detection failed! Possible reasons:
> 1. CUDA driver not installed
> 2. CUDA not installed
> 3. You have multiple conflicting CUDA libraries
> 4. Required library not pre-compiled for this bitsandbytes release!
> CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
> CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
> ================================================================================
> 
> CUDA SETUP: Something unexpected happened. Please compile from source:
> git clone git@github.com:TimDettmers/bitsandbytes.git
> cd bitsandbytes
> CUDA_VERSION=114 make cuda11x
> python setup.py install
> CUDA SETUP: Setup Failed!
> Traceback (most recent call last):
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/runpy.py", line 188, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/runpy.py", line 147, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "/scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
>     from . import cuda_setup, utils, research
>   File "/scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
>     from . import nn
>   File "/scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
>     from .modules import LinearFP8Mixed, LinearFP8Global
>   File "/scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
>     from bitsandbytes.optim import GlobalOptimManager
>   File "/scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
>     from bitsandbytes.cextension import COMPILED_WITH_CUDA
>   File "/scratch/jolicoea/qlora_/env/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 20, in <module>
>     raise RuntimeError('''
> RuntimeError:
>         CUDA Setup failed despite GPU being available. Please run the following command to get more information:
> 
>         python -m bitsandbytes
> 
>         Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
