### ISSUE TITLE
AttributeError: /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats

### ISSUE THREAD

**Issue by kishorgujjar** [TimDettmers/bitsandbytes#459]
How to solve this problem : 

AttributeError: /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats

**Comment by 22zhangqian** [comment]
这是由于bitsandbytes的版本冲突问题导致的。对我来说这个方法有效。
解决：
1. 进入报错路径对应的目录：cd /opt/conda/envs/finetune/lib/python3.10/site-packages/bitsandbytes
2. 拷贝cuda113版本的文件为使用的文件：cp libbitsandbytes_cuda113.so libbitsandbytes_cpu.so
这里是因为实例拉取的镜像是11.3版本，所以使用113版本文件。

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.
