### ISSUE TITLE
AttributeError: module 'bitsandbytes' has no attribute 'nn'

### ISSUE THREAD

**Issue by SeekPoint** [TimDettmers/bitsandbytes#462]
│ /home/amd00/llm_dev/qlora/qlora.py:33 in <module>                                                │
│                                                                                                  │
│    30 from datasets import load_dataset                                                          │
│    31 import evaluate                                                                            │
│    32                                                                                            │
│ ❱  33 from peft import (                                                                         │
│    34 │   prepare_model_for_int8_training,                                                       │
│    35 │   LoraConfig,                                                                            │
│    36 │   get_peft_model,                                                                        │
│                                                                                                  │
│ /home/amd00/llm_dev/qlora/peft/src/peft/__init__.py:22 in <module>                               │
│                                                                                                  │
│   19                                                                                             │
│   20 __version__ = "0.4.0.dev0"                                                                  │
│   21                                                                                             │
│ ❱ 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_    │
│   23 from .peft_model import (                                                                   │
│   24 │   PeftModel,                                                                              │
│   25 │   PeftModelForCausalLM,                                                                   │
│                                                                                                  │
│ /home/amd00/llm_dev/qlora/peft/src/peft/mapping.py:16 in <module>                                │
│                                                                                                  │
│    13 # See the License for the specific language governing permissions and                      │
│    14 # limitations under the License.                                                           │
│    15                                                                                            │
│ ❱  16 from .peft_model import (                                                                  │
│    17 │   PeftModel,                                                                             │
│    18 │   PeftModelForCausalLM,                                                                  │
│    19 │   PeftModelForSeq2SeqLM,                                                                 │
│                                                                                                  │
│ /home/amd00/llm_dev/qlora/peft/src/peft/peft_model.py:31 in <module>                             │
│                                                                                                  │
│     28 from transformers.modeling_outputs import SequenceClassifierOutput, TokenClassifierOutpu  │
│     29 from transformers.utils import PushToHubMixin                                             │
│     30                                                                                           │
│ ❱   31 from .tuners import (                                                                     │
│     32 │   AdaLoraModel,                                                                         │
│     33 │   AdaptionPromptModel,                                                                  │
│     34 │   LoraModel,                                                                            │
│                                                                                                  │
│ /home/amd00/llm_dev/qlora/peft/src/peft/tuners/__init__.py:21 in <module>                        │
│                                                                                                  │
│   18 # limitations under the License.                                                            │
│   19                                                                                             │
│   20 from .adaption_prompt import AdaptionPromptConfig, AdaptionPromptModel                      │
│ ❱ 21 from .lora import LoraConfig, LoraModel                                                     │
│   22 from .adalora import AdaLoraConfig, AdaLoraModel                                            │
│   23 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizatio    │
│   24 from .prefix_tuning import PrefixEncoder, PrefixTuningConfig                                │
│                                                                                                  │
│ /home/amd00/llm_dev/qlora/peft/src/peft/tuners/lora.py:676 in <module>                           │
│                                                                                                  │
│   673                                                                                            │
│   674 if is_bnb_available():                                                                     │
│   675 │                                                                                          │
│ ❱ 676 │   class Linear8bitLt(bnb.nn.Linear8bitLt, LoraLayer):                                    │
│   677 │   │   # Lora implemented in a dense layer                                                │
│   678 │   │   def __init__(                                                                      │
│   679 │   │   │   self,                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'bitsandbytes' has no attribute 'nn'

**Comment by cmosguy** [comment]
@SeekPoint  do a:
`pip install bitsandbytes==0.39.0`

**Comment by SeekPoint** [comment]
it works!

**Comment by sqrt81xmy** [comment]
thank you for solving my problem!!
