### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by MehrdadAbsolute** [TimDettmers/bitsandbytes#463]
Hi,
I wanted to test qlora but have issue with bitsandbytes this is my code :

from transformers import AutoModelForCausalLM
import torch

print(torch.cuda.is_available())

model = AutoModelForCausalLM.from_pretrained(
    'llama-13b-hf',
  device_map='auto',
  load_in_8bit=True,
  max_memory=f'{int(torch.cuda.mem_get_info()[0]/1024**3)-2}GB')

and i get 
True
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
.
.
.
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
.
.
.
Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes

My setup is ;

 Processor: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 CPUs), ~3.6GHz
Memory: 32768MB RAM
Card name: NVIDIA GeForce RTX 3060
Display Memory: 28431 MB
Dedicated Memory: 12129 MB

**Comment by TimDettmers** [comment]
I think this has been fixed in a recent release. Please upgrade and report back if you still face the issue.
