### ISSUE TITLE
Any tutorials on int8/nf4 parallel training?

### ISSUE THREAD

**Issue by ghost** [TimDettmers/bitsandbytes#466]
Can we use int8 + peft + deepspeed to do parallel training on multiple GPUs?

I've read many issues and docs but still can't get the definitive answer.

From https://github.com/TimDettmers/bitsandbytes/issues/89, it seems that this is infeasible now.

**Comment by TimDettmers** [comment]
Yes, FSDP does not work currently. There is a plan to support data parallelism, but there is currently no timeline for this feature. I am happy to take pull requests to fix the FSDP issue.

**Comment by wanglamao2** [comment]
Thank you! Keep up the good work!

**Comment by ouhenio** [comment]
> Yes, FSDP does not work currently. There is a plan to support data parallelism, but there is currently no timeline for this feature. I am happy to take pull requests to fix the FSDP issue.

Hi @TimDettmers. What would be required to fix this bug?
