### ISSUE TITLE
Why is S3 file system being used?

### ISSUE THREAD

**Issue by phalexo** [TimDettmers/bitsandbytes#471]
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
Segmentation fault (core dumped)

Is it possible to suppress its use?

**Comment by VelvetAcidChrist** [comment]
Reinstall pyarrow==11.0.0 fix it

**Comment by TimDettmers** [comment]
As this is not a bitsandbytes issue (bitsandbytes does not use pyarrow), I close this issue.
