### ISSUE TITLE
BUG REPORT

### ISSUE THREAD

**Issue by sDAWFFRXCACEV** [TimDettmers/bitsandbytes#479]
return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 11.99 GiB total capacity; 10.99 GiB already allocated; 0 bytes free; 11.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                                                  | 0/4950 [00:01<?, ?it/s]
Traceback (most recent call last):

**Comment by phalexo** [comment]
I have been plagued with this problem. What model are you loading? Into what GPU?

**Comment by sDAWFFRXCACEV** [comment]
> 我一直被这个问题所困扰。您正在加载什么型号？进入什么 GPU？

I successfully solved this problem, most cases is the lack of video memory of my computer itself, see the probability can run, more points a few times I successfully run, my computer is 4070Ti, only 12G, can be adjusted according to his training program to lower the configuration on the video memory consumption needs,https://civitai.com/articles/166/lora-training-guide-rz-passage-21-15

**Comment by phalexo** [comment]
> > 我一直被这个问题所困扰。您正在加载什么型号？进入什么 GPU？
> 
> I successfully solved this problem, most cases is the lack of video memory of my computer itself, see the probability can run, more points a few times I successfully run, my computer is 4070Ti, only 12G, can be adjusted according to his training program to lower the configuration on the video memory consumption needs,https://civitai.com/articles/166/lora-training-guide-rz-passage-21-15

I don't quite understand how this link helps to solve the problem. It is about a different matter.

**Comment by TimDettmers** [comment]
This problem is that you use a too-large model on a too-small GPU. I am unable to help with more information. Bitsandbytes helps with running larger models, but it does not guarantee that they can be run. The user still needs to make the necessary configurations to avoid errors such as these. Without more information, I cannot help. I will close this issue because its not bitsandbytes related.
