### ISSUE TITLE
Cannot built on arm cpu

### ISSUE THREAD

**Issue by bio-punk** [TimDettmers/bitsandbytes#483]
my cpu info:

> (alpaca_lora2)  [scx6012@paraai-n32-h-01-agent-7 bitsandbytes-0.38.0]$ lscpu
> Architecture:                    aarch64
> CPU op-mode(s):                  64-bit
> Byte Order:                      Little Endian
> CPU(s):                          128
> On-line CPU(s) list:             0-127
> Thread(s) per core:              1
> Core(s) per socket:              64
> Socket(s):                       2
> NUMA node(s):                    4
> Vendor ID:                       HiSilicon
> Model:                           0
> Model name:                      Kunpeng-920
> Stepping:                        0x1
> BogoMIPS:                        200.00
> L1d cache:                       8 MiB
> L1i cache:                       8 MiB
> L2 cache:                        64 MiB
> L3 cache:                        128 MiB
> NUMA node0 CPU(s):               0-31
> NUMA node1 CPU(s):               32-63
> NUMA node2 CPU(s):               64-95
> NUMA node3 CPU(s):               96-127
> Vulnerability Itlb multihit:     Not affected
> Vulnerability L1tf:              Not affected
> Vulnerability Mds:               Not affected
> Vulnerability Meltdown:          Not affected
> Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
> Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
> Vulnerability Spectre v2:        Not affected
> Vulnerability Srbds:             Not affected
> Vulnerability Tsx async abort:   Not affected
> Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
> 

my gpu is NVIDIA A100-PCIE-40GB
cuda is 11.8
```
(alpaca_lora2)  [scx6012@paraai-n32-h-01-agent-7 bitsandbytes-0.38.0]$ CUDA_VERSION=118 make cuda11x
mkdir -p build
mkdir -p dependencies
ENVIRONMENT
============================
CUDA_VERSION: 118
============================
NVCC path: /home/bingxing2/apps/compilers/cuda/cuda-11.8/bin/nvcc
GPP path: /usr/bin/g++ VERSION: g++ (GCC) 7.3.0
CUDA_HOME: /home/bingxing2/apps/compilers/cuda/cuda-11.8
CONDA_PREFIX: /home/bingxing2/home/scx6012/.conda/envs/alpaca_lora2
PATH: /home/bingxing2/apps/compilers/cuda/cuda-11.8/bin:/home/bingxing2/home/scx6012/git-lfs-3.3.0:/home/bingxing2/apps/compilers/gcc/9.3.0/bin:/home/bingxing2/home/scx6012/.conda/envs/alpaca_lora2/bin:/home/bingxing2/apps/anaconda/2021.11/condabin:/home/bingxing2/home/scx6012/.local/bin:/home/bingxing2/home/scx6012/bin:/home/bingxing2/apps/tools/modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
LD_LIBRARY_PATH: /home/bingxing2/apps/cudnn/8.4.0.27_cuda11.x/lib:/home/bingxing2/apps/cudnn/8.4.0.27_cuda11.x/lib64:/home/bingxing2/apps/compilers/cuda/cuda-11.8/lib64:/home/bingxing2/apps/anaconda/2021.11/lib:/home/bingxing2/apps/compilers/gcc/9.3.0/lib64
============================
/home/bingxing2/apps/compilers/cuda/cuda-11.8/bin/nvcc -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -Xcompiler '-fPIC' --use_fast_math -Xptxas=-v -dc /home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/csrc/ops.cu /home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/csrc/kernels.cu -I /home/bingxing2/apps/compilers/cuda/cuda-11.8/include -I /home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/csrc -I /home/bingxing2/home/scx6012/.conda/envs/alpaca_lora2/include -I /home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/include -L /home/bingxing2/apps/compilers/cuda/cuda-11.8/lib64 -lcudart -lcublas -lcublasLt -lcurand -lcusparse -L /home/bingxing2/home/scx6012/.conda/envs/alpaca_lora2/lib --output-directory /home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/build
In file included from /home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/include/BinSearch.h:5,
                 from /home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/csrc/ops.cu:10:
/home/bingxing2/home/scx6012/bitsandbytes38/bitsandbytes-0.38.0/include/SIMD.h:32:10: fatal error: emmintrin.h: No such file or directory
   32 | #include <emmintrin.h>
      |          ^~~~~~~~~~~~~

```
Is avx/sse must need?
I have an aarch64 HPC

**Comment by KastanDay** [comment]
I'm facing the same issue on a Nvidia developer box (`aarch64` + `a100`s). I wish there was a work-around.

**Comment by TimDettmers** [comment]
Currently, ARM is not supported. I would love a pull request that fixes this, but I  do not have an ARM system myself to test and maintain compatibility.
