### ISSUE TITLE
load_in_8bit very slow and slower than load_in_4bit now?

### ISSUE THREAD

**Issue by JulesGM** [TimDettmers/bitsandbytes#490]
My configuration is a DGX with 8x A100 40GB.

With all the models tested (Llama 7B, falcon 7b, flan-t5-xl or flan-t5-xxl), `load_in_8bit` is extremely slow, about 5x as slow as bf16, and 150% slower than load_in_4bit. 

I'm using Cuda 11.7 and the latest (github) version of both bitsandbytes & transformers.

My Cuda driver version is 470.141.03. I build bitsandbytes from source.

Any ideas?

@TimDettmers

**Comment by Oxi84** [comment]
Yes, it is pretty slow. I think Tim is already working on that.

**Comment by TimDettmers** [comment]
4-bit is faster now, but for small models like common 7B models, inference will always be slow and there is currently no plan to improve 8-bit inference performance. The kernels that I designed were designed for training and are not efficient for inference hence the slow speed.

**Comment by cringelord000222** [comment]
> 4-bit is faster now, but for small models like common 7B models, inference will always be slow and there is currently no plan to improve 8-bit inference performance. The kernels that I designed were designed for training and are not efficient for inference hence the slow speed.

Hi Tim,

Does that mean bitsandbytes are recommended for training and not for inference currently? I'm planning to use the Llama2-13B model with either 8bit or 4bit for training+inference, the plan is to deploy internally. 

Thanks.

**Comment by Oxi84** [comment]
Is  the speed improved now for 3bits. Cant test with my card, I can hardly put the model in memory.
