### ISSUE TITLE
load_in_8bit=True returns gibberish when inferencing on multi GPU

### ISSUE THREAD

**Issue by Daryl149** [TimDettmers/bitsandbytes#491]
Hi, the maintainers at Huggingface transformers mentioned that I should note it here as well. See the original issue here: https://github.com/huggingface/transformers/issues/23989

For the tested `bitsandbytes` versions `0.31.8`, `0.38.1` and `0.39.0`, when inferencing on multiple V100S GPUs (compute capability 7.0), the transformers `model.generate()` call returns gibberish **if you used the flag `load_in_8bit=True`** when loading the LLM.

- It only happens on multi GPU, not when the model is loaded on a single GPU.
- It does not happen when the model is loaded in default 16 bit.
- It does not happen with `load_in_4bit=True`, so the fix is installing `0.39.0` and running in 4bit.

**Comment by TimDettmers** [comment]
8-bit inference on a GPU of 7.0 does not use the original kernels for 8-bit matmul but works with an alternative implementation. It seems there is a bug with these implementations.

**Comment by Daryl149** [comment]
Since the new `load_in_4bit` flag for model weights in `transformers`, running `load_in_8bit` is a very situational decision, so not too high prio anymore. Could still be high prio for other dependent libraries that do not have 4bit support yet.

**Comment by RDearnaley** [comment]
I'm interested in using load_in_8bit to run a model and confirm that load_in_4bit hasn't caused a noticeable decrease in generation quality/increase in perplexity. So it would be nice to have this working.
