### ISSUE TITLE
Issue on CentOS

### ISSUE THREAD

**Issue by Kou-Guandong** [TimDettmers/bitsandbytes#492]
bin /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /home/dbw6B/anaconda3/envs/dbwenv did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
libcurand.so.10: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x
python setup.py install
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/13B/Chinese-Vicuna/interaction.py:3 in <module>                        │
│                                                                              │
│     1 import sys                                                             │
│     2 import torch                                                           │
│ ❱   3 from peft import PeftModel                                             │
│     4 import transformers                                                    │
│     5 import gradio as gr                                                    │
│     6 import argparse                                                        │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/peft/__init__. │
│ py:22 in <module>                                                            │
│                                                                              │
│   19                                                                         │
│   20 __version__ = "0.3.0.dev0"                                              │
│   21                                                                         │
│ ❱ 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CON │
│   23 from .peft_model import (                                               │
│   24 │   PeftModel,                                                          │
│   25 │   PeftModelForCausalLM,                                               │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/peft/mapping.p │
│ y:16 in <module>                                                             │
│                                                                              │
│    13 # See the License for the specific language governing permissions and  │
│    14 # limitations under the License.                                       │
│    15                                                                        │
│ ❱  16 from .peft_model import (                                              │
│    17 │   PeftModel,                                                         │
│    18 │   PeftModelForCausalLM,                                              │
│    19 │   PeftModelForSeq2SeqLM,                                             │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/peft/peft_mode │
│ l.py:31 in <module>                                                          │
│                                                                              │
│    28 from transformers.modeling_outputs import SequenceClassifierOutput, To │
│    29 from transformers.utils import PushToHubMixin                          │
│    30                                                                        │
│ ❱  31 from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptE │
│    32 from .utils import (                                                   │
│    33 │   TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,          │
│    34 │   WEIGHTS_NAME,                                                      │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/peft/tuners/__ │
│ init__.py:20 in <module>                                                     │
│                                                                              │
│   17 # See the License for the specific language governing permissions and   │
│   18 # limitations under the License.                                        │
│   19                                                                         │
│ ❱ 20 from .lora import LoraConfig, LoraModel                                 │
│   21 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoder │
│   22 from .prefix_tuning import PrefixEncoder, PrefixTuningConfig            │
│   23 from .prompt_tuning import PromptEmbedding, PromptTuningConfig, PromptT │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/peft/tuners/lo │
│ ra.py:36 in <module>                                                         │
│                                                                              │
│    33                                                                        │
│    34                                                                        │
│    35 if is_bnb_available():                                                 │
│ ❱  36 │   import bitsandbytes as bnb                                         │
│    37                                                                        │
│    38                                                                        │
│    39 @dataclass                                                             │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/_ │
│ _init__.py:6 in <module>                                                     │
│                                                                              │
│    3 # This source code is licensed under the MIT license found in the       │
│    4 # LICENSE file in the root directory of this source tree.               │
│    5                                                                         │
│ ❱  6 from . import cuda_setup, utils, research                               │
│    7 from .autograd._functions import (                                      │
│    8 │   MatmulLtState,                                                      │
│    9 │   bmm_cublas,                                                         │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/r │
│ esearch/__init__.py:1 in <module>                                            │
│                                                                              │
│ ❱ 1 from . import nn                                                         │
│   2 from .autograd._functions import (                                       │
│   3 │   switchback_bnb,                                                      │
│   4 │   matmul_fp8_global,                                                   │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/r │
│ esearch/nn/__init__.py:1 in <module>                                         │
│                                                                              │
│ ❱ 1 from .modules import LinearFP8Mixed, LinearFP8Global                     │
│   2                                                                          │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/r │
│ esearch/nn/modules.py:8 in <module>                                          │
│                                                                              │
│    5 from torch import Tensor, device, dtype, nn                             │
│    6                                                                         │
│    7 import bitsandbytes as bnb                                              │
│ ❱  8 from bitsandbytes.optim import GlobalOptimManager                       │
│    9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims         │
│   10                                                                         │
│   11 T = TypeVar("T", bound="torch.nn.Module")                               │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/o │
│ ptim/__init__.py:6 in <module>                                               │
│                                                                              │
│    3 # This source code is licensed under the MIT license found in the       │
│    4 # LICENSE file in the root directory of this source tree.               │
│    5                                                                         │
│ ❱  6 from bitsandbytes.cextension import COMPILED_WITH_CUDA                  │
│    7                                                                         │
│    8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit                 │
│    9 from .adam import Adam, Adam8bit, Adam32bit                             │
│                                                                              │
│ /home/dbw6B/anaconda3/envs/dbwenv/lib/python3.8/site-packages/bitsandbytes/c │
│ extension.py:20 in <module>                                                  │
│                                                                              │
│   17 │   if lib is None and torch.cuda.is_available():                       │
│   18 │   │   CUDASetup.get_instance().generate_instructions()                │
│   19 │   │   CUDASetup.get_instance().print_log_stack()                      │
│ ❱ 20 │   │   raise RuntimeError('''                                          │
│   21 │   │   CUDA Setup failed despite GPU being available. Please run the f │
│   22 │   │                                                                   │
│   23 │   │   python -m bitsandbytes                                          │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following 
command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA 
libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the 
information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.
