### ISSUE TITLE
cuda.cuDeviceGetCount(ct.byref(nGpus) does not update nGpus.values

### ISSUE THREAD

**Issue by jitingxu1** [TimDettmers/bitsandbytes#495]
I ran cuda.cuDeviceGetCount(ct.byref(nGpus), it returns 34, but the nGpus.value remains 0. 

```
>>> nGpus = ct.c_int()
>>> cuda.cuDeviceGetCount(ct.byref(nGpus))
34
>>> nGpus.value
0
```

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.
