### ISSUE TITLE
Do you have plan to integrate CPU enabling PRs for bitsandbytes

### ISSUE THREAD

**Issue by yao-matrix** [TimDettmers/bitsandbytes#496]
@TimDettmers , from Intel Xeon SapphireRapids CPU, there is an AMX(Advanced Matrix eXtention) instruction set introduced(see more from [here](https://www.intel.com/content/www/us/en/products/docs/accelerator-engines/advanced-matrix-extensions/overview.html)), and it actually an CPU tensor core for BF16 and INT8 precisions. So if we have some AMX related upstreaming to enable bitsandbytes in CPU, will you think it's a good idea and help review these PRs? Thx.

**Comment by TimDettmers** [comment]
I would not work on this myself, but if you want to give it a shot I am happy to support it in bitsandbytes and integrate it.
