### ISSUE TITLE
Sophia Optimizer

### ISSUE THREAD

**Issue by liveck** [TimDettmers/bitsandbytes#499]
Is there any test for Sophia?

https://github.com/Liuhong99/Sophia

**Comment by TimDettmers** [comment]
The work does not have strong AdamW baselines, and some plots show constant offsets compared to Adam, indicating that it is not better than Adam and has merely better hyperparameters. I am waiting for this optimizer to be used successfully in multiple training runs before implementing it. But if anyone wants to help implement it, I am happy to support the development process.

**Comment by dustydecapod** [comment]
@TimDettmers I've been looking at using Sophia, have you seen any meaningful successes out in the wild yet?
