### ISSUE TITLE
Failing with 4bit cuDeviceCount

### ISSUE THREAD

**Issue by nishant-ust** [TimDettmers/bitsandbytes#501]
I am facing this issue when using in the code :
path = starcoder-alpha
model_4bit = AutoModelForCausalLM.from_pretrained(path,
                                              load_in_4bit=True,
                                              device_map='auto',
                                              torch_dtype=torch.float16
                                              )
In code i get AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'

**GPU info** 
 torch.cuda.is_available()
True
 torch.cuda.device_count()
1
torch.cuda.get_device_name(0)
'Quadro RTX 5000 with Max-Q Design'

**On running bug report :**     
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: D:\codeda\conda\envs\starcoder-cuda\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\codeda\conda\envs\starcoder-cuda\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++ DEBUG INFORMATION +++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++ POTENTIALLY LIBRARY-PATH-LIKE ENV VARS ++++++++++
'_CONDA_EXE': 'C:/Anaconda3\Scripts\conda.exe'
'_CONDA_ROOT': 'C:/Anaconda3'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

WARNING: Please be sure to sanitize sensible info from any such env vars!

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
Traceback (most recent call last):
  File "D:\codeda\conda\envs\starcoder-cuda\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\codeda\conda\envs\starcoder-cuda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\codeda\conda\envs\starcoder-cuda\lib\site-packages\bitsandbytes\__main__.py", line 47, in <module>
    print(f"COMPUTE_CAPABILITIES_PER_GPU = {get_compute_capabilities(cuda)}")
  File "D:\codeda\conda\envs\starcoder-cuda\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 336, in get_compute_capabilities
    check_cuda_result(cuda, cuda.cuDeviceGetCount(ct.byref(nGpus)))
AttributeError: 'NoneType' object has no attribute 'cuDeviceGetCount'

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
