### ISSUE TITLE
Loras not doing anything

### ISSUE THREAD

**Issue by IWDLACSWCAKT** [TimDettmers/bitsandbytes#508]
Hello, I installed Koyah properly no problem. I tried to make a lora model with 15 images simply to try it out but the .safetensor file I get as an output doesn't work when I use it on A1111. It doesn't do anything meaning there is no difference between a prompting with the lora I made and the exact same prompt but without the lora.

What could be causing this? I followed aitrepeneurs guide and the bald dude with a beard (forgot his name) on youtube but still no luck for some reason. Both guides were easy to follow but for some reason my training delivers a file that doesn't do anything.
Pretty new to this so it could be something simple that wasn't covered in the tutorials.

**Comment by TimDettmers** [comment]
I do not have the time to watch the tutorials that you did. Can you provide me with a small example that replicates this issue?

**Comment by IWDLACSWCAKT** [comment]
so sorry, I tried to replicate it too but can't
So I guess there no longer is a problem
