### ISSUE TITLE
CUDA Setup failed despite GPU being available.

### ISSUE THREAD

**Issue by TS10armourer** [TimDettmers/bitsandbytes#512]
But I ran the following code check and there was no problem
![image](https://github.com/TimDettmers/bitsandbytes/assets/100982130/74fb151a-6a20-4112-8319-6b1266290e05)
After running 'Python - m bitsandbytes', the information is as follows
(AI002) C:\Users\Administrator>python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('E'), WindowsPath('/Miniconda3/envs/AI002/lib')}
  warn(msg)
E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: E:\Miniconda3\envs\AI002 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "E:\Miniconda3\envs\AI002\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "E:\Miniconda3\envs\AI002\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "E:\Miniconda3\envs\AI002\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "E:\Miniconda3\envs\AI002\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by sunbeibei-hub** [comment]
楼主解决没

**Comment by sunbeibei-hub** [comment]
遇到同样的问题

**Comment by vootox** [comment]
Same issue

**Comment by krishnareddyML** [comment]
any update on above issue, I have also got the same issue in windows

**Comment by RyanDivigalpitiya** [comment]
I also have the same issue (am on windows)

**Comment by wzwtime** [comment]
same issue

**Comment by marco-ve** [comment]
Same issue

**Comment by wzwtime** [comment]
cuda use 11.8 not 12.1 
bitsanbytes use pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl

**Comment by TimDettmers** [comment]
This issue might be resolve by upgrading via `pip install -U bitsandbytes`. However, note that Windows is currently not supported. You can find more information here: #30

**Comment by chwshuang** [comment]
in my window10:
`git clone https://github.com/Vision-CAIR/MiniGPT-4.git `
`cd MiniGPT-4 `
`conda env create -f environment.yml `
`conda activate minigpt4`
`pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`
`pip uninstall bitsandbytes`
`pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl`

run `python demo.py --cfg-path eval_configs/minigpt4_eval.yaml --gpu-id 0`

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
