### ISSUE TITLE
执行过程中直接报错，信息如下

### ISSUE THREAD

**Issue by linghongli** [TimDettmers/bitsandbytes#513]
![image](https://github.com/TimDettmers/bitsandbytes/assets/2770205/380b949c-df53-419b-9711-6ada07d9e946)
![image](https://github.com/TimDettmers/bitsandbytes/assets/2770205/e91e7e37-430c-4913-9562-e18e95320b7c)

**Comment by TimDettmers** [comment]
This is a problem with a different library. The error is not part of the bitsandbytes codebase.
