### ISSUE TITLE
Issue with CUDA setup on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by quartet** [TimDettmers/bitsandbytes#514]
I am experiencing an issue with the CUDA setup while trying to run h2oGPT on Ubuntu 20.04.6 LTS. I would like to open a bug report to seek assistance in resolving this problem.

Here is my system information:

OS: Ubuntu 20.04.6 LTS
CUDA Driver Version: 470.42.01
CUDA Version: 11.4
GPU: Tesla K80
The error message I encountered suggests that the CUDA setup failed despite the GPU being available. I followed the installation steps correctly, including the installation of the necessary CUDA Toolkit and setting the PATH and LD_LIBRARY_PATH environment variables accordingly.

When running the command python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --load_8bit=True, I received the following error message:

CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
...
I have ensured that the CUDA driver is installed, and the CUDA version is compatible with the installed CUDA Toolkit.

To provide more context, here are additional details:

Ubuntu distribution: Focal (20.04)
NVIDIA GPU utilization: Tesla K80
I have also tried running python -m bitsandbytes to gather more information about the CUDA setup, but it didn't provide any useful insights.

I would greatly appreciate any guidance or suggestions on how to resolve this issue. Please let me know if you require any further information or logs to assist in troubleshooting.

Thank you for your attention to this matter.

**Comment by TimDettmers** [comment]
Unfortunately, K80 GPUs are no longer supported for bitsandbytes. The problem is that lots of custom code would be needed to support both K80s and bfloat16. To ensure we can support bfloat16 and maintain the library with less time, we decided to remove K80 support.

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
