### ISSUE TITLE
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

### ISSUE THREAD

**Issue by mmderakhshani** [TimDettmers/bitsandbytes#528]
Hi, I have installed bitsandbytes using following commands:

```
pip install -q bitsandbytes datasets accelerate loralib
pip install -q git+https://github.com/huggingface/transformers.git@main git+https://github.com/huggingface/peft.git
```

But when I run `python -m bitsandbytes`, I get the following error. Do you have any idea how to solve it? For more information, please see the following:

Python version
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Pytorch/cuda version:
```
>>> torch.__version__
'2.0.1+cu117'
>>> torch.version.cuda
'11.7'
```

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/anaconda/envs/mlenv/lib/libcudart.so.11.0'), PosixPath('/anaconda/envs/mlenv/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /anaconda/envs/mlenv/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 3.7
CUDA SETUP: Detected CUDA version 116
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/anaconda/envs/mlenv/lib/libcudart.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/torch/lib/libc10_cuda.so
/anaconda/envs/mlenv/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so

Traceback (most recent call last):
  File "/anaconda/envs/mlenv/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda/envs/mlenv/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 54, in generate_bug_report_information
    paths = find_file_recursive('/usr/local', '*cuda*so')
  File "/anaconda/envs/mlenv/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by bigheiniu** [comment]
Get the same issue here.

**Comment by TimDettmers** [comment]
It seems you are running on a K80 GPU. Unfortunately, these are no longer supported in bitsandbytes because it makes it very difficult to implement wide bfloat16 support and at the same time support these GPUs that are now 9 years old.

**Comment by Amoiensis** [comment]
I hit the same issue, and solved it by:

1. sudo su 

>  in "/home/pier/miniconda3/envs/cuda11_py39/lib/python3.9/site-packages/bitsandbytes/__main__.py" function find_file_recursive : CMD:find {folder} -name {filename} , using "root"(account) and skip the error.

2. python -m bitsandbytes

>  [will be OK.]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable
WARNING: Please be sure to sanitize sensible info from any such env vars!
SUCCESS!
Installation was successful!
