### ISSUE TITLE
UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!   warn(msg) Detected 8-bit loading: activating 8-bit loading for this model

### ISSUE THREAD

**Issue by brijesh-6899** [TimDettmers/bitsandbytes#529]
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
> and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 7.0
> CUDA SETUP: Detected CUDA version 118
> CUDA SETUP: Loading binary /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
> /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
>   warn(msg)
> /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
>   warn(msg)
> /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('mi'), PosixPath('is=\\E)0'), PosixPath('LP'), PosixPath('kD=\\E[3~'), PosixPath('kI=\\E[2~'), PosixPath('rs=\\Ec'), PosixPath('DC=\\E[%dP'), PosixPath('se=\\E[23m'), PosixPath('so=\\E[3m'), PosixPath('k8=\\E[19~'), PosixPath('pf=\\E[4i'), PosixPath('md=\\E[1m'), PosixPath('as=\\E(0'), PosixPath('IC=\\E[%d@'), PosixPath('k;=\\E[21~'), PosixPath('AX'), PosixPath('AF=\\E[3%dm'), PosixPath('k6=\\E[17~'), PosixPath('k9=\\E[20~'), PosixPath('vs=\\E[34l'), PosixPath('LE=\\E[%dD'), PosixPath('kr=\\EOC'), PosixPath('im=\\E[4h'), PosixPath('dl=\\E[M'), PosixPath('kB=\\E[Z'), PosixPath('pa#64'), PosixPath('mr=\\E[7m'), PosixPath('k1=\\EOP'), PosixPath('vb=\\Eg'), PosixPath('ta=^I'), PosixPath('le=^H'), PosixPath('k5=\\E[15~'), PosixPath('op=\\E[39;49m'), PosixPath('km'), PosixPath('li#33'), PosixPath('F1=\\E[23~'), PosixPath('kl=\\EOD'), PosixPath('AL=\\E[%dL'), PosixPath('cl=\\E[H\\E[J'), PosixPath('k0=\\E[10~'), PosixPath('mh=\\E[2m'), PosixPath('Km=\\E[M'), PosixPath('@7=\\E[4~'), PosixPath('F2=\\E[24~'), PosixPath('SC|screen|VT 100/ANSI X3.64 virtual terminal'), PosixPath('ve=\\E[34h\\E[?25h'), PosixPath('ks=\\E[?1h\\E='), PosixPath('dc=\\E[P'), PosixPath('rc=\\E8'), PosixPath('it#8'), PosixPath('sc=\\E7'), PosixPath('k7=\\E[18~'), PosixPath('kH=\\E[4~'), PosixPath('do=^J'), PosixPath('nd=\\E[C'), PosixPath('ce=\\E[K'), PosixPath('up=\\EM'), PosixPath('me=\\E[m'), PosixPath('ae=\\E(B'), PosixPath('xn'), PosixPath('ku=\\EOA'), PosixPath('ue=\\E[24m'), PosixPath('ct=\\E[3g'), PosixPath('DO=\\E[%dB'), PosixPath('bt=\\E[Z'), PosixPath('ei=\\E[4l'), PosixPath('cd=\\E[J'), PosixPath('ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00'), PosixPath('kh=\\E[1~'), PosixPath('am'), PosixPath('kN=\\E[6~'), PosixPath('sr=\\EM'), PosixPath('pt'), PosixPath('bs'), PosixPath('k4=\\EOS'), PosixPath('us=\\E[4m'), PosixPath('Co#8'), PosixPath('k2=\\EOQ'), PosixPath('ke=\\E[?1l\\E>'), PosixPath('UP=\\E[%dA'), PosixPath('cr=^M'), PosixPath('cs=\\E[%i%d;%dr'), PosixPath('DL=\\E[%dM'), PosixPath('po=\\E[5i'), PosixPath('ti=\\E[?1049h'), PosixPath('@1=\\E[1~'), PosixPath('bl=^G'), PosixPath('ms'), PosixPath('G0'), PosixPath('ho=\\E[H'), PosixPath('te=\\E[?1049l'), PosixPath('kd=\\EOB'), PosixPath('RI=\\E[%dC'), PosixPath('st=\\EH'), PosixPath('co#123'), PosixPath('mb=\\E[5m'), PosixPath('xv'), PosixPath('kP=\\E[5~'), PosixPath('vi=\\E[?25l'), PosixPath('AB=\\E[4%dm'), PosixPath('nw=\\EE'), PosixPath('cm=\\E[%i%d;%dH'), PosixPath('k3=\\EOR'), PosixPath('al=\\E[L')}
>   warn(msg)
> /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
>   warn(msg)
> /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
> Either way, this might cause trouble in the future:
> If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
>   warn(msg)
> /usr/local/lib/python3.8/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
>   warn(msg)
> Detected 8-bit loading: activating 8-bit loading for this model
> Loading widget...

Received above when tried to load Falcon-7B with 4-bit quantisation.

Please check and provide the solution to load in 4-bits instead of 8-bits

Thanks and regards!

**Comment by davidheineman** [comment]
Compute capability has to do with the specific features of the GPU you are using.

You can see this here:
`torch.cuda.get_device_capability()`

This corresponds to this list of compute capabilities: https://en.wikipedia.org/wiki/CUDA#GPUs_supported.

So, for example, a V100 is incompatible because the required features aren't part of its hardware. Unfortunately, you'd need to move to a newer GPU like A10/A100

**Comment by TimDettmers** [comment]
Thank you @davidheineman, you are correct. I think its a good suggestion to point to the 4-bit implementation which also works with older hardware. I will try to integrate that in a future release.

**Comment by brijesh-6899** [comment]
Hi @TimDettmers, It's a bit confusing. Does V100 support 4-bit quantisation or it doesn't. Given the comment from @davidheineman suggesting that V100 is incompatible for 4-bit loading. Thanks!

**Comment by TimDettmers** [comment]
Yes, 4-bit is supported by all GPUs, but  8-bit is not supported. I added a comment on this in the commit above and close the issue now. Thanks again for reporting this.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
