### ISSUE TITLE
Slow inference on most of the LLMs

### ISSUE THREAD

**Issue by mattkallo** [TimDettmers/bitsandbytes#537]
Thanks for creating this library.

Does quantization reduce model inference speed drastically compared to the non-quantized model? I am seeing a drop of 10x on most of the LLMs I tried. Is this expected? There is no discussions tab/option for the repository, hence posting it under issues. 

Most of them takes roughly 120 secs to make the inference on any task (200 output tokens)

GPU  - A100 40GB

Falcon 7B
Falcon 40B
LLaMA (multiple versions)

Quantization config used:

```
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map={"":0}, trust_remote_code=True)
```

**Comment by tiandiao123** [comment]
@mattkallo  We are working on something related to inference project, this project is actively being developed. Please stay tuned.

**Comment by TimDettmers** [comment]
This has been addressed for batch size of 1 in the most recent release: https://github.com/TimDettmers/bitsandbytes/releases/tag/0.40.0

Batched inference is planned, but will take several weeks until completed.
