### ISSUE TITLE
make error:This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

### ISSUE THREAD

**Issue by beileiyuyue** [TimDettmers/bitsandbytes#542]
When I run "CUDA_VERSION=110 make cuda110", I get the following error:
```
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
make: *** [cuda110] Error 1
``` 
I tried replacing "-std=c++11" with "-std=c++14" in the makefile, but still get the same error.
I see that some have solved this problem by upgrading GCC(#450 ). However, upgrading GCC has a significant impact on me. Is there any other way to solve this problem?

**Comment by TimDettmers** [comment]
It should work with c++11. I think the Makefile might not be able to find the right g++ version. see if the make file returns the correct G++ compiler that has c++11 support.

**Comment by beileiyuyue** [comment]
I have solved this problem by upgrading GCC.

**Comment by xf4fresh** [comment]
> I have solved this problem by upgrading GCC.

Can you kindly tell me which version you upgraded to?
