### ISSUE TITLE
What exactly is the `nf4` data type?

### ISSUE THREAD

**Issue by AlpinDale** [TimDettmers/bitsandbytes#543]
There seems to be no proper explanation for the data type anywhere I've seen (maybe I'm not looking hard enough). What exactly is this data type, and how is FP4 normalized to get NF4?

**Comment by r3curs10n** [comment]
nf4 is the normalized float 4 bit data type. It quantizes floats into 4 bits. This video (at the specific timestamp) explains it in more detail: https://youtu.be/TPcXVJ1VSRI?t=563

**Comment by TimDettmers** [comment]
See also the QLoRA paper: https://arxiv.org/abs/2305.14314

I will see to add documentation somewhere for people that are interested to learn more.

**Comment by TimDettmers** [comment]
I now added documentation in the commit above. Thanks again for reporting the lack of information on this.

**Comment by RonanKMcGovern** [comment]
I see, so instead of evenly distributing the quantized levels, they are normally distributed. Interesting the optimum is a normal distribution. Is this because language model weights are normally distributed - kind of surprises me?

Interesting it's not exactly symmetric as well, those 16 datapoints

**Comment by garyhlai** [comment]
Fwiw I traced the code back to the actual cuda kernels. It seems that these are the two kernels actually executed:
- https://github.com/TimDettmers/bitsandbytes/blob/25abf8d95f8a33f38e2ce6f637768b442379ccd9/csrc/kernels.cu#L223-L329

Note `dQuantizeNF4` is the quantization kernel, `dDequantizeNF4` is the de-quantization kernel (The "d" is a bit confusing)

**Comment by leizhenyuan** [comment]
May I know why table for NF4 quantize and dequantize are different? In my understanding, they should be the same
