### ISSUE TITLE
scipy dep

### ISSUE THREAD

**Issue by danbider** [TimDettmers/bitsandbytes#544]
Hi!

scipy is used in a few places in the repo, but doesn't appear in the deps. should be added? or eliminated from repo?

**Comment by TimDettmers** [comment]
Thank you for reporting this. scipy is needed for the 4-bit NormalFloat data type calculation. So it is best to add it to the requirements.

**Comment by TimDettmers** [comment]
It has been added. Thanks again for reporting.

**Comment by davidthomas426** [comment]
I don't think this addresses the problem.

Note the `Requires:` line in pip show: 
```
$ pip show bitsandbytes
Name: bitsandbytes
Version: 0.40.2
Summary: k-bit optimizers and matrix multiplication routines.
Home-page: https://github.com/TimDettmers/bitsandbytes
Author: Tim Dettmers
Author-email: dettmers@cs.washington.edu
License: MIT
Location: /home/ubuntu/.local/lib/python3.10/site-packages
Requires:
Required-by:
```

**Comment by dulalbert** [comment]
> It has been added. Thanks again for reporting.

I think you need to add it to `install_requires` too.
https://github.com/TimDettmers/bitsandbytes/pull/525#issuecomment-1630724978

**Comment by liebkne** [comment]
How to fix?

**Comment by ashleykleynhans** [comment]
This issue is closed but its still an issue in the latest version 0.41.1.

**Comment by goetzc** [comment]
I can confirm it's still an open issue when installing from `pip`. 

@TimDettmers 👀
