### ISSUE TITLE
AutoModelForCausalLM TypeError

### ISSUE THREAD

**Issue by williamseward** [TimDettmers/bitsandbytes#546]
trying to load this in Colab. Been working for the last few days, now I’m getting a TypeError

!pip install -q -U bitsandbytes
!pip install -q -U git+https://github.com/huggingface/transformers.git
!pip install -q -U git+https://github.com/huggingface/peft.git
!pip install -q -U git+https://github.com/huggingface/accelerate.git
!pip install -q -U einops
!pip install -q -U safetensors
!pip install -q -U torch
!pip install -q -U xformers
!pip install -q -U datasets

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, pipeline
import transformers
import torch
from torch.utils.data import DataLoader, Dataset
import torch
from transformers import AutoTokenizer

model_id = "vilsonrodrigues/falcon-7b-instruct-sharded" # sharded model by vilsonrodrigues
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map={"":0}, trust_remote_code=True)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-021942e1551e>](https://bt56dvhtbq9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230626-060134-RC00_543392955#) in <cell line: 11>()
      9 tokenizer = AutoTokenizer.from_pretrained(model_id)
     10 tokenizer.pad_token = tokenizer.eos_token
---> 11 model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map={"":0}, trust_remote_code=True)

2 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py](https://bt56dvhtbq9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230626-060134-RC00_543392955#) in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    477             )
    478             _ = hub_kwargs.pop("code_revision", None)
--> 479             return model_class.from_pretrained(
    480                 pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    481             )

[/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py](https://bt56dvhtbq9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230626-060134-RC00_543392955#) in from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2957             if "skip_keys" in inspect.signature(dispatch_model).parameters:
   2958                 kwargs["skip_keys"] = model._skip_keys_device_placement
-> 2959             dispatch_model(model, **kwargs)
   2960 
   2961         if output_loading_info:

[/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py](https://bt56dvhtbq9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230626-060134-RC00_543392955#) in dispatch_model(model, device_map, main_device, state_dict, offload_dir, offload_index, offload_buffers, skip_keys, preload_module_classes)
    387         retie_parameters(model, tied_params)
    388     else:
--> 389         device = device_map.values()[0]
    390         if device != "disk":
    391             model.to(device)

TypeError: 'dict_values' object is not subscriptable

**Comment by DJT777** [comment]
Getting a similar issue too after days of it working on Colab with Falcon and LLaMa.

**Comment by TimDettmers** [comment]
The behavior of `device_map` might have changed. You could try `device_map='auto'`. @younesbelkada do you know more?

**Comment by younesbelkada** [comment]
yes this was a bug on accelerate that was fixed by: https://github.com/huggingface/accelerate/pull/1651 
@TimDettmers re-installing `accelerate` from source should fix the issue

**Comment by TimDettmers** [comment]
Thank you, @younesbelkada!
