### ISSUE TITLE
view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by zxy333666** [TimDettmers/bitsandbytes#550]
bitsandbytes/autograd /_functions.py

300         # 1. Quantize A
301         if len(A.shape) == 3:
302             A = A.view(-1, A.shape[-1]).contiguous()

Is this a bug? Change it to :A = A.contiguous().view(-1, A.shape[-1])

 an error before changing:

view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...)  instead

normal after  change

**Comment by TimDettmers** [comment]
Thank you for reporting this. I need to look at this carefully to consider the performance tradeoffs. I think I  will just merge the existing PR as it has a minimal performance hit.
