### ISSUE TITLE
What Optimizer2State for?

### ISSUE THREAD

**Issue by kjlee18** [TimDettmers/bitsandbytes#559]
While watching code of QLoRA, I come to this repo.

I could not understand why `optimizer2state` class is needed. Why do we need two states when updating gradient? Is it relevant with quantization?

**Comment by TimDettmers** [comment]
Some optimizers like Adam/AdamW use two optimizer states. One estimates the first moment (mean), and the second the second moment (variance).  The AdamW is ratio s1/sqrt(s2+eps), where s1 and s2 are the first and second states and eps is a constant to avoid dividing by zero. This formula is equivalent to the signal-to-noise ratio. As such, AdamW can be seen as the smoothed signal-to-noise ratio of the gradient over time.
