### ISSUE TITLE
WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...

### ISSUE THREAD

**Issue by jypark9731** [TimDettmers/bitsandbytes#562]
I have following code in my bash.rc file.

export PATH=/usr/local/cuda-11.6/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.6/lib64:$LD_LIBRARY_PATH
export CUDADIR=/usr/local/cuda-11.6

And my GPU Driver Version: 510.108.03 / CUDA Version: 11.6 

I think proper versions of GPU Driver, Cuda were set, but I got an error while compling a model into INT8 : 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/jypark/anaconda3/envs/hf/lib/libcudart.so'), PosixPath('/home/jypark/anaconda3/envs/hf/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /home/jypark/anaconda3/envs/hf/lib/libcudart.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary /home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/jypark/anaconda3/envs/hf/nsight-compute/2023.2.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/home/jypark/anaconda3/envs/hf/nsight-compute/2023.2.0/target/linux-desktop-t210-a64/libcuda-injection.so
/home/jypark/anaconda3/envs/hf/nsight-compute/2023.2.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/torch/lib/libc10_cuda.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/jypark/anaconda3/envs/hf/lib/stubs/libcuda.so
/home/jypark/anaconda3/envs/hf/lib/libcudart.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.1/nsight-compute-2020.2.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.1/nsight-compute-2020.2.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.1/nsight-compute-2020.2.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.1/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.6/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.6/nsight-compute-2022.1.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.6/nsight-compute-2022.1.0/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.6/nsight-compute-2022.1.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cu.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_cpp.so
/usr/local/cuda-11.7/nsight-compute-2022.2.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.7/nsight-compute-2022.2.1/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.7/nsight-compute-2022.2.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.7/lib64/stubs/libcuda.so
/usr/local/cuda-11.7/lib64/libcudart.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudart.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
++++++++++ /usr/local/cuda-11.1/lib64 CUDA PATHS +++++++++++

++++++++++ /usr/local/cuda-11.6/lib64 CUDA PATHS +++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
Traceback (most recent call last):
  File "/home/jypark/anaconda3/envs/hf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jypark/anaconda3/envs/hf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 106, in <module>
    print(f"COMPUTE_CAPABILITIES_PER_GPU = {get_compute_capabilities(cuda)}")
  File "/home/jypark/anaconda3/envs/hf/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 349, in get_compute_capabilities
    check_cuda_result(cuda, cuda.cuDeviceGetCount(ct.byref(nGpus)))
AttributeError: 'NoneType' object has no attribute 'cuDeviceGetCount'

**Comment by TimDettmers** [comment]
These are a lot of different CUDA paths. But this is good information what an environment can look like and we are able to debug with this. It also seems the wrong libcuda.so is loaded which is not compatible with your GPU.

We are working on a fix, but for now what you can do is try to clean up your environment. If you can get rid of faulty libcuda.so, it should at least run or you should be able to compile.

We will also try to eliminate the dependency on the libcuda.so for compute capability detection.

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue now. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
