### ISSUE TITLE
Running bitsandbytes on windows, getting following issue

### ISSUE THREAD

**Issue by muralimuppireddy** [TimDettmers/bitsandbytes#564]
Hi,

When my code related LLM is trying to download a model getting an issue to run python -m bitsanbytes, but after running it on my windows machine using CPU getting the following error, looks like it's not supporting Windows version.
How to run bitsandbytes in my windows machine?

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\Murali M M\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\Murali M M\anaconda3\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
CUDA SETUP: Loading binary C:\Users\Murali M M\anaconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "C:\Users\Murali M M\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Murali M M\anaconda3\lib\runpy.py", line 87, in _run_code
 exec(code, run_globals)
  File "C:\Users\Murali M M\anaconda3\lib\site-packages\bitsandbytes\__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "C:\Users\Murali M M\anaconda3\lib\site-packages\bitsandbytes\__main__.py", line 49, in generate_bug_report_information
    paths = find_file_recursive(os.environ['CONDA_PREFIX'], '*cuda*so')
  File "C:\Users\Murali M M\anaconda3\lib\site-packages\bitsandbytes\__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by jb-01** [comment]
Trying upgrading your package version: `pip install --upgrade bitsandbytes`

**Comment by TimDettmers** [comment]
Windows is currently not supported. You can find more information here: #30
