### ISSUE TITLE
❌ Inference Error: invalid configuration argument in ops.cu

### ISSUE THREAD

**Issue by PhilWicke** [TimDettmers/bitsandbytes#57]
I am able to load an 8-bit optimized BLOOM model into memory, provided by [https://huggingface.co/joaoalvarenga/bloom-8bit](https://huggingface.co/joaoalvarenga/bloom-8bit). Unfortunately, I'm receiving the error message:

`Error invalid configuration argument at line 69 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu`

I'm afraid my hardware does not support the bitsandbytes cuda prerequisites?
My system:
```
8x NVIDIA RTX A6000
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 113
```

Any insights would be greatly appreciated.

**Comment by TimDettmers** [comment]
Your setup should be supported. The issue currently, is that passing a tensor into block-wise quantization that was indexed leads to an error. You can prevent this error by indexing and then calling `.clone()` on the slice. Or you wait for the fix.

In any case, now that `LLM.int8()` exists, I would recommend that you use that. You can use fine-tunable Int8 Linear layer with the argument `memory_efficient_backward=True` for the [Linear8bitLt module](https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/nn/modules.py#L224).

**Comment by PhilWicke** [comment]
Thanks, @TimDettmers for your quick response - I appreciate it. 
I'm super confident with this code, so I might be wrong here. The solution you suggest has already been in place:
```python3
input_chunk = flat_tensor[i * chunk_size: (i + 1) * chunk_size].clone()
quantized_chunk, (absmax_chunk, code) = quantize_blockwise(input_chunk, code=code)
```

Your alternative is way to complex for me at this moment. I'll have to do some reading on that, thanks.

**Comment by PhilWicke** [comment]
I'm now running the models with` LLM.int8()`. Thanks
