### ISSUE TITLE
Error named symbol not found at line 117 in file /home/ubuntu/bitsandbytes/csrc/ops.cu

### ISSUE THREAD

**Issue by snichols** [TimDettmers/bitsandbytes#571]
This is similar to https://github.com/TimDettmers/bitsandbytes/issues/568 but I'm not getting exactly the same log info.  This is running on a Lambda Labs VM.  Had to build from source.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ubuntu/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118.so
CUDA SETUP: CUDA runtime path found: /usr/lib/x86_64-linux-gnu/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 9.0
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/ubuntu/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/lib/python3.8/dist-packages/bitsandbytes-0.39.1-py3.8.egg/bitsandbytes/libbitsandbytes_cuda118.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/ubuntu/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda118.so
/home/ubuntu/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++ /usr/lib/x86_64-linux-gnu CUDA PATHS +++++++++++
/usr/lib/x86_64-linux-gnu/libcudart.so
/usr/lib/x86_64-linux-gnu/stubs/libcuda.so
/usr/lib/x86_64-linux-gnu/libcuda.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['9.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

Error named symbol not found at line 117 in file /home/ubuntu/bitsandbytes/csrc/ops.cu

**Comment by snichols** [comment]
Looks like a duplicate of https://github.com/TimDettmers/bitsandbytes/issues/382 and some others.  Using a H100 GPU.

**Comment by Daryl149** [comment]
See https://github.com/TimDettmers/bitsandbytes/issues/566 for the solution.

**Comment by TimDettmers** [comment]
Thank you for reporting this and thank you @Daryl149 for your previous solution. The main problem is that I thought that Hopper only supports >= CUDA 12.0, but apparently, CUDA 11.8 is also supported. I did not compile the CUDA 11.8 with Hopper. This is an easy fix and will do this soon.

**Comment by TimDettmers** [comment]
@Daryl149 thanks for the pointer. I just checked, and there are indeed still some issues regarding Volta. I will create a new issue for that. This issue was related to Hopper which is fixed now.

**Comment by TimDettmers** [comment]
@Daryl149 I actually find  on a second look that the correct binary for Volta V100 should be `libbitsandbytes_cudaXXX_nocublaslt.so` which can be compiled with `CUDA_VERSION=118 make cuda118_nomatmul`

**Comment by Daryl149** [comment]
ahhh, that makes sense! Yeah, the only hint for the V100 and V100S atm is that on running `python -m bitsandbytes`, you get a 'only slow matmul is supported' nofication.
I'll see if I can do this in a fresh venv. If successful, then I'll make a PR for the readme.

**Comment by JohnTailor** [comment]
I get almost the same error as above:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/torch/lib/libc10_cuda.so
/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes-0.41.1-py3.11.egg/bitsandbytes/libbitsandbytes_cuda118.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/johannes/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118.so
/home/johannes/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda118.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++ /usr/lib/x86_64-linux-gnu CUDA PATHS +++++++++++
/usr/lib/x86_64-linux-gnu/libcuda.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['9.0', '9.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

Error named symbol not found at line 117 in file /home/johannes/bitsandbytes/csrc/ops.cu




I got this on a H100 when installing as suggested:

git clone https://github.com/timdettmers/bitsandbytes.git
cd bitsandbytes
# CUDA_VERSIONS in {110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 120}
# make argument in {cuda110, cuda11x, cuda12x}
# if you do not know what CUDA you have, try looking at the output of: python -m bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install


I want to use llama-recipes which requires 0.39.1 but using 0.39.1 I get another error...

================================================================================
bin /home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
False
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 9.0
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Required library version not found: libbitsandbytes_cuda122.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=122
python setup.py install
CUDA SETUP: Setup Failed!
/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/johannes/miniconda3/envs/lrec did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
Traceback (most recent call last):
  File "/home/johannes/codejs/llama-recipes/llamarun.py", line 8, in <module>
    model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2886, in from_pretrained
    from .utils.bitsandbytes import get_keys_to_not_convert, replace_with_bnb_linear
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/transformers/utils/bitsandbytes.py", line 12, in <module>
    import bitsandbytes as bnb
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/johannes/miniconda3/envs/lrec/lib/python3.11/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by lonngxiang** [comment]
run：python -m bitsandbytes
result：bitsandbytes/__main__.py", line 100, in <module>
    from .cuda_setup.main import get_compute_capabilities, get_cuda_lib_handle
ImportError: cannot import name 'get_cuda_lib_handle' from 'bitsandbytes.cuda_setup.main' (/mnt/data/anaconda3/envs/pytorch-cuda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py)

**Comment by andrewssobral** [comment]
Same problem, added my remarks here:
https://github.com/TimDettmers/bitsandbytes/issues/566
and here:
https://github.com/TimDettmers/bitsandbytes/issues/382

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
