### ISSUE TITLE
Cuda version 11.8 eta?

### ISSUE THREAD

**Issue by auwsom** [TimDettmers/bitsandbytes#58]
Hi, I just reinstalled cuda and picked the latest version 11.8. I dont see a file for libbitsandbytes_cuda118.so. I'll uninstall and downgrade.

**Comment by auwsom** [comment]
fyi, downgrading worked.. Ubuntu has a conflict between `apt install nvidia-utils-515` and `apt install nvidia-cuda-toolkit`. The latter uninstalls 515 and the former uninstalls cuda. Have to manually install (https://askubuntu.com/questions/1424400/ubuntu-22-04-cannot-install-nvidia-utils-515-and-nvidia-cuda-toolkit).

**Comment by TimDettmers** [comment]
I will work on this ASAP. Thank you for your patience.
