### ISSUE TITLE
bitsandbytes can't detect CUDA inside docker

### ISSUE THREAD

**Issue by MelsHakobyan96** [TimDettmers/bitsandbytes#584]
I am trying to deploy falcon-40b 4bit quantized model on aws instance that has an A10 GPU and CUDA 12.0 installed, I guess the problem is in my docker so here is the Docker file which was generated automatically by the truss library

ARG PYVERSION=py39
FROM baseten/truss-server-base:3.9-gpu-v0.4.9
ENV PYTHON_EXECUTABLE python3
RUN grep -w 'ID=debian\|ID_LIKE=debian' /etc/os-release || { echo "ERROR: Supplied base image is not a debian image"; exit 1; }
RUN $PYTHON_EXECUTABLE -c "import sys; sys.exit(0) if sys.version_info.major == 3 and sys.version_info.minor >=8 and sys.version_info.minor <=11 else sys.exit(1)" \
    || { echo "ERROR: Supplied base image does not have 3.8 <= python <= 3.11"; exit 1; }
RUN pip install --upgrade pip --no-cache-dir \
    && rm -rf /root/.cache/pip
COPY ./requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir && rm -rf /root/.cache/pip
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY ./data /app/data
COPY ./server /app
COPY ./model /app/model
COPY ./config.yaml /app/config.yaml
COPY ./packages /packages
ENV INFERENCE_SERVER_PORT 8080
ENV SERVER_START_CMD="python3 /app/inference_server.py"
ENTRYPOINT ["python3", "/app/inference_server.py"]

and here is the config.yaml for truss

pply_library_patches: true
bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: Falcon-40B
model_type: custom
python_version: py39
requirements:
- torch
- peft
- sentencepiece
- accelerate
- bitsandbytes
- einops
- scipy
- git+https://github.com/huggingface/transformers.git
resources:
  use_gpu: true
  cpu: "3"
  memory: 23Gi
secrets: {}
spec_version: '2.0'
system_packages: []

{"asctime": "2023-07-13 12:24:51,347", "levelname": "INFO", "message": "Setting max asyncio worker threads as 32"}
{"asctime": "2023-07-13 12:24:51,350", "levelname": "INFO", "message": "starting uvicorn with 1 workers"}
{"asctime": "2023-07-13 12:24:51,366", "levelname": "INFO", "message": "Executing model.load()..."}
{"asctime": "2023-07-13 12:24:51,366", "levelname": "INFO", "message": "Application startup complete."}
THE DEVICE INFERENCE IS RUNNING ON IS:  cuda
Downloading (…)okenizer_config.json: 100%|██████████| 287/287 [00:00<00:00, 79.6kB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 2.73M/2.73M [00:00<00:00, 33.9MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 281/281 [00:00<00:00, 439kB/s]
Downloading (…)lve/main/config.json: 100%|██████████| 1.05k/1.05k [00:00<00:00, 308kB/s]
Downloading (…)figuration_falcon.py: 100%|██████████| 6.70k/6.70k [00:00<00:00, 2.19MB/s]
A new version of the following files was downloaded from https://huggingface.co/tiiuae/falcon-40b-instruct:
- configuration_falcon.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading (…)n/modeling_falcon.py: 100%|██████████| 56.9k/56.9k [00:00<00:00, 16.6MB/s]
A new version of the following files was downloaded from https://huggingface.co/tiiuae/falcon-40b-instruct:
- modeling_falcon.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Downloading (…)model.bin.index.json: 100%|██████████| 39.3k/39.3k [00:00<00:00, 11.4MB/s]
Downloading (…)l-00001-of-00009.bin: 100%|██████████| 9.50G/9.50G [00:18<00:00, 517MB/s]
Downloading (…)l-00002-of-00009.bin: 100%|██████████| 9.51G/9.51G [00:17<00:00, 536MB/s]
Downloading (…)l-00003-of-00009.bin: 100%|██████████| 9.51G/9.51G [00:17<00:00, 538MB/s]
Downloading (…)l-00004-of-00009.bin: 100%|██████████| 9.51G/9.51G [00:17<00:00, 549MB/s]
Downloading (…)l-00005-of-00009.bin: 100%|██████████| 9.51G/9.51G [00:17<00:00, 545MB/s]
Downloading (…)l-00006-of-00009.bin: 100%|██████████| 9.51G/9.51G [00:18<00:00, 524MB/s]
Downloading (…)l-00007-of-00009.bin: 100%|██████████| 9.51G/9.51G [00:17<00:00, 543MB/s]
Downloading (…)l-00008-of-00009.bin: 100%|██████████| 9.51G/9.51G [00:18<00:00, 502MB/s]
Downloading (…)l-00009-of-00009.bin: 100%|██████████| 7.58G/7.58G [00:15<00:00, 502MB/s]
Downloading shards: 100%|██████████| 9/9 [02:38<00:00, 17.66s/it] [00:14<00:00, 487MB/s]===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please runpython -m bitsandbytes and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /usr/local/lib/python3.9/dist-packages/bitsandbytes/libbitsandbytes_cuda112.so
False
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/extras/CUPTI/lib64'), PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(msg)
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('python3 /app/inference_server.py')}
  warn(msg)
/usr/local/lib/python3.9/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Required library version not found: libbitsandbytes_cuda112.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================  warn(msg)
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=112 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
{"asctime": "2023-07-13 12:27:32,812", "levelname": "WARNING", "message": "Failed to load model. Retrying..."}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Required library version not found: libbitsandbytes_cuda112.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=112 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
{"asctime": "2023-07-13 12:27:34,136", "levelname": "WARNING", "message": "Failed to load model. Retrying. Retry count: 1"}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Required library version not found: libbitsandbytes_cuda112.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=112 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
{"asctime": "2023-07-13 12:27:35,520", "levelname": "WARNING", "message": "Failed to load model. Retrying. Retry count: 2"}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Required library version not found: libbitsandbytes_cuda112.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=112 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
{"asctime": "2023-07-13 12:27:36,789", "levelname": "ERROR", "message": "Exception while loading model", "exc_info": "Traceback (most recent call last):\n  File \"/app/model_wrapper.py\", line 52, in load\n    self.try_load()\n  File \"/app/model_wrapper.py\", line 114, in try_load\n    retry(\n  File \"/app/common/retry.py\", line 20, in retry\n    raise exc\n  File \"/app/common/retry.py\", line 15, in retry\n    fn()\n  File \"/app/model/model.py\", line 20, in load\n    model_4bit = AutoModelForCausalLM.from_pretrained(\n  File \"/usr/local/lib/python3.9/dist-packages/transformers/models/auto/auto_factory.py\", line 481, in from_pretrained\n    return model_class.from_pretrained(\n  File \"/usr/local/lib/python3.9/dist-packages/transformers/modeling_utils.py\", line 2710, in from_pretrained\n    from .utils.bitsandbytes import get_keys_to_not_convert, replace_with_bnb_linear\n  File \"/usr/local/lib/python3.9/dist-packages/transformers/utils/bitsandbytes.py\", line 12, in <module>\n    import bitsandbytes as bnb\n  File \"/usr/local/lib/python3.9/dist-packages/bitsandbytes/__init__.py\", line 6, in <module>\n    from . import cuda_setup, utils, research\n  File \"/usr/local/lib/python3.9/dist-packages/bitsandbytes/research/__init__.py\", line 1, in <module>\n    from . import nn\n  File \"/usr/local/lib/python3.9/dist-packages/bitsandbytes/research/nn/__init__.py\", line 1, in <module>\n    from .modules import LinearFP8Mixed, LinearFP8Global\n  File \"/usr/local/lib/python3.9/dist-packages/bitsandbytes/research/nn/modules.py\", line 8, in <module>\n    from bitsandbytes.optim import GlobalOptimManager\n  File \"/usr/local/lib/python3.9/dist-packages/bitsandbytes/optim/__init__.py\", line 6, in <module>\n    from bitsandbytes.cextension import COMPILED_WITH_CUDA\n  File \"/usr/local/lib/python3.9/dist-packages/bitsandbytes/cextension.py\", line 20, in <module>\n    raise RuntimeError('''\nRuntimeError: \n        CUDA Setup failed despite GPU being available. Please run the following command to get more information:\n\n        python -m bitsandbytes\n\n        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them\n        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes\n        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues"}

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
