### ISSUE TITLE
Slow inference speed of T5 model using huggingface "load_in_8bits/4bits" option in load_pretrained_model

### ISSUE THREAD

**Issue by JiancongWang** [TimDettmers/bitsandbytes#585]
### Problem description
Hi guys,
I am trying out the load_in_4bit/load_in_8bit options in huggingface's `from_pretrained()` to see if it speed up model inference. By checking the source code I an confirm it is calling bitsandbytes to replace linear layers in the transformer layer.  My understanding is that by quantizing the model, the inference speed will improve. However that's not the case. I use a simple script (see reproduction below) to test out speed on a T5 XXL model for 4bits/8bits/fp32, and actually fp32 model runs the fastest (0.07sec), and the 4bits/8bits run almost in the same speed (0.1sec). So I want to double check if that's expected to be the case. I posted this issue in the huggingface Issues and was referred to report here. See https://github.com/huggingface/transformers/issues/24762.

### System Info

To reproduce, I am running on CUDA 12.1/Driver 530 on an A100 with Ubuntu 20.04. I am running with the following packages
accelerate                    0.21.0.dev0
triton                        2.0.0
transformers                  4.31.0.dev0
torch                         2.0.1
bitsandbytes                  0.40.0.post3

Output from the transformers-cli env is 
- `transformers` version: 4.31.0.dev0
- Platform: Linux-5.15.0-1015-aws-x86_64-with-glibc2.17
- Python version: 3.8.12
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Reproduction

The script I am using to test the speed is here

```
from transformers import T5Tokenizer, T5ForConditionalGeneration
import torch
import pdb
import gc
import time
import os
device_id = 3
tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-xxl")
input_text = "translate English to German: How old are you?" * 20
input_ids = tokenizer(input_text, return_tensors="pt").input_ids[:, :128].to(f"cuda:{device_id}")

# Actual model loading
max_memory = f'{int(torch.cuda.mem_get_info()[0]/1024**3)-2}GB'
model_4bits = T5ForConditionalGeneration.from_pretrained(
    "google/flan-t5-xxl", 
    load_in_4bit=True,
    max_memory=max_memory)

# model_8bits = T5ForConditionalGeneration.from_pretrained(
#     "google/flan-t5-xxl", 
#     load_in_8bit=True,
#     max_memory=max_memory)

# model_fp32 = T5ForConditionalGeneration.from_pretrained(
#     "google/flan-t5-xxl").to(f"cuda:{device_id}")

def benchmark(model_name, model, input_ids):
    # warmup
    for _ in range(200):
        model.encoder(input_ids)

    torch.cuda.synchronize()
    with torch.no_grad():
        start = time.time()
        for i in range(200):
            model.encoder(input_ids)
            
        torch.cuda.synchronize()
        end = time.time()

        print(f"{model_name} inference time is {(end-start)/200} sec")

benchmark("model_4bits", model_4bits, input_ids) # model_4bits inference time is 0.1036052393913269 sec
# benchmark("model_8bits", model_8bits, input_ids) # model_8bits inference time is 0.1006016504764557 sec
# benchmark("model_fp32", model_fp32, input_ids) # model_fp32 inference time is 0.0731453263759613 sec
```

### Expected behavior

I expect the 4 bits model runs faster than the 8bits model, which in turn runs faster than the fp32 model. That's not the case I observe.

**Comment by TimDettmers** [comment]
The 8-bit models are not optimized for inference and will remain slow.

The 4-bit inference kernels are currently only supported for batch size 1 (meaning a single token). As such, in a encoder-decoder architecture the encoder is slow and  the cross attention. These need to be deactivated to receive speedups. Furthermore, `model.encoder()` encodes the entire sequence and as such will never use the inference kernels which need batch size 1 (token by token generation). 

You can take account of these by using the following config:
```python
model_4bits = T5ForConditionalGeneration.from_pretrained(
    "google/flan-t5-xxl", 
    load_in_4bit=False,
    max_memory=max_memory,
    torch_dtype=torch.bfloat16,
    bnb_4bit_compute_dtype=torch.bfloat16,
    llm_int8_skip_modules=['lm_head', 'encoder', 'EncDecAttention'],
    bnb_4bit_use_double_quant=True,
    device_map='auto')
```

This only leads to a minor speedup of 1.62x for my GPU (RTX 4090) since most of the matmul are still in bfloat16. I cannot fit the model with FP32, but compared to FP32 the speedup should roughly double with this configuration.

T5 is just not a great model if batch size = 1 is supported. We will support multi-batch 4-bit kernels in the future, but this will take time.

**Comment by lppllppl920** [comment]
I observed that the Falcon40B model inference speed with 4-bit NF4 quantization remains the same with bitsandbytes version 0.39.0 and 0.40.2. I don't know if what I did below is correct in terms of making sure the batch size equals 1. Any thoughts on this? I am using CUDA 12.1 on NVIDIA A6000.

`import time
import importlib.metadata
from packaging import version
import tqdm

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)

@torch.no_grad()
def generate_text(model, input_text, tokenizer, device, max_length=50):
    # Convert input_text to model's required format
    inputs = tokenizer.encode_plus(input_text, return_tensors="pt").to(device)

    generated_text = input_text
    start = time.time()
    for i in range(max_length):
        # Generate a single token
        outputs = model.generate(
            inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_length=len(inputs["input_ids"][0]) + 1,
            do_sample=True,
            num_return_sequences=1,
        )
        # Decode it to text
        generated_token_id = outputs[0][-1]
        generated_token = tokenizer.decode(generated_token_id, skip_special_tokens=True)
        # Add it to the generated text
        generated_text += generated_token
        # Use the newly generated sequence as the next model's input
        inputs = tokenizer.encode_plus(generated_text, return_tensors="pt").to(device)

        # Check if the generated token is the EOS token or the max_length has been reached
        if generated_token_id == tokenizer.eos_token_id or i == max_length - 1:
            break

    torch.cuda.synchronize()
    end = time.time()
    print(f"Inference time is {(i + 1) / (end-start)} tokens/sec")
    return generated_text

print(
    f"Bitsandbytes version: {version.parse(importlib.metadata.version('bitsandbytes'))}"
)

model_id = "/home/user/tiiuae_falcon-40b"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

model_4bit = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    trust_remote_code=True,
    device_map="auto",
)
tokenizer = AutoTokenizer.from_pretrained(model_id)

text = "Hello my name is"
device = "cuda:0"
inputs: dict = tokenizer(text, return_tensors="pt").to(device)

inputs.pop("token_type_ids")

# Test
text = "Hello my name is"
print(generate_text(model_4bit, text, tokenizer, "cuda:0"))



`
