### ISSUE TITLE
python -m bitsandbytes error message

### ISSUE THREAD

**Issue by tginart** [TimDettmers/bitsandbytes#588]
pytorch) ubuntu@164-152-21-24:~$ python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/ubuntu/anaconda3/envs/pytorch/lib/libcudart.so.11.0'), PosixPath('/home/ubuntu/anaconda3/envs/pytorch/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/ubuntu/anaconda3/envs/pytorch/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/ubuntu/anaconda3/envs/pytorch/nsight-compute/2023.1.1/target/linux-desktop-t210-a64/libcuda-injection.so
/home/ubuntu/anaconda3/envs/pytorch/nsight-compute/2023.1.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/home/ubuntu/anaconda3/envs/pytorch/nsight-compute/2023.1.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/lib/libc10_cuda.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/ubuntu/anaconda3/envs/pytorch/lib/libcudart.so
/home/ubuntu/anaconda3/envs/pytorch/lib/stubs/libcuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/ubuntu/anaconda3/pkgs/cuda-cudart-dev-11.6.55-h42ad0f4_0/lib/libcudart.so
/home/ubuntu/anaconda3/pkgs/icu-58.2-he6710b0_3/lib/libicudata.so
/home/ubuntu/anaconda3/pkgs/nsight-compute-2023.1.1.4-0/nsight-compute/2023.1.1/target/linux-desktop-t210-a64/libcuda-injection.so
/home/ubuntu/anaconda3/pkgs/nsight-compute-2023.1.1.4-0/nsight-compute/2023.1.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/home/ubuntu/anaconda3/pkgs/nsight-compute-2023.1.1.4-0/nsight-compute/2023.1.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/home/ubuntu/anaconda3/pkgs/cuda-driver-dev-11.6.55-0/lib/stubs/libcuda.so
/home/ubuntu/anaconda3/envs/pytorch/nsight-compute/2023.1.1/target/linux-desktop-t210-a64/libcuda-injection.so
/home/ubuntu/anaconda3/envs/pytorch/nsight-compute/2023.1.1/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/home/ubuntu/anaconda3/envs/pytorch/nsight-compute/2023.1.1/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/lib/libc10_cuda.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/ubuntu/anaconda3/envs/pytorch/lib/libcudart.so
/home/ubuntu/anaconda3/envs/pytorch/lib/stubs/libcuda.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/ubuntu/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/ubuntu/anaconda3/lib/libicudata.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.11/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
               ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'LD_LIBRARY_PATH'

**Comment by TimDettmers** [comment]
Thank you, this has been fixed and will soon be released in the lastest bitsandbytes version.
