### ISSUE TITLE
why python can't import the libbitsandbytes_cuda122.dll in specified path(D:\Toolkit\conda\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.dll) even though the dll file is already in the path 

### ISSUE THREAD

**Issue by NgAgoM** [TimDettmers/bitsandbytes#590]
## maybe python -m bitsandbytes useful info 
CUDA SETUP: Loading binary D:\Toolkit\conda\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.dll...
Could not find module 'D:\Toolkit\conda\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Something unexpected happened. Please compile from source:

##  ls  D:\Toolkit\conda\envs\textgen\lib\site-packages\bitsandbytes
-a----         2023/7/14     17:22       15174144 libbitsandbytes_cuda122.dll
-a----         2023/7/14     17:22         208370 libbitsandbytes_cuda122.exp
-a----         2023/7/14     17:22         351180 libbitsandbytes_cuda122.lib
-a----         2023/7/14     17:22       28902912 libbitsandbytes_cuda122_nocublaslt.dll
-a----         2023/7/14     17:22         206795 libbitsandbytes_cuda122_nocublaslt.exp
-a----         2023/7/14     17:22         357540 libbitsandbytes_cuda122_nocublaslt.lib

appreciate !!!!

**Comment by TimDettmers** [comment]
Which bitsandbytes version are you running? 

It might be a small fix, but currently, Windows is not supported and I cannot promise a fix. You can find more information here: #30

**Comment by NgAgoM** [comment]
appreciate

**Comment by sr2mg** [comment]
Please try it.
pip install bitsandbytes==0.39.1 --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui

**Comment by liangdong415** [comment]
hi @NgAgoM , wonder where did you get the libbitsandbytes_cuda122.dll? Thanks
