### ISSUE TITLE
cublaslt ran into an error! On h100

### ISSUE THREAD

**Issue by Ar770** [TimDettmers/bitsandbytes#599]
I'm not sure what is the status of the other issues opened related to this problem, I can confirm that the problem remaines with 0.40.1 on an H100 instance. 
See here the complete error:
[#538](https://github.com/TimDettmers/bitsandbytes/issues/538#issuecomment-1637150778) 

I was in touch with the Lambdalabs support, maybe it could help. 
I added their response here: 
[#383](https://github.com/TimDettmers/bitsandbytes/issues/383#issuecomment-1633659087)

**Comment by TimDettmers** [comment]
Thanks for letting me know. I looked at the details and it turns out Hopper does not support `col_turning` or `col_ampere` formats. As such, new logic is needed. I might implement the FP8 version instead for Hopper.

**Comment by Ar770** [comment]
Thank you!
Do you have ETA to resolve this issue?

**Comment by Mythli** [comment]
Hi @TimDettmers ,

Thank you for your amazing work.
While I'm not qualified to fix this issue myself I can provide a bounty so you could focus on it.

I can provide an H100 for testing as well.

Please reach out to me at tobias@butlerapp.de

**Comment by jieWANGforwork** [comment]
I encountered the same error as loading 8bit Llama on H100. Are there any solutions?

**Comment by hyaticua** [comment]
Hi this still seems to be an issue.

**Comment by corbt** [comment]
Confirming this is still an issue, and would love to get it fixed so we can use H100s for training!

**Comment by karroo** [comment]
I have the same error on H100!!!

**Comment by zhangj1an** [comment]
still having the same issue

**Comment by Jean-KOUAGOU** [comment]
I get the following: Error operation not supported at line 380 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/pythonInterface.c with H100 GPU

**Comment by yz26cn** [comment]
Still getting the issue on H100 with 8-bit setup. 4-bit works as usual but 8-bit does.
