### ISSUE TITLE
What is the latest version of bitsandbytes supported on Windows Python 3.10.x with cuda support?

### ISSUE THREAD

**Issue by FurkanGozukara** [TimDettmers/bitsandbytes#614]
What is the latest version of bitsandbytes supported on Windows Python 3.10.x with cuda support?

**Comment by neural-oracle** [comment]
I have a windows machine and successfully got bitsandbytes running with cuda 12.2
however, I used the following bitsandbytes version:
Dont know if you have windows system ... 
on Windows i had to search 24hours for solution regarding conflict between CUDA and bitsandbytes.
For me the following windows version of bitsandbytes helped:

pip install bitsandbytes-windows

search on github ... there is a repository for bitsandbytes-windows

**Comment by FurkanGozukara** [comment]
> I have a windows machine and successfully got bitsandbytes running with cuda 12.2 however, I used the following bitsandbytes version: Dont know if you have windows system ... on Windows i had to search 24hours for solution regarding conflict between CUDA and bitsandbytes. For me the following windows version of bitsandbytes helped:
> 
> pip install bitsandbytes-windows
> 
> search on github ... there is a repository for bitsandbytes-windows

I think that is older version but will test ty

**Comment by MuhammadShifa** [comment]
Try this: it's worked for me in Window 10.
```
pip uninstall bitsandbytes
pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.0-py3-none-win_amd64.whl
```

**Comment by spydaz** [comment]
i will try but i have also been trying every post toget this working on windows again !! < makes me sad because i also just got flashattention compiled with cuda at last !
