### ISSUE TITLE
What is the meaning of CB CxB SB SCB CxBt SBt CBt?

### ISSUE THREAD

**Issue by Waylon-Zhu** [TimDettmers/bitsandbytes#624]
Hello, I'm reading the source code of LLM.int8(), and found it was Implemented in Linear8bitLt, But I can't understand this implementation

**Comment by Little0o0** [comment]
I'm curious about these too. Did you get the answer?

**Comment by Little0o0** [comment]
I found that:
CB and CBt are the quantized matrix (Int) of B ( col based and row based). SCB and SCBt are the quantized step sizes.  CxB and CxBt are the transformed versions for the quantized matrix CB and CBt. SB is a tuple to store the information: (shapeB, formatB)
