### ISSUE TITLE
CUDA SETUP: CUDA detection failed!

### ISSUE THREAD

**Issue by DStarEpoch** [TimDettmers/bitsandbytes#625]
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
>  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
> False
> /home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/software/anaconda3/envs/work/lib/libcudart.so'), PosixPath('/home/software/anaconda3/envs/work/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
> Either way, this might cause trouble in the future:
> If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
>   warn(msg)
> CUDA SETUP: CUDA runtime path found: /home/software/anaconda3/envs/work/lib/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.6
> CUDA SETUP: Detected CUDA version 118
> CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.so. Maybe you need to compile it from source?
> CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
> 
> ================================================ERROR=====================================
> CUDA SETUP: CUDA detection failed! Possible reasons:
> 1. CUDA driver not installed
> 2. CUDA not installed
> 3. You have multiple conflicting CUDA libraries
> 4. Required library not pre-compiled for this bitsandbytes release!
> CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
> CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
> ================================================================================
> 
> CUDA SETUP: Something unexpected happened. Please compile from source:
> git clone git@github.com:TimDettmers/bitsandbytes.git
> cd bitsandbytes
> CUDA_VERSION=118 make cuda11x
> python setup.py install
> CUDA SETUP: Setup Failed!
> Traceback (most recent call last):
>   File "/home/software/anaconda3/envs/work/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/home/software/anaconda3/envs/work/lib/python3.10/runpy.py", line 146, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/home/software/anaconda3/envs/work/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
>     from . import cuda_setup, utils, research
>   File "/home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
>     from . import nn
>   File "/home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
>     from .modules import LinearFP8Mixed, LinearFP8Global
>   File "/home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
>     from bitsandbytes.optim import GlobalOptimManager
>   File "/home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
>     from bitsandbytes.cextension import COMPILED_WITH_CUDA
>   File "/home/software/anaconda3/envs/work/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
>     raise RuntimeError('''
> RuntimeError:
>         CUDA Setup failed despite GPU being available. Please run the following command to get more information:
> 
>         python -m bitsandbytes
> 
>         Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

I got this error with install cudatoolkit by conda.
Here is my trial for this.
1. Remove one of libcudart.so.11.0 and libcudart.so.
2.  Build bitsandbytes by source  from github.

But neither of theses can solve this bug. How to solve this?

Sincerely, thanks!

**Comment by vishal-kvn** [comment]
I am experiencing the same issue. Just started seeing the error today. Any pointers to resolve the issue will be greatly appreciated. 

Thanks in advance.

**Comment by DStarEpoch** [comment]
> I am experiencing the same issue. Just started seeing the error today.
> 
> I am using Sagemaker Studio for fine tuning the falcon-7b model on g5.2xl instance type and Data Science 3.0 kernel.
> 
> Any pointers to resolve the issue will be greatly appreciated.
> 
> Thanks in advance.

I solve this by reinstall a specific version of cuda.
Problem come from this, I used to install cudatoolkit by conda like 
`conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit`
After I checking cuda driver by `nvidia-smi` and get ouput:

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 470.94       Driver Version: 470.94       CUDA Version: 11.4     |
> |-------------------------------+----------------------+----------------------+

I realise my cuda driver cannot support cuda-11.8.0, so I install cuda-11.3 and rebuild bitsandbytes from source. Solved!
