### ISSUE TITLE
Error in this : nvidia/cuda:12.2.0-devel-ubuntu20.04

### ISSUE THREAD

**Issue by djaym7** [TimDettmers/bitsandbytes#633]
False

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
The following directories listed in your path were found to be non-existent: {PosixPath('["/tmp/vscode-ssh-auth-24e3e3c5-ae2c-4735-9c34-71e7b9c82dd1.sock","/root/.gnupg/S.gpg-agent"]')}
The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/vscode-ipc-faea15fa-6319-4352-afd8-76c6ea1a316e.sock')}
The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /usr/local/lib/python3.11/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x_nomatmul
python setup.py install
/usr/local/lib/python3.11/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
/usr/local/lib/python3.11/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/usr/local/lib/python3.11/dist-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 3
      1 import os
      2 import torch
----> 3 from peft import PeftModel, PeftConfig
      4 from transformers import AutoModelForCausalLM as AutoModelForSeq2SeqLM
      5 from transformers import AutoTokenizer

File /usr/local/lib/python3.11/dist-packages/peft/__init__.py:22
      1 # flake8: noqa
      2 # There's no way to ignore "F401 '...' imported but unused" warnings in this
      3 # module, but to preserve other warnings. So, don't check this module at all.
   (...)
     17 # See the License for the specific language governing permissions and
     18 # limitations under the License.
     20 __version__ = "0.5.0.dev0"
---> 22 from .auto import (
     23     AutoPeftModel,
     24     AutoPeftModelForCausalLM,
     25     AutoPeftModelForSequenceClassification,
     26     AutoPeftModelForSeq2SeqLM,
     27     AutoPeftModelForTokenClassification,
     28     AutoPeftModelForQuestionAnswering,
     29     AutoPeftModelForFeatureExtraction,
     30 )
     31 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
     32 from .peft_model import (
     33     PeftModel,
     34     PeftModelForCausalLM,
   (...)
     39     PeftModelForFeatureExtraction,
     40 )

File /usr/local/lib/python3.11/dist-packages/peft/auto.py:30
     19 from typing import Optional
     21 from transformers import (
     22     AutoModel,
     23     AutoModelForCausalLM,
   (...)
     27     AutoModelForTokenClassification,
     28 )
---> 30 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
     31 from .peft_model import (
     32     PeftModel,
     33     PeftModelForCausalLM,
   (...)
     38     PeftModelForTokenClassification,
     39 )
     40 from .utils import PeftConfig

File /usr/local/lib/python3.11/dist-packages/peft/mapping.py:20
     16 from __future__ import annotations
     18 from typing import TYPE_CHECKING, Any, Dict
---> 20 from .peft_model import (
     21     PeftModel,
     22     PeftModelForCausalLM,
     23     PeftModelForFeatureExtraction,
     24     PeftModelForQuestionAnswering,
     25     PeftModelForSeq2SeqLM,
     26     PeftModelForSequenceClassification,
     27     PeftModelForTokenClassification,
     28 )
     29 from .tuners import (
     30     AdaLoraConfig,
     31     AdaptionPromptConfig,
   (...)
     36     PromptTuningConfig,
     37 )
     38 from .utils import PromptLearningConfig, _prepare_prompt_learning_config

File /usr/local/lib/python3.11/dist-packages/peft/peft_model.py:26
     23 from typing import Any, Dict, List, Optional, Union
     25 import torch
---> 26 from accelerate import dispatch_model, infer_auto_device_map
     27 from accelerate.hooks import AlignDevicesHook, add_hook_to_module, remove_hook_from_submodules
     28 from accelerate.utils import get_balanced_memory

File /usr/local/lib/python3.11/dist-packages/accelerate/__init__.py:3
      1 __version__ = "0.21.0"
----> 3 from .accelerator import Accelerator
      4 from .big_modeling import (
      5     cpu_offload,
      6     cpu_offload_with_hook,
   (...)
     11     load_checkpoint_and_dispatch,
     12 )
     13 from .data_loader import skip_first_batches

File /usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py:35
     32 import torch
     33 import torch.utils.hooks as hooks
---> 35 from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
     36 from .data_loader import DataLoaderDispatcher, prepare_data_loader, skip_first_batches
     37 from .logging import get_logger

File /usr/local/lib/python3.11/dist-packages/accelerate/checkpointing.py:24
     21 import torch
     22 from torch.cuda.amp import GradScaler
---> 24 from .utils import (
     25     MODEL_NAME,
     26     OPTIMIZER_NAME,
     27     RNG_STATE_NAME,
     28     SCALER_NAME,
     29     SCHEDULER_NAME,
     30     get_pretty_name,
     31     is_tpu_available,
     32     is_xpu_available,
     33     save,
     34 )
     37 if is_tpu_available(check_device=False):
     38     import torch_xla.core.xla_model as xm

File /usr/local/lib/python3.11/dist-packages/accelerate/utils/__init__.py:131
    121 if is_deepspeed_available():
    122     from .deepspeed import (
    123         DeepSpeedEngineWrapper,
    124         DeepSpeedOptimizerWrapper,
   (...)
    128         HfDeepSpeedConfig,
    129     )
--> 131 from .bnb import has_4bit_bnb_layers, load_and_quantize_model
    132 from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer
    133 from .launch import (
    134     PrepareForLaunch,
    135     _filter_args,
   (...)
    140     prepare_tpu,
    141 )

File /usr/local/lib/python3.11/dist-packages/accelerate/utils/bnb.py:42
     31 from .modeling import (
     32     find_tied_parameters,
     33     get_balanced_memory,
   (...)
     37     set_module_tensor_to_device,
     38 )
     41 if is_bnb_available():
---> 42     import bitsandbytes as bnb
     44 from copy import deepcopy
     47 logger = logging.getLogger(__name__)

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/__init__.py:6
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from . import cuda_setup, utils, research
      7 from .autograd._functions import (
      8     MatmulLtState,
      9     bmm_cublas,
   (...)
     13     matmul_4bit
     14 )
     15 from .cextension import COMPILED_WITH_CUDA

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/research/__init__.py:1
----> 1 from . import nn
      2 from .autograd._functions import (
      3     switchback_bnb,
      4     matmul_fp8_global,
      5     matmul_fp8_mixed,
      6 )

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/research/nn/__init__.py:1
----> 1 from .modules import LinearFP8Mixed, LinearFP8Global

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/research/nn/modules.py:8
      5 from torch import Tensor, device, dtype, nn
      7 import bitsandbytes as bnb
----> 8 from bitsandbytes.optim import GlobalOptimManager
      9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims
     11 T = TypeVar("T", bound="torch.nn.Module")

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/optim/__init__.py:6
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from bitsandbytes.cextension import COMPILED_WITH_CUDA
      8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
      9 from .adam import Adam, Adam8bit, Adam32bit, PagedAdam, PagedAdam8bit, PagedAdam32bit

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/cextension.py:20
     18     CUDASetup.get_instance().generate_instructions()
     19     CUDASetup.get_instance().print_log_stack()
---> 20     raise RuntimeError('''
     21     CUDA Setup failed despite GPU being available. Please run the following command to get more information:
     22 
     23     python -m bitsandbytes
     24 
     25     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
     26     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
     27     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues''')
     28 lib.cadam32bit_grad_fp32 # runs on an error if the library could not be found -> COMPILED_WITH_CUDA=False
     29 lib.get_context.restype = ct.c_void_p

RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by djaym7** [comment]
even though path is this /usr/local/cuda-12.2/lib64/

**Comment by djaym7** [comment]
after adding /user/local/cuda/12.2/lib64 to LD library path, more errors 

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
The following directories listed in your path were found to be non-existent: {PosixPath('["/tmp/vscode-ssh-auth-24e3e3c5-ae2c-4735-9c34-71e7b9c82dd1.sock","/root/.gnupg/S.gpg-agent"]')}
The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/vscode-ipc-faea15fa-6319-4352-afd8-76c6ea1a316e.sock')}
The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /usr/local/lib/python3.11/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x_nomatmul
python setup.py install
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 3
      1 import os
      2 import torch
----> 3 from peft import PeftModel, PeftConfig
      4 from transformers import AutoModelForCausalLM as AutoModelForSeq2SeqLM
      5 from transformers import AutoTokenizer

File /usr/local/lib/python3.11/dist-packages/peft/__init__.py:22
      1 # flake8: noqa
      2 # There's no way to ignore "F401 '...' imported but unused" warnings in this
      3 # module, but to preserve other warnings. So, don't check this module at all.
   (...)
     17 # See the License for the specific language governing permissions and
     18 # limitations under the License.
     20 __version__ = "0.5.0.dev0"
---> 22 from .auto import (
     23     AutoPeftModel,
     24     AutoPeftModelForCausalLM,
     25     AutoPeftModelForSequenceClassification,
     26     AutoPeftModelForSeq2SeqLM,
     27     AutoPeftModelForTokenClassification,
     28     AutoPeftModelForQuestionAnswering,
     29     AutoPeftModelForFeatureExtraction,
     30 )
     31 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
     32 from .peft_model import (
     33     PeftModel,
     34     PeftModelForCausalLM,
   (...)
     39     PeftModelForFeatureExtraction,
     40 )

File /usr/local/lib/python3.11/dist-packages/peft/auto.py:30
     19 from typing import Optional
     21 from transformers import (
     22     AutoModel,
     23     AutoModelForCausalLM,
   (...)
     27     AutoModelForTokenClassification,
     28 )
---> 30 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
     31 from .peft_model import (
     32     PeftModel,
     33     PeftModelForCausalLM,
   (...)
     38     PeftModelForTokenClassification,
     39 )
     40 from .utils import PeftConfig

File /usr/local/lib/python3.11/dist-packages/peft/mapping.py:20
     16 from __future__ import annotations
     18 from typing import TYPE_CHECKING, Any, Dict
---> 20 from .peft_model import (
     21     PeftModel,
     22     PeftModelForCausalLM,
     23     PeftModelForFeatureExtraction,
     24     PeftModelForQuestionAnswering,
     25     PeftModelForSeq2SeqLM,
     26     PeftModelForSequenceClassification,
     27     PeftModelForTokenClassification,
     28 )
     29 from .tuners import (
     30     AdaLoraConfig,
     31     AdaptionPromptConfig,
   (...)
     36     PromptTuningConfig,
     37 )
     38 from .utils import PromptLearningConfig, _prepare_prompt_learning_config

File /usr/local/lib/python3.11/dist-packages/peft/peft_model.py:26
     23 from typing import Any, Dict, List, Optional, Union
     25 import torch
---> 26 from accelerate import dispatch_model, infer_auto_device_map
     27 from accelerate.hooks import AlignDevicesHook, add_hook_to_module, remove_hook_from_submodules
     28 from accelerate.utils import get_balanced_memory

File /usr/local/lib/python3.11/dist-packages/accelerate/__init__.py:3
      1 __version__ = "0.21.0"
----> 3 from .accelerator import Accelerator
      4 from .big_modeling import (
      5     cpu_offload,
      6     cpu_offload_with_hook,
   (...)
     11     load_checkpoint_and_dispatch,
     12 )
     13 from .data_loader import skip_first_batches

File /usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py:35
     32 import torch
     33 import torch.utils.hooks as hooks
---> 35 from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
     36 from .data_loader import DataLoaderDispatcher, prepare_data_loader, skip_first_batches
     37 from .logging import get_logger

File /usr/local/lib/python3.11/dist-packages/accelerate/checkpointing.py:24
     21 import torch
     22 from torch.cuda.amp import GradScaler
---> 24 from .utils import (
     25     MODEL_NAME,
     26     OPTIMIZER_NAME,
     27     RNG_STATE_NAME,
     28     SCALER_NAME,
     29     SCHEDULER_NAME,
     30     get_pretty_name,
     31     is_tpu_available,
     32     is_xpu_available,
     33     save,
     34 )
     37 if is_tpu_available(check_device=False):
     38     import torch_xla.core.xla_model as xm

File /usr/local/lib/python3.11/dist-packages/accelerate/utils/__init__.py:131
    121 if is_deepspeed_available():
    122     from .deepspeed import (
    123         DeepSpeedEngineWrapper,
    124         DeepSpeedOptimizerWrapper,
   (...)
    128         HfDeepSpeedConfig,
    129     )
--> 131 from .bnb import has_4bit_bnb_layers, load_and_quantize_model
    132 from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer
    133 from .launch import (
    134     PrepareForLaunch,
    135     _filter_args,
   (...)
    140     prepare_tpu,
    141 )

File /usr/local/lib/python3.11/dist-packages/accelerate/utils/bnb.py:42
     31 from .modeling import (
     32     find_tied_parameters,
     33     get_balanced_memory,
   (...)
     37     set_module_tensor_to_device,
     38 )
     41 if is_bnb_available():
---> 42     import bitsandbytes as bnb
     44 from copy import deepcopy
     47 logger = logging.getLogger(__name__)

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/__init__.py:6
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from . import cuda_setup, utils, research
      7 from .autograd._functions import (
      8     MatmulLtState,
      9     bmm_cublas,
   (...)
     13     matmul_4bit
     14 )
     15 from .cextension import COMPILED_WITH_CUDA

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/research/__init__.py:1
----> 1 from . import nn
      2 from .autograd._functions import (
      3     switchback_bnb,
      4     matmul_fp8_global,
      5     matmul_fp8_mixed,
      6 )

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/research/nn/__init__.py:1
----> 1 from .modules import LinearFP8Mixed, LinearFP8Global

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/research/nn/modules.py:8
      5 from torch import Tensor, device, dtype, nn
      7 import bitsandbytes as bnb
----> 8 from bitsandbytes.optim import GlobalOptimManager
      9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims
     11 T = TypeVar("T", bound="torch.nn.Module")

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/optim/__init__.py:6
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from bitsandbytes.cextension import COMPILED_WITH_CUDA
      8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit
      9 from .adam import Adam, Adam8bit, Adam32bit, PagedAdam, PagedAdam8bit, PagedAdam32bit

File /usr/local/lib/python3.11/dist-packages/bitsandbytes/cextension.py:20
     18     CUDASetup.get_instance().generate_instructions()
     19     CUDASetup.get_instance().print_log_stack()
---> 20     raise RuntimeError('''
     21     CUDA Setup failed despite GPU being available. Please run the following command to get more information:
     22 
     23     python -m bitsandbytes
     24 
     25     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
     26     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
     27     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues''')
     28 lib.cadam32bit_grad_fp32 # runs on an error if the library could not be found -> COMPILED_WITH_CUDA=False
     29 lib.get_context.restype = ct.c_void_p

RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by djaym7** [comment]
is there support for CUDA 12.2 yet ?

**Comment by djaym7** [comment]
rebuilt the container, now resolved

**Comment by TobiasWegener** [comment]
> rebuilt the container, now resolved

I am sorry, I have nearly exactly the same hardware and the exact same cuda and Ubuntu version. 
Can you please, shortly explain, what "rebuilt the container" means or point me to a tutorial how to rebuilt it?
Thank very much in advance.

**Comment by djaym7** [comment]
Here's the files I used Dockerfile: 

```

# FROM pure/python:3.7-cuda10.2-cudnn7-runtime
# FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel
# FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
# FROM nvidia/cuda:11.6.0-devel-ubuntu20.04
FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

COPY ./app /app
WORKDIR /app
RUN apt update
RUN apt install curl -y

#install openmpi 
RUN DEBIAN_FRONTEND=noninteractive apt install libopenmpi-dev -y

#install python
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.11-dev -y python3.11-distutils -y
RUN echo 'alias python=python3.11' >> /etc/bash.bashrc
RUN ln -s /usr/bin/python3.11 /usr/local/bin/python
RUN curl https://bootstrap.pypa.io/get-pip.py |  python3.11 -
RUN pip install pip --upgrade
RUN apt install -y git 
RUN apt install -y screen
RUN echo 'termcapinfo xterm* ti@:te@' >> ~/.screenrc
RUN pip install -r /app/requirements.txt
RUN python3.11 -m spacy download en

VOLUME /app

# ENV FLASK_APP=main.py
# ENV FLASK_DEBUG=1 #set in app.run
EXPOSE 8080
ENTRYPOINT ["python","/app/model/LevelWiseTopiclabeling/RTO_v1/gradio_app_active_learning.py"]


#https://linuxopsys.com/topics/how-to-install-vim-text-editor-on-ubuntu to install vim from source

```

Here's the requirements: 


```
matplotlib
nltk
scikit_learn
torch --extra-index-url https://download.pytorch.org/whl/cu117
torchvision --extra-index-url https://download.pytorch.org/whl/cu117
torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
tensorflow
#numpy==1.20.0
pandas
stop-words==2018.7.23
swifter
ipykernel
jupyterlab
tensorboard
tabulate
git+https://github.com/huggingface/transformers
spacy
datasets
sentence-transformers
bert-score
rouge-score
protobuf==3.20.*
bertopic
gradio
pathos
git+https://github.com/microsoft/DeepSpeed.git#egg=deepspeed
git+https://github.com/huggingface/peft.git#egg=peft
#git+https://github.com/huggingface/peft.git@47acddd790791b4408cc87b1188f2684d5a8da8f #solves multi-gpu issue
mpi4py #this will throw error in python 3.10, 'apt install python3.8-dev' and 'curl https://bootstrap.pypa.io/get-pip.py | python3.8' and change alias of python and pip in /etc/bash.bashrc to point to python3.8 and install requirements again. Then install ipykernel for python using 'python -m ipykernel install --name python3.8 --display-name python3.8' .
bitsandbytes

```
