### ISSUE TITLE
CUDA compatibility issue

### ISSUE THREAD

**Issue by Fonchote** [TimDettmers/bitsandbytes#645]
Getting this issue, thoughts?

/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:93: UserWarning: /Tools/anaconda3-Fonchai/envs/Fonchai did not contain libcudart.so as expected! Searching further paths...
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/cv2/../../lib64')}
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain libcudart.so as expected! Searching further paths...
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//nodejs.org/dist')}
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/Fonchai'), PosixPath('@/tmp/.ICE-unix/2507,unix/Fonchai')}
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/0426ca50_bb8f_45d2_b907_b6a91d5218e9')}
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('0')}
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/run/user/1000/fnm_multishells/24930_1690415446698')}
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
  warn(
/Tools/kohya_ss-21.8.2/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic_0dn8tzln/none_9dgt79nw/attempt_0/0/error.json')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda122.so

**Comment by neural-oracle** [comment]
Dont know if you have windows system ... 
on Windows i had to search 24hours for solution regarding conflict between CUDA and bitsandbytes.
For me the following windows version of bitsandbytes helped:

pip install bitsandbytes-windows

search on github ... there is a repository for bitsandbytes-windows

**Comment by Fonchote** [comment]
Thanks!  I tried updating the bitsandbytes package, and also creating symbolic links to libbitsandbytes_cuda122.so in multiple directories.... right now trying to downgrade to cuda 11.8

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
