### ISSUE TITLE
issue while training dolly using windows, pycharm

### ISSUE THREAD

**Issue by snehaxtend** [TimDettmers/bitsandbytes#648]
C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\python.exe "C:/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 62020 --file C:\Users\XTEND\PycharmProjects\Dolly_training\TRAIN.py 
Connected to pydev debugger (build 223.8617.48)
False
===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
The following directories listed in your path were found to be non-existent: {WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pysftp;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/stdlib-list;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/redis;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-bugbear;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/hdbcli;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/requests;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/Flask-Cors;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-builtins;C'), WindowsPath('/Users/XTEND/AppData/Local/JetBrains/PyCharmCE2022.3/python_stubs/-1560385001;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/bleach;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-plugin-utils;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/editdistance;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-typing-imports;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/Send2Trash;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/cryptography;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/vobject;C'), WindowsPath('C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/singledispatch;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/oauthlib;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stdlib;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pyRFC3339;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/whatthepatch;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/toposort;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/decorator;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/psutil;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/tabulate;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/prettytable;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/invoke;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/first;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/croniter;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/DateTimeRange;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/python-slugify;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/aiofiles;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/filelock;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/termcolor;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/entrypoints;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/setuptools;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/dateparser;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/httplib2;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/python-gflags;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/opentracing;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/appdirs;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/emoji;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pyOpenSSL;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pyflakes;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/frozendict;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/chardet;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/regex;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pyfarmhash;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/annoy;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/mysqlclient;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/click-spinner;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/html5lib;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/humanfriendly;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/retry;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pep8-naming;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/PyMySQL;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pyaudio;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/beautifulsoup4;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-rst-docstrings;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/ldap3;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-2020;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/ttkthemes;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/passlib;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/Markdown;C'), WindowsPath('/Users/XTEND/anaconda3/envs/Dtorch_gpu/Lib/site-packages;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/ujson;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/psycopg2;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/cachetools;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pycurl;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/xmltodict;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/certifi;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/dataclasses;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/playsound;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/contextvars;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/python-dateutil;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/selenium;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pytz;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/stripe;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/characteristic;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/six;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/xxhash;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/jsonschema;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/docopt;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/typed-ast;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/python-skeletons;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/JACK-Client;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-docstrings;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/python-jose;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/flake8-simplify;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/polib;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/commonmark;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/jmespath;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/urllib3;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/freezegun;C'), WindowsPath('/Users/XTEND/anaconda3/envs/Dtorch_gpu/Lib;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/tzlocal;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/PyYAML;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pytest-lazy-fixture;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/atomicwrites;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/SQLAlchemy;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pynput;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/aws-xray-sdk;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/python-nmap;C'), WindowsPath('/Users/XTEND/anaconda3/envs/Dtorch_gpu/DLLs;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/toml;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/fpdf2;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/parsimonious;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/Deprecated;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/Pillow;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/Pygments;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/simplejson;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/waitress;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/mypy-extensions;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/mock;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/slumber;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/passpy;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/boto;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/openpyxl;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/braintree;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/colorama;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/Flask-SQLAlchemy;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/caldav;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/chevron;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/pyvmomi;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/babel;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/docutils;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/typeshed/stubs/paramiko;C')}
The following directories listed in your path were found to be non-existent: {WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/third_party/thriftpy;C'), WindowsPath('/Program Files/JetBrains/PyCharm Community Edition 2022.3.2/plugins/python-ce/helpers/pydev;C'), WindowsPath('C'), WindowsPath('/Users/XTEND/AppData/Local/JetBrains/PyCharmCE2022.3/cythonExtensions;C'), WindowsPath('/Users/XTEND/PycharmProjects/Dolly_training;C')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
python-BaseException
C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run
python -m bitsandbytes
  warn(msg)
C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: C:\Users\XTEND\anaconda3\envs\Dtorch_gpu did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
Traceback (most recent call last):
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\transformers\utils\import_utils.py", line 1099, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\transformers\trainer.py", line 39, in <module>
    from .integrations import (
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\transformers\integrations.py", line 71, in <module>
    from .trainer_callback import ProgressCallback, TrainerCallback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\transformers\trainer_callback.py", line 27, in <module>
    from .training_args import TrainingArguments
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\transformers\training_args.py", line 67, in <module>
    from accelerate.state import AcceleratorState, PartialState
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:
        python -m bitsandbytes
        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\XTEND\anaconda3\envs\Dtorch_gpu\Lib\site-packages\transformers\utils\import_utils.py", line 1101, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:
        python -m bitsandbytes
        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
