### ISSUE TITLE
Error operation not supported at line 380 in file [...] pythonInterface.c

### ISSUE THREAD

**Issue by BugReporterZ** [TimDettmers/bitsandbytes#649]
The scenario is as follows:
- I'm using the [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl) trainer with `load_in_8bit` option enabled (which uses bitsandbytes) to fine tune a model on 8x NVidia A40 48GB GPUs (Driver Version: 510.47.03, CUDA Version: 11.6).
- The training machine is a non-commercial Linux VM I have access to, but I don't have administrative control over it.
- `accelerate` is used to start the training script.
- 7B models (e.g. Llama2-7B) load and train fine.

**Problem**: Llama2-13B (or any other 13B-scale model or larger) fails with this error:

```
Error operation not supported at line 380 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/pythonInterface.c
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
```
Which points to this file: https://github.com/TimDettmers/bitsandbytes/blob/main/csrc/pythonInterface.c#L380

What's perplexing:
- There is plenty of VRAM available, yet this appears to be a model size-dependent issue.
- `bitsandbytes` versions 0.40.0 to 0.41.0 have been used with no change: models greater than 7B give issues.
- `load_in_4bit` gives similar problems. Models larger than 7B cannot be trained due to above problem.
- Loading the model in `bf16` of `fp16` doesn't solve the problem.
- Using 1 GPU with `CUDA_VISIBLE_DEVICES=0` doesn't solve the problem.
- _Not_ using the `xformers-attention` monkeypatch provided with Axolotl to reduce VRAM usage doesn't solve the problem.

What could be causing this issue?

**Comment by Nayahei** [comment]
I have the same problem, do you solve it...

**Comment by muhammad-asn** [comment]
How do you solve it sir? I have A100 40GB and A100 80GB

 But only A100 40GB works

**Comment by BugReporterZ** [comment]
It seemed to occur when using _paged_ AdamW optimizer from Bitsandbytes; possibly the VM or its configuration weren't compatible with it. Using regular AdamW worked around the issue.

**Comment by prawiraelang** [comment]
> It seemed to occur when using _paged_ AdamW optimizer from Bitsandbytes; possibly the VM or its configuration weren't compatible with it. Using regular AdamW worked around the issue.

I have checked Transformers documentation [here](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.optim). Could you help with which specific optimizer to use?

**Comment by BugReporterZ** [comment]
I generally use `adamw_bnb_8bit`.

**Comment by prawiraelang** [comment]
> I generally use `adamw_bnb_8bit`. `paged_adamw_8bit` can give issues on some configurations.

Thanks for your suggestion. Will try to use `adamw_bnb_8bit`.

**Comment by prawiraelang** [comment]
I want to confirm that changing the optimizer from `paged_adamw_8bit` to `adamw_bnb_8bit ` resolved the issue.
