### ISSUE TITLE
KeyError: 'LD_LIBRARY_PATH'

### ISSUE THREAD

**Issue by leonleeldc** [TimDettmers/bitsandbytes#655]
(base) dili@02003A220600Z0P CouNLPy % python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
CUDA SETUP: Loading binary /Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
dlopen(/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (no such file), '/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/Users/dili/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/dili/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/Users/dili/miniconda3/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/Users/dili/miniconda3/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'

**Comment by cdhx** [comment]
same issue
