### ISSUE TITLE
aarch64 compilation on a Xavier AGX

### ISSUE THREAD

**Issue by blizzn** [TimDettmers/bitsandbytes#660]
Hi, I wanted to install text-generation-webui on a XAVIER AGX (Volta Architecture) in a docer file l4t that has all the pytorch, vision, audio installed. I tried to troubleshoot it with GPT4 but it tells me that the source code is not for arm64 architecture of the Xavier. 

gpt4 output:
Your output indicates that you have CUDA version 11.4 installed and it is accessible to PyTorch, which means your PyTorch installation can leverage your system's GPU.

This confirms that your GPU and CUDA setup are functioning correctly with respect to PyTorch. The problem you're encountering when building the bitsandbytes package is specific to that package's use of x86-specific SIMD instructions, as I explained earlier. It's not an issue with your CUDA installation or its integration with PyTorch.

For now, you might need to wait for the package maintainers to provide a solution that supports the ARM architecture used by your Jetson Xavier AGX, or attempt to modify the code yourself if you are comfortable doing so.

output of trying to compile it from source:
# CUDA_VERSION=114 make cuda11x_nomatmul
ENVIRONMENT
============================
CUDA_VERSION: 114
============================
NVCC path: /usr/local/cuda/bin/nvcc
GPP path: /usr/bin/g++ VERSION: g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
CUDA_HOME: /usr/local/cuda
CONDA_PREFIX: 
PATH: /usr/local/cuda/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64:
============================
/usr/local/cuda/bin/nvcc -gencode arch=compute_50,code=sm_50  -gencode arch=compute_52,code=sm_52  -gencode arch=compute_60,code=sm_60  -gencode arch=compute_61,code=sm_61  -gencode arch=compute_70,code=sm_70  -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -Xcompiler '-fPIC' --use_fast_math -Xptxas=-v -dc /home/bitsandbytes/csrc/ops.cu /home/bitsandbytes/csrc/kernels.cu -I /usr/local/cuda/include -I /home/bitsandbytes/csrc -I /include -I /home/bitsandbytes/include -L /usr/local/cuda/lib64 -lcudart -lcublas -lcublasLt -lcusparse -L /lib --output-directory /home/bitsandbytes/build -D NO_CUBLASLT
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /home/bitsandbytes/include/BinSearch.h:5,
                 from /home/bitsandbytes/csrc/ops.cu:10:
/home/bitsandbytes/include/SIMD.h:32:10: fatal error: emmintrin.h: No such file or directory
   32 | #include <emmintrin.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:79: cuda11x_nomatmul] Error 1

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
