### ISSUE TITLE
Clarification concerning gradient backpropagation

### ISSUE THREAD

**Issue by gsarti** [TimDettmers/bitsandbytes#67]
I'm trying to extract gradients from Hugging Face models loaded with `load_in_8bit=True` and stumbling on an exception thrown by the `bitsandbytes` library: `State must contain either CBt or CB matrix for backward`. I would like to understand what causes the issue, since I don't think there should be any theoretical limitations to extracting gradients in this way from LLM.int8 models.
 
## Minimal setup to reproduce the issue

- `transformers` version: 4.23.1
- Platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Using GPU in script?: yes, RTX 3060 8GB with CUDA 11.6
- Bitsandbytes version: 0.35.0

```python
import torch
from transformers import AutoModelForSeq2SeqLM,  AutoTokenizer

# if load_in_8bit is specified, the exception will be thrown
# otherwise gradients are extracted normally. Using t5-small as dummy model.
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small", device_map="auto", load_in_8bit=True)
tokenizer = AutoTokenizer.from_pretrained("t5-small", model_max_length=512)
inputs = tokenizer("translate English to German: Hello world!", return_tensors="pt")

with torch.autograd.set_grad_enabled(True):
    inputs_embeds = model.get_input_embeddings()(inputs["input_ids"])
    decoder_inputs_ids = torch.tensor([[tokenizer.pad_token_id]], dtype=torch.int)
    out = model(inputs_embeds=inputs_embeds, decoder_input_ids=decoder_inputs_ids, attention_mask=inputs["attention_mask"])
	# Using first score in output logits as dummy backprop target
    grads = torch.autograd.grad(torch.unbind(out.logits[0,0]), inputs_embeds)
```

## Stack trace

```shell
╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│                                                                                           │
│ /home/.cache/pypoetry/virtualenvs/venv/lib/python3.8/site-packages                        │
│ /torch/autograd/__init__.py:276 in grad                                                   │
│                                                                                           │
│   273 │   │   │   │   allow_unused, accumulate_grad=False)  # Calls into the C++ engine t │
│   274 │   │   return _vmap_internals._vmap(vjp, 0, 0, allow_none_pass_through=True)(grad_ │
│   275 │   else:                                                                           │
│ ❱ 276 │   │   return Variable._execution_engine.run_backward(  # Calls into the C++ engin │
│   277 │   │   │   t_outputs, grad_outputs_, retain_graph, create_graph, t_inputs,         │
│   278 │   │   │   allow_unused, accumulate_grad=False)  # Calls into the C++ engine to ru │
│   279                                                                                     │
│                                                                                           │
│ /home/.cache/pypoetry/virtualenvs/venv/lib/python3.8/site-packages                        │
│ /torch/autograd/function.py:253 in apply                                                  │
│                                                                                           │
│   250 │   │   │   │   │   │   │      "Function is not allowed. You should only implement  │
│   251 │   │   │   │   │   │   │      "of them.")                                          │
│   252 │   │   user_fn = vjp_fn if vjp_fn is not Function.vjp else backward_fn             │
│ ❱ 253 │   │   return user_fn(self, *args)                                                 │
│   254 │                                                                                   │
│   255 │   def apply_jvp(self, *args):                                                     │
│   256 │   │   # _forward_cls is defined by derived class                                  │
│                                                                                           │
│ /home/.cache/pypoetry/virtualenvs/venv/lib/python3.8/site-packages                        │
│ /bitsandbytes/autograd/_functions.py:388 in backward                                      │
│                                                                                           │
│   385 │   │   │   │   CB = state.CB.to(ctx.dtype_A, copy=True).mul_(state.SCB.unsqueeze(1 │
│   386 │   │   │   │   grad_A = torch.matmul(grad_output, CB).view(ctx.grad_shape).to(ctx. │
│   387 │   │   │   else:                                                                   │
│ ❱ 388 │   │   │   │   raise Exception('State must contain either CBt or CB matrix for bac │
│   389 │   │                                                                               │
│   390 │   │   return grad_A, grad_B, None, grad_bias, None                                │
│   391                                                                                     │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
Exception: State must contain either CBt or CB matrix for backward
```

**Comment by gsarti** [comment]
Hi @TimDettmers, any pointer regarding the aforementioned issue? Thanks in advance!

**Comment by TimDettmers** [comment]
Hi @gsarti, the main issue here is that in the current HF implementation the weights are converted to 8-bit and for the backward pass updating 8-bit weights lead to instabilities.

There are three solutions:
1. Use 8-bit/16-bit mixed precision training. This will use 16-bit main weights and 8-bit compute weights similarly to PyTorch automatic mixed precision (AMP). You can enable this by setting the `has_fp16_weights` argument to `True`.
2. Use a frozen model and separate fp16 weights that are learned, similar to [Low-rank Adapters](https://arxiv.org/abs/2106.09685). You need to add new weights and use the `memory_efficient_backward` argument set to `True`
3. Use 8-bit non-linear quantization adapted for your use-case. As a reference you can follow these notebooks: [current](https://colab.research.google.com/drive/1ZzcM_J3AEhpuwxJ8I0qDwVSwU-6Scpbl?usp=sharing), [old](https://huggingface.co/joaoalvarenga/bloom-8bit), [how to convert old to new](https://nbviewer.org/urls/huggingface.co/hivemind/gpt-j-6B-8bit/raw/main/convert-gpt-j.ipynb).

**Comment by gsarti** [comment]
Thank you for your answer @TimDettmers! I am curious whether the instabilities you mention are the results of repeated updates on approximated weights. To provide you with more context, I am not interested in updating the weight per se, but rather using gradients for feature attribution purposes (with the above example being a simplification of the `saliency` method implemented in [Captum](https://captum.ai/api/saliency.html).

In all the solutions you mention I believe there would be an overhead, either in terms of additional memory size required by fp16 weights (1. and 2.), or by having to monkey-patch the custom modules on top of my selected model. Do you see an alternative that would make extracting gradients compatible with the current `load_in_8bit=True` abstraction?

**Comment by hatvn** [comment]
@TimDettmers thank you for suggestion, Actually I tried your second approach: Using frozen model and separate fp16 weights that are learned, and I set memory_efficient_backward = True. I did inject additional parameters and set requires_grad = True for only additional parameters. However, I tried to print the loss at every step of the same input. It seems that the losses didn't change during training loop. I think no update was done for trainable parameters. Do you have any ideas of how to dealing with this. Thank you !

**Comment by gsarti** [comment]
@TimDettmers verified that our use-case is satisfied with the new v0.37.0, thank you! Refer to inseq-team/inseq#163 for an example. Closing this!
