### ISSUE TITLE
Quantized models will silently load in fp16 even with bf16 turned on

### ISSUE THREAD

**Issue by rationalism** [TimDettmers/bitsandbytes#682]
Finally tracked this down after a bunch of digging through Llama's model implementation:

> from transformers.utils.quantization_config import BitsAndBytesConfig
> from transformers import AutoModel
> import torch
> bnb_config = BitsAndBytesConfig(bnb_4bit_compute_dtype="bfloat16", bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True, load_in_4bit=True)
> model = AutoModel.from_pretrained('/home/alyssa/lm_fun/text-generation-webui/models/llama-65b', device_map='sequential', low_cpu_mem_usage=True, quantization_config=bnb_config)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:46<00:00,  3.13s/it]
> model.dtype
torch.float16
>

**Comment by RonanKMcGovern** [comment]
Can you share more info - how can you tell it's silently loading in fp16?

**Comment by rationalism** [comment]
@RonanKMcGovern I called model.dtype after loading, and it returned torch.float16 (see the last two lines).

**Comment by RonanKMcGovern** [comment]
I think that refers to the other submodules not subject to quantization. From [here](https://huggingface.co/blog/4bit-transformers-bitsandbytes):

> Keep in mind that loading a quantized model will automatically cast other model's submodules into float16 dtype. You can change this behavior, (if for example you want to have the layer norms in float32), by passing torch_dtype=dtype to the from_pretrained method.

**Comment by rationalism** [comment]
@TimDettmers sorry, do you know why this was closed? If it just auto closes everything after a few months, even if it's still broken, that seems inaccurate? Thanks as always
