### ISSUE TITLE
Error finding CUDA in Windows despite me using it many times before

### ISSUE THREAD

**Issue by MinervaArgus** [TimDettmers/bitsandbytes#690]
False
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Program Files\Python\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\offic\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by jianingyu-ustc** [comment]
similar error in linux:

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/conda/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by yxc0915** [comment]
I have the same problem too.And my CUDA version is 12.1.

**Comment by cateyelow** [comment]
1. Download [bitsandbytes-0.39.1-py3-none-win_amd64.whl](https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl)

2. cd [Download Directory]
    pip install bitsandbytes-0.39.1-py3-none-win_amd64.whl

3. remove this code in C:\Users\UserName\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\__main__.py

```
    if 'CONDA_PREFIX' in os.environ:
        paths = find_file_recursive(os.environ['CONDA_PREFIX'], f'*cuda*{SHARED_LIB_EXTENSION}')
        print_header("ANACONDA CUDA PATHS")
        print(paths)
        print('')
    if 'CUDA_HOME' in os.environ:
        paths = find_file_recursive(os.environ['CONDA_PREFIX'], f'*cuda*{SHARED_LIB_EXTENSION}')
        print_header("CUDA_HOME CUDA PATHS")
        print(paths)
        print('')
    elif 'CUDA_PATH' in os.environ:
        paths = find_file_recursive(os.environ['CONDA_PREFIX'], f'*cuda*{SHARED_LIB_EXTENSION}')
        print_header("CUDA_PATH CUDA PATHS")
        print(paths)
        print('')
```

4. python -m bitsandbytes

```
C:\Users\Master>python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
C:\Users\Master\anaconda3\envs\stylegan3\bin\cudart32_110.dll
C:\Users\Master\anaconda3\envs\stylegan3\bin\cudart64_110.dll
C:\Users\Master\anaconda3\envs\stylegan3\lib\site-packages\torch\lib\c10_cuda.dll
C:\Users\Master\anaconda3\envs\stylegan3\lib\site-packages\torch\lib\torch_cuda.dll
C:\Users\Master\anaconda3\envs\stylegan3\Library\bin\cudart64_110.dll
C:\Users\Master\anaconda3\pkgs\cuda-cudart-dev-11.8.89-0\bin\cudart32_110.dll
C:\Users\Master\anaconda3\pkgs\cuda-cudart-dev-11.8.89-0\bin\cudart64_110.dll
C:\Users\Master\anaconda3\pkgs\cudatoolkit-11.1.1-hb074779_11\Library\bin\cudart64_110.dll
C:\Users\Master\anaconda3\pkgs\cudatoolkit-11.8.0-h09e9e62_11\Library\bin\cudart64_110.dll
C:\Users\Master\anaconda3\pkgs\pytorch-2.0.1-py3.9_cuda11.8_cudnn8_0\Lib\site-packages\torch\lib\c10_cuda.dll
C:\Users\Master\anaconda3\pkgs\pytorch-2.0.1-py3.9_cuda11.8_cudnn8_0\Lib\site-packages\torch\lib\torch_cuda.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda122_nocublaslt.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\c10_cuda.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\cudart64_110.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\torch_cuda.dll
C:\Users\Master\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\cudart64_110.dll
C:\Users\Master\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\c10_cuda.dll
C:\Users\Master\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\cudart64_110.dll
C:\Users\Master\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\torch_cuda.dll
C:\Users\Master\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\torch_cuda_cpp.dll
C:\Users\Master\AppData\Local\Programs\Python\Python37\Lib\site-packages\torch\lib\torch_cuda_cu.dll
C:\Users\Master\AppData\Local\Programs\Python\Python37\Lib\site-packages\torchvision\cudart64_110.dll
C:\Users\Master\Downloads\libbitsandbytes_cuda116.dll

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64 CUDA PATHS
Could not read LD_LIBRARY_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.6']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

**Comment by samon11** [comment]
The block below was also an offender for me. 

```python
    if isdir(os.getcwd()):
        paths = find_file_recursive(os.getcwd(), '*cuda*' + SHARED_LIB_EXTENSION)
        print_header("WORKING DIRECTORY CUDA PATHS")
        print(paths)
        print('')
```

I was receiving the error:

```python
Traceback (most recent call last):
  File "C:\Users\mjsam\miniconda3\envs\pytorch\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mjsam\miniconda3\envs\pytorch\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mjsam\miniconda3\envs\pytorch\lib\site-packages\bitsandbytes\__main__.py", line 109, in <module>
    generate_bug_report_information()
  File "C:\Users\mjsam\miniconda3\envs\pytorch\lib\site-packages\bitsandbytes\__main__.py", line 73, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*' + SHARED_LIB_EXTENSION)
  File "C:\Users\mjsam\miniconda3\envs\pytorch\lib\site-packages\bitsandbytes\__main__.py", line 40, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file.' + err)
RuntimeError: Something when wrong when trying to find file.
```

More likely than not, your CUDA installation is correct. The library however is searching for the wrong paths on Windows environments when printing the system's info which crashes the execution before even getting to the installation. Removing these blocks just allows the install to continue without printing as much information.

**Comment by 13990008036** [comment]
The operating system I am using is Linux, cuda11.7, and I have installed Python 2.0.0+cu117. During Python debugging, I imported the torch and printed (torch. cuda. is_available()) as true. However, I followed your instructions to enter the bitsandbytes folder and did not find this Python 311 Lib site packages main_ Bitsandbytes_ The py file, I think it's caused by the different installation paths for Linux and Windows, but I found a__ Main__ Py file, so I entered it and only found this code

`If 'CONDA_ PREFIX 'in os. environment:

Paths=find_ File_ Recursive (os. environment ['CONDA_PREFIX '], f' * cuda * {SHARED_LIB-EXTENSION} ')

Print_ Header ("ANACONDA CUDA PATHS")

Print (paths)

Print ('')`

I deleted it, but still encountered the same error message

**Comment by 13990008036** [comment]
The operating system I am using is Linux, cuda11.7, and I have installed Python 2.0.0+cu117. During Python debugging, I imported the torch and printed (torch. cuda. is_available()) as true. However, I followed your instructions to enter the bitsandbytes folder and did not find 'Python311\Lib\site-packages\main_bitsandbytes_.py', I think it's caused by the different installation paths for Linux and Windows, but I found '~/anaconda3/envs/pytorch200/lib/python3.10/site-packages/bitsandbytes/__ main__ .py', so I tried to access it and only found this code
`import os
import sys
import shlex
import subprocess

from warnings import warn
from typing import Tuple
from os.path import isdir

import torch

HEADER_WIDTH = 60

def execute_and_return(command_string: str) -> Tuple[str, str]:
    def _decode(subprocess_err_out_tuple):
        return tuple(
            to_decode.decode("UTF-8").strip()
            for to_decode in subprocess_err_out_tuple
        )

    def execute_and_return_decoded_std_streams(command_string):
        return _decode(
            subprocess.Popen(
                shlex.split(command_string),
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            ).communicate()
        )

    std_out, std_err = execute_and_return_decoded_std_streams(command_string)
    return std_out, std_err

def find_file_recursive(folder, filename):
    cmd = f'find {folder} -name {filename}'
    out, err = execute_and_return(cmd)
    if len(err) > 0:
        raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')

    return out


def generate_bug_report_information():
    print_header("")
    print_header("BUG REPORT INFORMATION")
    print_header("")
    print('')

   
    if isdir('/usr/local/'):
        paths = find_file_recursive('/usr/local', '*cuda*so')
        print_header("/usr/local CUDA PATHS")
        print(paths)
        print('')

    if isdir(os.getcwd()):
        paths = find_file_recursive(os.getcwd(), '*cuda*so')
        print_header("WORKING DIRECTORY CUDA PATHS")
        print(paths)
        print('')

    print_header("LD_LIBRARY CUDA PATHS")
    if 'LD_LIBRARY_PATH' in os.environ:
        lib_path = os.environ['LD_LIBRARY_PATH'].strip()
        for path in set(lib_path.split(':')):
            try:
                if isdir(path):
                    print_header(f"{path} CUDA PATHS")
                    paths = find_file_recursive(path, '*cuda*so')
                    print(paths)
            except:
                print(f'Could not read LD_LIBRARY_PATH: {path}')
    print('')





def print_header(
    txt: str, width: int = HEADER_WIDTH, filler: str = "+"
) -> None:
    txt = f" {txt} " if txt else ""
    print(txt.center(width, filler))


def print_debug_info() -> None:
    print(
        "\nAbove we output some debug information. Please provide this info when "
        f"creating an issue via {PACKAGE_GITHUB_URL}/issues/new/choose ...\n"
    )


generate_bug_report_information()


from . import COMPILED_WITH_CUDA, PACKAGE_GITHUB_URL
from .cuda_setup.env_vars import to_be_ignored
from .cuda_setup.main import get_compute_capabilities


print_header("OTHER")
print(f"COMPILED_WITH_CUDA = {COMPILED_WITH_CUDA}")
print(f"COMPUTE_CAPABILITIES_PER_GPU = {get_compute_capabilities()}")
print_header("")
print_header("DEBUG INFO END")
print_header("")
print(
    """
Running a quick check that:
    + library is importable
    + CUDA function is callable
"""
)
print("\nWARNING: Please be sure to sanitize sensible info from any such env vars!\n")

try:
    from bitsandbytes.optim import Adam

    p = torch.nn.Parameter(torch.rand(10, 10).cuda())
    a = torch.rand(10, 10).cuda()

    p1 = p.data.sum().item()

    adam = Adam([p])

    out = a * p
    loss = out.sum()
    loss.backward()
    adam.step()

    p2 = p.data.sum().item()

    assert p1 != p2
    print("SUCCESS!")
    print("Installation was successful!")
    sys.exit(0)

except ImportError:
    print()
    warn(
        f"WARNING: {__package__} is currently running as CPU-only!\n"
        "Therefore, 8-bit optimizers and GPU quantization are unavailable.\n\n"
        f"If you think that this is so erroneously,\nplease report an issue!"
    )
    print_debug_info()
    sys.exit(0)
except Exception as e:
    print(e)
    print_debug_info()
    sys.exit(1)

`
I have deleted similar parts from the code snippet you posted ,But there are still the same errors that I reported before performing the delete operation
`RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
`

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
