### ISSUE TITLE
set config ﻿﻿bnb_4bit_quant_type="nf4" load_in_4bit=True, but torch state_dict dtype is torch.uint8?

### ISSUE THREAD

**Issue by aohan237** [TimDettmers/bitsandbytes#691]
very confusing.

it should be a normal float 4 dtype, but pytorch has no support for nf4.

how does this work? is there any instructions?

**Comment by yunhao-tech** [comment]
I also got confused. [A snippet on Colab](https://colab.research.google.com/drive/1xye-EBq2Gkkxu1poVzQ4I2EZt_7HaFUf?usp=sharing) for this. 
Anyone have some ideas?
