### ISSUE TITLE
NF4 bnb toks are slow vs GPTQ

### ISSUE THREAD

**Issue by RonanKMcGovern** [TimDettmers/bitsandbytes#696]
I'm finding that NF4 in bnb is giving much lower token generation speed than GPTQ - for similar GPU VRAM requirements and the same model (Llama-2-7B).

---

Llama-7B nf4 bitsandbytes quantisation:
PPL: 8.8, GPU Mem: 4.7 GB, 12.2 toks.

Llama-7B-GPTQ-4bit-128:
PPL: 9.3, GPU Mem: 4.8 GB, 21.4 toks.

---

Is there a better way to load the NF4 model?

Here is NF4 in bnb config:
```
    runtimeFlag = "cuda:0"

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True, #adds speed with minimal loss of quality.
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map='auto', # for inference use 'auto', for training use device_map={"":0}
        trust_remote_code=True,
        # rope_scaling = {"type": "dynamic", "factor": 2.0}, # allows for a max sequence length of 8192 tokens !!! [not tested in this notebook yet]
        cache_dir=cache_dir)
```

and here is GPTQ:
```
os.environ["SAFETENSORS_FAST_GPU"] = "1"

use_triton = False

extrapolation_factor = 1.0 # allows for a max sequence length of 8192 tokens (~6k words) with a factor of 2.0! Unfortunately, requires Colab Pro and a V100 or A100 to have sufficient RAM.

model = AutoGPTQForCausalLM.from_quantized(model_name_or_path,
        model_basename=model_basename,
        use_safetensors=True,
        trust_remote_code=True,
        device="cuda:0",
        use_triton=use_triton,
        quantize_config=None,
        rope_scaling = {"type": "dynamic", "factor": extrapolation_factor}, # allows for a max sequence length of 8192 tokens with a factor of 2.0!!!
        cache_dir=cache_dir)
```

**Comment by AntoineBlanot** [comment]
Do you have more details about the dataset you used ?
I would like to test it on my own environment and compare

**Comment by RonanKMcGovern** [comment]
Hi @AntoineBlanot , I just did a very simple/naive speed check:
```
import time

# Initialize the prompt
prompt = "Once upon a time"

# Record the start time
start_time = time.time()

# Encode the prompt
input_ids = tokenizer.encode(prompt, return_tensors='pt').to(device)

# Set the maximum length for generation
max_length = 100

# Generate the sequence
output = model.generate(input_ids, max_length=max_length)

# Record the end time
end_time = time.time()

# Calculate the tokens per second
elapsed_time = end_time - start_time
tokens_per_sec = max_length / elapsed_time

print(f"Tokens per second: {tokens_per_sec}")
```

and I run that a few times to check consistency of toks. 'device' here is 'cuda:0'

**Comment by RonanKMcGovern** [comment]
And there is some good data here - albeit for 8-bit: https://github.com/PanQiWei/AutoGPTQ/issues/49#issuecomment-1538065985

**Comment by AegeanYan** [comment]
I've noticed that recently too. I found that after using bnb nf4, the llama-30B's inference speed on 1 PGU is even slower than the meta's original repo on 4 GPU. It's unreasonable right?

**Comment by AegeanYan** [comment]
By the way, my device is 3090 Amperor. I've seen someone says that Ada(4090.) would do better on GPTQ, do you have any relative thoughts?

**Comment by RonanKMcGovern** [comment]
Probably GPTQ will always be faster than bitsandbytes and ggml because GPTQ uses a custom quantised kernel for matrix-vector operations. Basically everything is quantised, and the weights that are full precision are fetched on an as-needed basis. This gives a very significant speed up.

This is my understanding from the [paper](https://arxiv.org/abs/2210.17323). @TimDettmers would know more and can correct me. I'm pretty sure bnb and also ggml could implement this.

Separately, in theory, GPTQ should perform better on perplexity for larger model sizes. GGML and BNB NF4 are "round to the nearest" quantization approaches that leave some weights in full precision. The GPTQ paper shows degradation in this approach at larger model sizes.
