### ISSUE TITLE
===================================BUG REPORT================================

### ISSUE THREAD

**Issue by Rnglg2** [TimDettmers/bitsandbytes#707]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/autodl-tmp/tr/sd-scripts/sdxl_train.py:746 in <module>                                     │
│                                                                                                  │
│   743 │   args = parser.parse_args()                                                             │
│   744 │   args = train_util.read_config_from_file(args, parser)                                  │
│   745 │                                                                                          │
│ ❱ 746 │   train(args)                                                                            │
│   747                                                                                            │
│                                                                                                  │
│ /root/autodl-tmp/tr/sd-scripts/sdxl_train.py:335 in train                                        │
│                                                                                                  │
│   332 │                                                                                          │
│   333 │   # 学習に必要なクラスを準備する                                                         │
│   334 │   accelerator.print("prepare optimizer, data loader etc.")                               │
│ ❱ 335 │   _, _, optimizer = train_util.get_optimizer(args, trainable_params=params_to_optimize   │
│   336 │                                                                                          │
│   337 │   # dataloaderを準備する                                                                 │
│   338 │   # DataLoaderのプロセス数：0はメインプロセスになる                                      │
│                                                                                                  │
│ /root/autodl-tmp/tr/sd-scripts/library/train_util.py:3348 in get_optimizer                       │
│                                                                                                  │
│   3345 │                                                                                         │
│   3346 │   elif optimizer_type.endswith("8bit".lower()):                                         │
│   3347 │   │   try:                                                                              │
│ ❱ 3348 │   │   │   import bitsandbytes as bnb                                                    │
│   3349 │   │   except ImportError:                                                               │
│   3350 │   │   │   raise ImportError("No bitsandbytes / bitsandbytesがインストールされていない   │
│   3351                                                                                           │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/__init__.py:7 in <module>             │
│                                                                                                  │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│    6 from . import cuda_setup, utils                                                             │
│ ❱  7 from .autograd._functions import (                                                          │
│    8 │   MatmulLtState,                                                                          │
│    9 │   bmm_cublas,                                                                             │
│   10 │   matmul,                                                                                 │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/__init__.py:1 in <module>    │
│                                                                                                  │
│ ❱ 1 from ._functions import undo_layout, get_inverse_transform_indices                           │
│   2                                                                                              │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:9 in <module>  │
│                                                                                                  │
│     6                                                                                            │
│     7 import torch                                                                               │
│     8                                                                                            │
│ ❱   9 import bitsandbytes.functional as F                                                        │
│    10                                                                                            │
│    11                                                                                            │
│    12 # math.prod not compatible with python < 3.8                                               │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/functional.py:17 in <module>          │
│                                                                                                  │
│     14 from typing import Tuple                                                                  │
│     15 from torch import Tensor                                                                  │
│     16                                                                                           │
│ ❱   17 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     18                                                                                           │
│     19                                                                                           │
│     20 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cextension.py:13 in <module>          │
│                                                                                                  │
│   10                                                                                             │
│   11 setup = CUDASetup.get_instance()                                                            │
│   12 if setup.initialized != True:                                                               │
│ ❱ 13 │   setup.run_cuda_setup()                                                                  │
│   14                                                                                             │
│   15 lib = setup.lib                                                                             │
│   16 try:                                                                                        │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:101 in             │
│ run_cuda_setup                                                                                   │
│                                                                                                  │
│    98 │   │   self.initialized = True                                                            │
│    99 │   │   self.cuda_setup_log = []                                                           │
│   100 │   │                                                                                      │
│ ❱ 101 │   │   binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()    │
│   102 │   │   self.cudart_path = cudart_path                                                     │
│   103 │   │   self.cuda = cuda                                                                   │
│   104 │   │   self.cc = cc                                                                       │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:382 in             │
│ evaluate_cuda_setup                                                                              │
│                                                                                                  │
│   379 │   if not torch.cuda.is_available(): return 'libbitsandbytes_cpu.so', None, None, None,   │
│   380 │                                                                                          │
│   381 │   cuda_setup = CUDASetup.get_instance()                                                  │
│ ❱ 382 │   cudart_path = determine_cuda_runtime_lib_path()                                        │
│   383 │   cuda = get_cuda_lib_handle()                                                           │
│   384 │   cc = get_compute_capability(cuda)                                                      │
│   385 │   cuda_version_string = get_cuda_version(cuda, cudart_path)                              │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:258 in             │
│ determine_cuda_runtime_lib_path                                                                  │
│                                                                                                  │
│   255 │   │   warn_in_case_of_duplicates(lib_ld_cuda_libs)                                       │
│   256 │   │                                                                                      │
│   257 │   │   CUDASetup.get_instance().add_log_entry(f'{candidate_env_vars["LD_LIBRARY_PATH"]}   │
│ ❱ 258 │   │   │   f'{CUDA_RUNTIME_LIB} as expected! Searching further paths...', is_warning=Tr   │
│   259 │                                                                                          │
│   260 │   remaining_candidate_env_vars = {                                                       │
│   261 │   │   env_var: value for env_var, value in candidate_env_vars.items()                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'CUDA_RUNTIME_LIB' is not defined
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/miniconda3/bin/accelerate:8 in <module>                                                    │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py:45 in main   │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py:923 in               │
│ launch_command                                                                                   │
│                                                                                                  │
│   920 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   921 │   │   sagemaker_launcher(defaults, args)                                                 │
│   922 │   else:                                                                                  │
│ ❱ 923 │   │   simple_launcher(args)                                                              │
│   924                                                                                            │
│   925                                                                                            │
│   926 def main():                                                                                │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.py:579 in               │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   576 │   process.wait()                                                                         │
│   577 │   if process.returncode != 0:                                                            │
│   578 │   │   if not args.quiet:                                                                 │
│ ❱ 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   580 │   │   else:                                                                              │
│   581 │   │   │   sys.exit(1)                                                                    │
│   582                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/root/miniconda3/bin/python', '/root/autodl-tmp/tr/sd-scripts/sdxl_train.py',
'--pretrained_model_name_or_path=/root/autodl-tmp/tr/model/sd_xl_base_1.0_0.9vae.safetensors',
'--train_data_dir=/root/autodl-tmp/tr/color', '--output_dir=./output', '--logging_dir=./logs',
'--resolution=1024,1024', '--max_train_epochs=36', '--learning_rate=5e-6', '--lr_scheduler=constant_with_warmup',
'--lr_warmup_steps=10', '--lr_scheduler_num_cycles=1', '--output_name=color_trace_db', '--train_batch_size=8',
'--save_every_n_epochs=6', '--save_precision=bf16', '--seed=1026', '--max_token_length=225',
'--caption_extension=.txt', '--save_model_as=safetensors', '--keep_tokens=3', '--xformers', '--full_bf16',
'--bucket_reso_steps=32', '--save_state', '--shuffle_caption', '--persistent_data_loader_workers',
'--caption_dropout_rate=0.1', '--vae=/root/autodl-tmp/tr/model/SDXLsdxl_vae.safetensors', '--cache_latents',
'--cache_latents_to_disk', '--mixed_precision=bf16', '--optimizer_type=AdamW8bit', '--optimizer_args',
'weight_decay=0.01', 'is_paged=True', '--noise_offset=0.0375', '--adaptive_noise_scale=0.0375', '--vae_batch_size=4',
'--min_snr_gamma=5', '--gradient_checkpointing', '--clip_skip=2']' returned non-zero exit status 1.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
