### ISSUE TITLE
Disable CUDA setup warning messages

### ISSUE THREAD

**Issue by AntoineBlanot** [TimDettmers/bitsandbytes#708]
Hello, 
I would like to disable the warning message and prints created by the CUDA setup. For example this:
`
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/chikara/.cache/pypoetry/virtualenvs/haru-nlp-core-nbPEcLsa-py3.8/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /home/chikara/.cache/pypoetry/virtualenvs/haru-nlp-core-nbPEcLsa-py3.8/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
`
Is there a simple way to remove all those prints?

**Comment by suzyahyah** [comment]
I don't think there's a way to do so easily because I found many hardcoded print statements (not using the logging package). I ended up going into the source code and manually commenting out the print statements.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
