### ISSUE TITLE
CUDASetup got issues...

### ISSUE THREAD

**Issue by conght** [TimDettmers/bitsandbytes#709]
bin /home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
False
/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/kml/lib/kblas/omp'), PosixPath('/usr/local/kml/lib/kspblas/single'), PosixPath('/usr/local/kml/lib/kblas/nolocking'), PosixPath('/usr/local/kml/lib/kspblas/multi'), PosixPath('/usr/local/kml/lib/kblas/pthread'), PosixPath('/usr/local/kml/lib/kvml/multi'), PosixPath('/usr/local/kml/lib/kblas/locking'), PosixPath('/usr/local/kml/lib/kvml/single'), PosixPath('/usr/local/kml/lib')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /home/HPCBase/compilers/cuda/11.6.0/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/share/zhejdxue/home/jifazhang/.conda/envs/ChatGLM2/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by pk1762012** [comment]
Facing the same issue in windows, no such issue in linux

**Comment by alongLFB** [comment]
> Facing the same issue in windows, no such issue in linux

I face this issue in centos.

![image](https://github.com/TimDettmers/bitsandbytes/assets/17883682/522fb908-cd88-4b71-a7d2-ea0c21db3d3e)

**Comment by Obamium69** [comment]
Getting the same issue

**Comment by suntea233** [comment]
i met the same problem, i found that there is an another package called bitsandbytes-windows.
But after i using this packag, there came another error
```
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
```

**Comment by t170815518** [comment]
A related issue https://github.com/TimDettmers/bitsandbytes/issues/723#issuecomment-1694731419 to solve the bug on Linux

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
