### ISSUE TITLE
How to hide welcome message?

### ISSUE THREAD

**Issue by Cyberes** [TimDettmers/bitsandbytes#71]
How do I hide the welcome message?

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
```

Maybe implement something like this in `evaluate_cuda_setup()`?

```python
if 'BITSANDBYTES_NOWELCOME' not in os.environ:
    print('')
    print('='*35 + 'BUG REPORT' + '='*35)
    print('Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues')
    print('For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link')
    print('='*80)
```

I can open a pull request if you guys are open to this.

**Comment by TimDettmers** [comment]
I like this idea! Currently, the message is hidden, but I think bringing the message back would help with error reporting. For people that want to hide the message can just set the environmental variables.

Could you create a PR with this? The best solution would also add a lien to the welcome message that has instructions on how to hide the message for example:
`print('To hide this message, set the BITSANDBYTES_NOWELCOME variable like so: export BITSANDBYTES_NOWELCOME=1`)
