### ISSUE TITLE
function 'cadam32bit_grad_fp32' not found

### ISSUE THREAD

**Issue by AtheerAlgherairy** [TimDettmers/bitsandbytes#711]
================================================================================
bin C:\Users\g201906730\anaconda3\envs\LLM_Finetuning_env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
function 'cadam32bit_grad_fp32' not found
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
ERROR: libcudart.so could not be read from path: None!
CUDA SETUP: Highest compute capability among GPUs detected: 6.0
CUDA SETUP: Detected CUDA version None
CUDA SETUP: Loading binary C:\Users\g201906730\anaconda3\envs\LLM_Finetuning_env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
