### ISSUE TITLE
UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.

### ISSUE THREAD

**Issue by w656924773** [TimDettmers/bitsandbytes#719]
bin E:\Anaconda\envs\llama_etuning\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
E:\Anaconda\envs\llama_etuning\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
CUDA SETUP: Loading binary E:\Anaconda\envs\llama_etuning\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121_nocublaslt.dll

+++++++++++++++++++ CUDA_PATH CUDA PATHS +++++++++++++++++++
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda111_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda112_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda113_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda114_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda115_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda116_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda120_nocublaslt.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
E:\Anaconda\envs\llama_etuning\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121_nocublaslt.dll

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
C:\Users\Administrator\AppData\Local\Temp\wincompress\{F46CB1DB-74DF-4746-8B9A-C81E55BB1024}\ChatGLM-Efficient-Tuning\python\Lib\site-packages\torch\lib\c10_cuda.dll
C:\Users\Administrator\AppData\Local\Temp\wincompress\{F46CB1DB-74DF-4746-8B9A-C81E55BB1024}\ChatGLM-Efficient-Tuning\python\Lib\site-packages\torch\lib\cudart64_110.dll
C:\Users\Administrator\AppData\Local\Temp\wincompress\{F46CB1DB-74DF-4746-8B9A-C81E55BB1024}\ChatGLM-Efficient-Tuning\python\Lib\site-packages\torch\lib\torch_cuda.dll
C:\Users\Administrator\AppData\Local\Temp\wincompress\{F46CB1DB-74DF-4746-8B9A-C81E55BB1024}\ChatGLM-Efficient-Tuning\python\Lib\site-packages\torchvision\cudart64_110.dll

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = ['8.6']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

Torch not compiled with CUDA enabled

Above we output some debug information. Please provide this info when creating an issue via https://github.com/jllllll/bitsandbytes/issues/new/choose ...

**Comment by w656924773** [comment]
Cuda installed

**Comment by AtheerAlgherairy** [comment]
I have same issue

**Comment by czw-czw-czw** [comment]
解决了吗

**Comment by zj-nb** [comment]
I have the same problem，have you solved the problem？
