### ISSUE TITLE
bitsandbytes on Windows

### ISSUE THREAD

**Issue by AtheerAlgherairy** [TimDettmers/bitsandbytes#721]
**How can I solve this issue?**

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\g201906730\anaconda3\envs\LLM_Finetuning_env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
function 'cadam32bit_grad_fp32' not found
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
ERROR: libcudart.so could not be read from path: None!
CUDA SETUP: Highest compute capability among GPUs detected: 6.0
CUDA SETUP: Detected CUDA version None
CUDA SETUP: Loading binary C:\Users\g201906730\anaconda3\envs\LLM_Finetuning_env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...

C:\Users\g201906730\anaconda3\envs\LLM_Finetuning_env\lib\site-packages\bitsandbytes\cextension.py:34: **UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.**

**Comment by AtheerAlgherairy** [comment]
Version of cuda 11.7
Torch version: 2.0.1+cu117
Is CUDA enabled? True

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
