### ISSUE TITLE
Error out of memory  in WSL(Ubuntu 22.04 )

### ISSUE THREAD

**Issue by leilichuan** [TimDettmers/bitsandbytes#726]
Hello, when I  use  QLora to finetune llama-7-b on wsl (ubuntu 22.04), I encountered the following error.

**Error out of memory at line 380 in file /home/leilichuan/bitsandbytes/csrc/pythonInterface.c**

environment：
win11 WSL(Ubuntu 22.04 )
GPU  NVIDIA GeForce RTX 4090  24GB
CUDA 11.7
model: Llama2-7b
bitsandbytes   0.41.1

---
`$ python train_qlora.py --model_name_or_path   /mnt/e/code/konwledge_base_QA/LLMs/Llama2-Chinese-7b-Chat
[2023-08-23 11:12:29,462] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
loading base model /mnt/e/code/konwledge_base_QA/LLMs/Llama2-Chinese-7b-Chat...
/home/leilichuan/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/modeling_utils.py:2193: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:19<00:00,  9.74s/it]
/home/leilichuan/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1714: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Adding special tokens.
adding LoRA modules...
loaded model
trainable params: 79953920.0 || all params: 3660328960 || trainable: 2.1843370056007205%
torch.float32 422326272 0.11537932153507864
torch.uint8 3238002688 0.8846206784649213
wandb: Currently logged in as: q393754502 (cupnickray). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.8 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /mnt/e/DB-GPT-Hub/wandb/run-20230823_111313-zwla7071
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run crimson-feather-11
wandb: ⭐️ View project at https://wandb.ai/cupnickray/huggingface
wandb: 🚀 View run at https://wandb.ai/cupnickray/huggingface/runs/zwla7071
  0%|                                                                                         | 0/10000 [00:00<?, ?it/s]
Error out of memory at line 380 in file /home/leilichuan/bitsandbytes/csrc/pythonInterface.c`
---
`$ python -m bitsandbytes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/leilichuan/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/bitsandbytes-0.41.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda117.so
/home/leilichuan/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/leilichuan/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/leilichuan/miniconda3/envs/dbgpt_hub/lib/python3.10/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.7/nsight-compute-2022.2.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.7/nsight-compute-2022.2.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.7/nsight-compute-2022.2.0/target/linux-desktop-t210-a64/libcuda-injection.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
++++++++ /usr/local/TensorRT-8.6.1.6/lib CUDA PATHS ++++++++

++++++++++ /usr/local/cuda-11.7/lib64 CUDA PATHS +++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.9']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!`

**Comment by LZHgrla** [comment]
Same situation👀

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
