### ISSUE TITLE
Is it possible to do a full fine-tune of a bnb quantized model? (No LoRA)

### ISSUE THREAD

**Issue by RonanKMcGovern** [TimDettmers/bitsandbytes#737]
This [notebook](https://colab.research.google.com/drive/1VoYNfYDKcKRQRor98Zbf2-9VQTtGJ24k?usp=sharing) nicely describes fine-tuning with quantization and LoRa.

Is it possible to remove LoRa and fine-tune all parameters of the quantized model?

- If so, what would have to be changed?
- Is there any reason (other than compute time) why this would be a bad idea?

**Comment by RonanKMcGovern** [comment]
@TimDettmers is this possible? Thanks

**Comment by omaratef3221** [comment]
@RonanKMcGovern Hello, were you able to do full fine tuning without LoRa and with Quantization ?

**Comment by TimDettmers** [comment]
Currently, only mixed 8-bit/16-bit training is supported, but this will consume more memory than regular training.
