### ISSUE TITLE
Is there any way to save models trained with 4 bit quantization?

### ISSUE THREAD

**Issue by nathan-az** [TimDettmers/bitsandbytes#738]
Creating a separate issue for workarounds to https://github.com/huggingface/transformers/issues/23904

I understand that models loaded in 4 bit cannot be directly saved. It also appears not straightforward to convert them back to a higher precision data type (I get an exception if I try `model.to(torch.bfloat16)` for example). 

Is there a clear way around this (i.e. some less obvious way to temporarily convert to a save-able datatype) so that models trained in 4 bit can be saved in higher precision?

The inability to save currently disallows checkpointing for features such as early stopping or `load_best_model_at_end` in the transformers Trainer.

**Comment by RonanKMcGovern** [comment]
Yeah, it's the same issue as [here](https://github.com/TimDettmers/bitsandbytes/issues/695). The model needs to be serialised.

Note that you can push 8-bit models to hub, that's the closest thing I can think of.

**Comment by RonanKMcGovern** [comment]
closing due to: https://github.com/TimDettmers/bitsandbytes/pull/753

**Comment by nathan-az** [comment]
Closing!
