### ISSUE TITLE
RuntimeError: CUDA Setup failed despite GPU being available.  BUG REPORT INFO OFFERED

### ISSUE THREAD

**Issue by tomFoxxxx** [TimDettmers/bitsandbytes#743]
`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
CUDA SETUP: CUDA runtime path found: /home/ma-user/anaconda3/envs/eurekabot/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 117
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/ma-user/anaconda3/envs/eurekabot/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/ma-user/anaconda3/envs/eurekabot/lib/libicudata.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/nvidia/lib64/libcuda.so
/usr/local/cuda-10.2/compat/libcuda.so
/usr/local/cuda-10.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudart.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++

++++++++++++ /usr/local/nvidia/lib64 CUDA PATHS ++++++++++++
/usr/local/nvidia/lib64/libcuda.so
++++++++++ /usr/lib/x86_64-linux-gnu/ CUDA PATHS +++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['7.0', '7.0', '7.0', '7.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!`

Thanks a lot ！

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
