### ISSUE TITLE
What is LoRA alpha?

### ISSUE THREAD

**Issue by RonanKMcGovern** [TimDettmers/bitsandbytes#762]
I don't see it mentioned in the LoRA paper and I don't see a clear description in transformers documentation?

Could someone point me to an explanation? thanks

**Comment by BenjaminBossan** [comment]
Section 4.1 in https://arxiv.org/abs/2106.09685

**Comment by LukeLIN-web** [comment]
> Many thanks [@BenjaminBossan](https://github.com/BenjaminBossan) that's great.
> 
> I guess the common (?) practise of setting alpha higher than r is basically implying that people are using quite a high learning rate (often 2e-4 is not uncommon on 7B Llama, so with r=8 and alpha=32, that's basically 8e-4 as a learning rate for LoRA training).

so when alpha = 4 r, it have similar effect , lr = 4 previous lr?
