### ISSUE TITLE
Matrix shape is corrupted after it's moved to CUDA.

### ISSUE THREAD

**Issue by Andrei-Aksionov** [TimDettmers/bitsandbytes#765]
> [!NOTE]
> I used bitsandbytes version 0.41.1

Hi there 👋 

I've noticed a weird behavior: if I create `bitsandbytes.modules.Linear4iit` with a weight matrix of shape, let's say **(24, 8)**, after I move the layer to a CUDA device and the weight matrix is quantized, its shape is corrupted to **(96, 1)**. 
Here is a Google Colab [notebook](https://colab.research.google.com/drive/1BsqUowCDB4N3snn6EeZG2ykvBf-Oazu1?usp=sharing) with the code example.

With a debugger I've noticed that after the weight matrix is dequantized the shape is restored to the original shape of **(24, 8)** and it happens here:
https://github.com/TimDettmers/bitsandbytes/blob/18e827d666fa2b70a12d539ccedc17aa51b2c97c/bitsandbytes/functional.py#L924

... which is weird, as don't know how you can get **(24, 8)** out of **(96, 1)**.
I think that's probably because in this line an empty tensor of the correct shape is created, that, apparently, later is filled with dequantized values:
https://github.com/TimDettmers/bitsandbytes/blob/18e827d666fa2b70a12d539ccedc17aa51b2c97c/bitsandbytes/functional.py#L908

Given that in this line the code checks that the first dimension of the shape might be **1** (the weight matrix is provided in a transposed form, so the shape is **(1, 96)**), maybe it's an expected behavior?:
https://github.com/TimDettmers/bitsandbytes/blob/18e827d666fa2b70a12d539ccedc17aa51b2c97c/bitsandbytes/functional.py#L934

If it is, then I'm totally confused 🤷.

------

### 1. Initialized tensor with shape **(24, 8)**

```python
Parameter(Params4bit([[ 8.6412e-03,  1.7115e-02, -1.5228e-02,  3.8203e-03,  1.3792e-02,
             -6.5176e-03, -3.4057e-02,  1.6407e-04],
            [ 4.6371e-04,  2.8627e-03,  7.2119e-03,  9.7935e-04,  6.4806e-03,
             -5.9384e-03,  2.8836e-02,  1.9967e-02],
            [-1.7876e-03, -1.1508e-02,  8.3073e-03, -4.6605e-03, -4.8682e-02,
              8.7687e-03, -7.6142e-03, -5.9601e-03],
            [-1.1494e-02,  3.1514e-03,  4.0517e-02,  2.5275e-02, -2.2224e-02,
             -6.1665e-03, -4.4321e-03, -3.8702e-02],
            [ 1.8763e-02, -2.4185e-02,  1.9109e-02, -5.4083e-03,  8.4692e-03,
             -2.8322e-02,  2.5491e-02,  2.2943e-02],
            [-2.1158e-03, -1.3222e-02,  2.8834e-02, -1.5119e-02, -4.4848e-02,
             -5.5804e-03, -2.6241e-03, -1.6475e-02],
            [-1.7726e-02, -2.7416e-02, -2.1919e-02, -1.7208e-02, -1.7509e-03,
              7.4488e-03,  3.3106e-02, -2.4068e-03],
            [ 2.2899e-02,  1.0011e-02, -1.7404e-02,  2.9949e-02,  2.3186e-02,
             -1.3737e-02, -1.4832e-02, -1.7456e-03],
            [ 8.4060e-03,  1.5438e-02, -1.2662e-02,  3.7730e-03,  2.7593e-02,
             -1.1197e-02, -2.0058e-03,  1.2036e-02],
            [-1.8819e-02, -1.6679e-04,  2.3931e-02,  3.7116e-03, -7.1925e-03,
              2.2928e-03,  7.9708e-03,  2.6739e-02],
            [-5.5610e-02, -3.1288e-02, -1.8222e-02,  2.5064e-02,  1.1076e-02,
              3.7112e-03, -8.9904e-03,  1.8498e-03],
            [-1.8066e-02,  1.8425e-03, -1.7269e-02, -2.2937e-02, -1.0607e-02,
             -1.7607e-02,  4.0654e-02,  1.0402e-02],
            [-1.1365e-02,  1.3659e-03, -3.1087e-02,  1.5962e-02,  2.6749e-02,
             -1.5058e-02,  1.1149e-02,  6.7742e-03],
            [-1.1953e-02, -2.1522e-02, -6.0751e-02,  2.3389e-02,  6.0851e-04,
             -1.9436e-02, -2.5581e-03, -9.4674e-03],
            [ 1.0490e-02, -2.7215e-02,  9.4475e-05,  3.4044e-03, -1.8287e-02,
             -2.2366e-02, -7.3819e-03,  2.2139e-02],
            [ 3.2720e-03, -1.6269e-02,  4.3183e-02,  2.4819e-02, -1.2707e-02,
             -3.8550e-02,  1.1262e-02,  3.2571e-02],
            [ 2.9163e-02,  1.4815e-02,  1.6936e-02, -4.6705e-03,  4.7889e-02,
             -2.6388e-02,  1.9182e-02,  2.7189e-02],
            [-7.0925e-03, -2.2854e-02,  1.1282e-02, -2.9967e-03,  6.9342e-03,
              1.1080e-02, -7.2178e-03,  1.6053e-03],
            [-1.5947e-02,  1.4481e-02, -9.0941e-03, -1.3270e-02,  2.1591e-03,
             -2.0800e-02, -2.7040e-02, -2.3984e-02],
            [-1.8092e-02,  6.2863e-03, -9.6596e-03, -2.8487e-02, -2.3229e-02,
              9.4091e-03,  1.5595e-02,  8.5087e-04],
            [-2.2467e-02, -6.9501e-04, -1.5225e-02, -1.7964e-02, -1.3129e-03,
              2.0371e-02,  2.2877e-02, -2.0133e-02],
            [ 2.2545e-02, -1.4812e-02, -2.7484e-02,  1.2947e-02, -2.9603e-02,
             -1.3069e-02,  3.2788e-02, -1.8620e-02],
            [-1.8710e-03,  1.5844e-03,  1.3107e-02,  1.8735e-02, -1.4179e-02,
             -3.1499e-02, -2.3512e-02, -1.1461e-02],
            [ 2.6163e-02, -5.9127e-03,  8.2212e-03,  1.6749e-02, -5.4961e-03,
             -1.8294e-03,  3.6558e-02, -2.5730e-02]]))
```

### 2. Quantized tensor with shape (96, 1)

```python
Parameter(Params4bit([[155],
            [ 72],
            [166],
            [ 23],
            [120],
            [151],
            [150],
            [220],
            [116],
            [150],
            [  9],
            [ 86],
            [ 72],
            [237],
            [ 54],
            [ 97],
            [178],
            [198],
            [146],
            [220],
            [116],
            [212],
            [  6],
            [100],
            [ 50],
            [ 51],
            [121],
            [230],
            [202],
            [ 61],
            [196],
            [ 71],
            [154],
            [ 88],
            [197],
            [121],
            [ 71],
            [200],
            [103],
            [156],
            [  2],
            [ 76],
            [152],
            [ 87],
            [ 71],
            [ 67],
            [ 84],
            [233],
            [ 87],
            [ 42],
            [196],
            [152],
            [ 83],
            [ 11],
            [116],
            [117],
            [147],
            [120],
            [ 67],
            [107],
            [132],
            [236],
            [ 81],
            [157],
            [219],
            [182],
            [242],
            [205],
            [ 82],
            [166],
            [154],
            [ 87],
            [ 75],
            [ 84],
            [131],
            [ 34],
            [ 57],
            [ 82],
            [ 41],
            [183],
            [ 39],
            [ 67],
            [124],
            [195],
            [196],
            [ 42],
            [ 20],
            [227],
            [119],
            [172],
            [ 65],
            [ 36],
            [214],
            [155],
            [103],
            [226]], device='cuda:0', dtype=torch.uint8))
```

### 3. Dequantized tensor with shape (24, 8)

```python
tensor([[ 0.0078,  0.0164, -0.0138,  0.0039,  0.0120, -0.0044, -0.0339,  0.0000],
        [ 0.0000,  0.0039,  0.0078,  0.0000,  0.0078, -0.0044,  0.0274,  0.0215],
        [ 0.0000, -0.0138,  0.0078, -0.0044, -0.0487,  0.0078, -0.0090, -0.0044],
        [-0.0138,  0.0039,  0.0352,  0.0274, -0.0192, -0.0044, -0.0044, -0.0339],
        [ 0.0164, -0.0256,  0.0215, -0.0044,  0.0078, -0.0256,  0.0274,  0.0215],
        [ 0.0000, -0.0138,  0.0274, -0.0138, -0.0487, -0.0044, -0.0044, -0.0138],
        [-0.0192, -0.0256, -0.0192, -0.0192,  0.0000,  0.0078,  0.0352, -0.0044],
        [ 0.0215,  0.0120, -0.0192,  0.0274,  0.0215, -0.0138, -0.0138,  0.0000],
        [ 0.0098,  0.0150, -0.0112,  0.0048,  0.0268, -0.0112,  0.0000,  0.0098],
        [-0.0173,  0.0000,  0.0268,  0.0048, -0.0055,  0.0000,  0.0098,  0.0268],
        [-0.0608, -0.0319, -0.0173,  0.0268,  0.0098,  0.0048, -0.0112,  0.0000],
        [-0.0173,  0.0000, -0.0173, -0.0240, -0.0112, -0.0173,  0.0439,  0.0098],
        [-0.0112,  0.0000, -0.0319,  0.0150,  0.0268, -0.0173,  0.0098,  0.0048],
        [-0.0112, -0.0240, -0.0608,  0.0205,  0.0000, -0.0173,  0.0000, -0.0112],
        [ 0.0098, -0.0240,  0.0000,  0.0048, -0.0173, -0.0240, -0.0055,  0.0205],
        [ 0.0048, -0.0173,  0.0439,  0.0268, -0.0112, -0.0423,  0.0098,  0.0342],
        [ 0.0269,  0.0162,  0.0162, -0.0044,  0.0479, -0.0251,  0.0211,  0.0269],
        [-0.0089, -0.0251,  0.0118, -0.0044,  0.0077,  0.0118, -0.0089,  0.0000],
        [-0.0136,  0.0162, -0.0089, -0.0136,  0.0038, -0.0189, -0.0251, -0.0251],
        [-0.0189,  0.0077, -0.0089, -0.0251, -0.0251,  0.0077,  0.0162,  0.0000],
        [-0.0251,  0.0000, -0.0136, -0.0189,  0.0000,  0.0211,  0.0211, -0.0189],
        [ 0.0211, -0.0136, -0.0251,  0.0118, -0.0333, -0.0136,  0.0346, -0.0189],
        [ 0.0000,  0.0000,  0.0118,  0.0211, -0.0136, -0.0333, -0.0251, -0.0136],
        [ 0.0269, -0.0044,  0.0077,  0.0162, -0.0044,  0.0000,  0.0346, -0.0251]],
       device='cuda:0', dtype=torch.float16)
```

Btw, is it normal that there are so many zeros? 23 zeroed values (out of 192) if to be exact.

**Comment by carmocca** [comment]
> ... which is weird, as don't know how you can get (24, 8) out of (96, 1).


I believe this comes from ((24*8)+1)//2: https://github.com/TimDettmers/bitsandbytes/blob/18e827d666fa2b70a12d539ccedc17aa51b2c97c/bitsandbytes/functional.py#L816

So everything seems to be working as expected given the quantization procedure.

**Comment by Andrei-Aksionov** [comment]
This explains how you can get **(96, 1)** out of **(24, 8)**, and I was wondering about the opposite 😄.
The overall question is: why it's even a case, why do we need to do this kind of shape manipulations in the first place?

**Comment by carmocca** [comment]
To do the opposite, the original input shape is saved in the state. Saved here https://github.com/TimDettmers/bitsandbytes/blob/18e827d666fa2b70a12d539ccedc17aa51b2c97c/bitsandbytes/functional.py#L851 and reused in https://github.com/TimDettmers/bitsandbytes/blob/18e827d666fa2b70a12d539ccedc17aa51b2c97c/bitsandbytes/functional.py#L898

But no idea about the advantage of flattening. It's probably either more efficient or simpler to implement

**Comment by Andrei-Aksionov** [comment]
Maybe I don't understand something obvious, but for me not the flattening itself is questionable, but the fact where numbers go/come.

Initial matrix is **(24, 8)** which means that this matrix contains 24*8=192 numbers. After quantization, we have a matrix of shape **(96, 1)** so this matrix contains only 96 numbers. Where did the rest 96 numbers go?
After dequantization we have a matrix with the original shape, which means that we get a matrix of shape **(24, 8)**, that has 192 numbers, out of the matrix of shape **(96, 1)** that has only 96 numbers. How did we get additional 96 numbers. Approximation? David Blaine? 🤷

**Comment by lukaskuhn-lku** [comment]
Did you ever find the answer to the David Blaine magic trick? I am still wondering about the same thing

**Comment by Andrei-Aksionov** [comment]
@lukaskuhn-lku Not yet. Was busy with some other things. But it is still on my list.
A bit later I'll revisit it and put my findings here.
Unless you surpass me 😉.

**Comment by lukaskuhn-lku** [comment]
I will see if I find the time and put any findings here as well

**Comment by lukaskuhn-lku** [comment]
Turns out the shape isn't corrupted, I was just missing something rather obvious. The dtype of the vector is uint8...but wait...weren't we supposed to work with 4-bit values? Well the uint8 represents two 4 bit values at once, concatenated. 

`format(weight[0].item(), '08b')`
returns `01110001` =>  0111 -> 7 & 0001 -> 1 

Hope that clarifies why we are dealing with "half" the amount of values flattened into one array.

**Comment by Andrei-Aksionov** [comment]
I just wanted to come back to this issue and yep, you have surpassed me 👍.
I had a suspicion that the reason is in the 4bit dtype, that is not natively supported, hence the usage of uint8 one.
But had no time to confirm it.

Thanks for clarifying it.
