### ISSUE TITLE
Export 8bit mt0-xxl-mt to ONNX fails

### ISSUE THREAD

**Issue by sh0tcall3r** [TimDettmers/bitsandbytes#768]
Hi, as the title states I'm not able to export quantized `mt0-xxl-mt` model to `ONNX`.
A little intro: I downloaded `mt0-xxl-mt` from hugging face with `8 bit` quantization. As far as I know, quantization is executed with `bitsandbytes` library. Then I fine-tuned the model on the downstream task with `LORA/PEFT` and now trying to export to `ONNX`, but stuck with the error.
I noticed that in the quantized model state dict a curious layer named `'weight_format'` has appeared. There is no such layer in the base (full precision) model state dict. The critical point is that this layer has string value `'row'` instead of weights tensor and torch's export to `ONNX` method tries to apply `detach()` method on it and obviously fails with the error ('str' has no detach method).
I adjusted a torch export to `ONNX` script to not use these `'weight_format'` layers and this error has gone, but another one has appeared - `RuntimeError: _Map_base::at` in one of the `bitsandbytes` scripts. It's seems that there're some problems with multiplication of some matrices, but I have no idea neither which matrices exactly nor how to resolve this issue.
Could you probably help me?

**Comment by tanyav2** [comment]
I have a similar issue with handling `weight_format`. Bumping this.

**Comment by zanilia1016** [comment]
Have you solved this problem?
