### ISSUE TITLE
Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by adalast** [TimDettmers/bitsandbytes#772]
binary_path: C:\Users\User\MLOPs\data\dependencies\python\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\User\MLOPs\data\dependencies\python\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
C:\Users\User\MLOPs\data\dependencies\python\numpy\core\getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
C:\Users\User\MLOPs\data\dependencies\python\numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
C:\Users\User\MLOPs\data\dependencies\python\numpy\core\getlimits.py:518: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
C:\Users\User\MLOPs\data\dependencies\python\numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'

**Comment by BeimengYuan** [comment]
I have the same issue! so how to deal with that??
