### ISSUE TITLE
About the output tensor of quantize_4bit()

### ISSUE THREAD

**Issue by XpracticeYSKM** [TimDettmers/bitsandbytes#777]
When I use functional.quantize_4bit() to quantize weight，I find the output tensor called weight_4bit will be wrapped with unit8(w_4bit.dtype is uint8). And it has 256 unique values from 0 to 255.

I want to figure out why it need be wrapped with uint8 and why it have 256 unique values?  How to achieve the 4bit memory overhead saving effect better than 8 bit in this way?

**Comment by junzhang-zj** [comment]
I think this is because he compresses every two parameters by 4bit and stores them in uint8 for quantization purposes, and you can check this idea out by looking at the dimensions of weight.
