### ISSUE TITLE
Please help with the error in bitsandbytes.

### ISSUE THREAD

**Issue by Flun** [TimDettmers/bitsandbytes#79]
My system: 5600x / 32gb / RTX3090 24gb
OS : win11/wsl2 ubuntu
anaconda 2022.05/cuda 11.7 pytorch 1.12.0 cu116
use dreambooth = https://github.com/ShivamShrirao/diffusers.git

test = bitsandbytes 0.35.1 / 0.35.2 / Just before 0.35.3

error code :
(diffusers) kona@DESKTOP-0T0D468:~/github/diffusers/examples/dreambooth$ ./my_training.sh
Traceback (most recent call last):
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py", line 125, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/kona/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py", line 90, in determine_cuda_runtime_lib_path
    CUDASetup.get_instance.add_log_entry(f'{candidate_env_vars["CONDA_PREFIX"]} did not contain '
AttributeError: 'function' object has no attribute 'add_log_entry'

I've tested several versions of recently built bitsandbytes, but dreambooth keeps spit out the same error.
In the end, dreambooth's calling function --use_8bit_adam has been removed and dreambooth is being used.

If you have a workaround solution, please help me.
Thank you for always.

**Comment by 0xspeedrunner** [comment]
Similar setup as the above: NVIDIA GeForce RTX 3090, running on Linux in Docker container.

Using same repo setup as above.

Tested on `0.35.2` and `0.35.3`

If helpful, can open a new ticket.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import bitsandbytes as bnb

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/__init__.py:6, in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from .autograd._functions import (
      7     MatmulLtState,
      8     bmm_cublas,
      9     matmul,
     10     matmul_cublas,
     11     mm_cublas,
     12 )
     13 from .cextension import COMPILED_WITH_CUDA
     14 from .nn import modules

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py:5, in <module>
      2 import warnings
      4 import torch
----> 5 import bitsandbytes.functional as F
      7 from dataclasses import dataclass
      8 from functools import reduce  # Required in Python 3

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/functional.py:13, in <module>
     10 from typing import Tuple
     11 from torch import Tensor
---> 13 from .cextension import COMPILED_WITH_CUDA, lib
     14 from functools import reduce  # Required in Python 3
     16 # math.prod not compatible with python < 3.8

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:113, in <module>
    109             cls._instance.initialize()
    110         return cls._instance
--> 113 lib = CUDASetup.get_instance().lib
    114 try:
    115     if lib is None and torch.cuda.is_available():

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:109, in CUDASetup.get_instance(cls)
    107 if cls._instance is None:
    108     cls._instance = cls.__new__(cls)
--> 109     cls._instance.initialize()
    110 return cls._instance

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:59, in CUDASetup.initialize(self)
     56 self.lib = None
     58 from .cuda_setup.main import evaluate_cuda_setup
---> 59 binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
     60 self.cudart_path = cudart_path
     61 self.cuda = cuda

ValueError: too many values to unpack (expected 5)
```

**Comment by 0xspeedrunner** [comment]
My bad - just saw the closed ticket which fixes this.

@TimDettmers , when will the next release go out? Debating whether to install from source. Thanks!

**Comment by rexroth0619** [comment]
Also seeing this "too many values to unpack" error. Please advise, thanks!

**Comment by ilos-vigil** [comment]
I received same error message/traceback, but i solved it by installing cudatoolkit.

```
conda install cudatoolkit
```

**Comment by 0xspeedrunner** [comment]
Thanks for the suggestion, it seems like another error has cropped up when I did that: #83

**Comment by TimDettmers** [comment]
Sorry for the delay on this one. This should be fixed in the newest version, but this part also lacks tests to verify that everything is working as expected.

I will do another release probably tomorrow.
