### ISSUE TITLE
Error named symbol not found at line 74 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu

### ISSUE THREAD

**Issue by MattMuffin** [TimDettmers/bitsandbytes#791]
Config:
RTX 3090
Ubuntu 22.04

Env:
Package                   Version
------------------------- ------------
accelerate                0.24.0.dev0
aiofiles                  23.2.1
aiohttp                   3.8.5
aiosignal                 1.3.1
altair                    5.1.1
annotated-types           0.5.0
anyio                     3.7.1
appdirs                   1.4.4
async-timeout             4.0.3
attrs                     23.1.0
bitsandbytes              0.41.1
cchardet                  2.1.7
certifi                   2023.7.22
chardet                   5.2.0
charset-normalizer        3.2.0
click                     8.1.7
cmake                     3.27.5
contourpy                 1.1.1
cycler                    0.11.0
datasets                  2.14.5
dill                      0.3.7
docker-pycreds            0.4.0
einops                    0.6.1
evaluate                  0.4.0
exceptiongroup            1.1.3
fastapi                   0.103.1
ffmpy                     0.3.1
filelock                  3.12.4
fonttools                 4.42.1
frozenlist                1.4.0
fsspec                    2023.6.0
gitdb                     4.0.10
GitPython                 3.1.37
gradio                    3.45.1
gradio_client             0.5.2
h11                       0.14.0
httpcore                  0.18.0
httpx                     0.25.0
huggingface-hub           0.16.4
idna                      3.4
importlib-resources       6.1.0
Jinja2                    3.1.2
joblib                    1.3.2
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
kiwisolver                1.4.5
lit                       17.0.1
MarkupSafe                2.1.3
matplotlib                3.8.0
mpmath                    1.3.0
multidict                 6.0.4
multiprocess              0.70.15
networkx                  3.1
numpy                     1.26.0
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
orjson                    3.9.7
packaging                 23.1
pandas                    2.1.1
pathtools                 0.1.2
peft                      0.6.0.dev0
Pillow                    10.0.1
pip                       22.0.2
protobuf                  4.24.3
psutil                    5.9.5
pyarrow                   11.0.0
pydantic                  2.4.1
pydantic_core             2.10.1
pydub                     0.25.1
pyparsing                 3.1.1
python-dateutil           2.8.2
python-multipart          0.0.6
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.30.2
regex                     2023.8.8
requests                  2.31.0
responses                 0.18.0
rpds-py                   0.10.3
safetensors               0.3.3
scikit-learn              1.2.2
scipy                     1.11.2
semantic-version          2.10.0
sentencepiece             0.1.99
sentry-sdk                1.31.0
setproctitle              1.3.2
setuptools                59.6.0
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
starlette                 0.27.0
sympy                     1.12
threadpoolctl             3.2.0
tokenizers                0.14.0
toolz                     0.12.0
torch                     2.0.1
tqdm                      4.66.1
transformers              4.34.0.dev0
triton                    2.0.0
typing_extensions         4.8.0
tzdata                    2023.3
urllib3                   2.0.5
uvicorn                   0.23.2
wandb                     0.15.3
websockets                11.0.3
wheel                     0.37.1
xxhash                    3.3.0
yarl                      1.9.2

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

Drivers nvidia 525

**Comment by Ali1858** [comment]
Did you figure out the problem?

**Comment by MattMuffin** [comment]
No...

It looks like it has a local reference to a file belonging to the maintainer's file system: /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes .

**Comment by ceru23** [comment]
I'm still getting the same error, which is incredibly weird 
Error operation not supported at line 380 in file /bitsandbytes/csrc/pythonInterface.c
