### ISSUE TITLE
failed to install bitsandbytes

### ISSUE THREAD

**Issue by fzanart** [TimDettmers/bitsandbytes#802]
Hi guys, I have problems loading bitsnadbytes. I'll appreciate any help! 

False
**===================================BUG REPORT===================================
================================================================================**
The following directories listed in your path were found to be non-existent: {PosixPath('vs/workbench/api/node/extensionHostProcess')}
The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
...
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?3986c63b-976d-4d77-b885-1bbec088285f) or open in a [text editor](command:workbench.action.openLargeOutput?3986c63b-976d-4d77-b885-1bbec088285f). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
[/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166](https://vscode-remote+ssh-002dremote-002b118-002e138-002e233-002e9.vscode-resource.vscode-cdn.net/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166): UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
[/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166](https://vscode-remote+ssh-002dremote-002b118-002e138-002e233-002e9.vscode-resource.vscode-cdn.net/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166): UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/mnt/software/lib/libcudart.so'), PosixPath('/mnt/software/lib/libcudart.so.11.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
[/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166](https://vscode-remote+ssh-002dremote-002b118-002e138-002e233-002e9.vscode-resource.vscode-cdn.net/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166): UserWarning: [/mnt/software](https://vscode-remote+ssh-002dremote-002b118-002e138-002e233-002e9.vscode-resource.vscode-cdn.net/mnt/software) did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
[/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166](https://vscode-remote+ssh-002dremote-002b118-002e138-002e233-002e9.vscode-resource.vscode-cdn.net/mnt/software/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:166): UserWarning: [/usr/local/cuda/lib64](https://vscode-remote+ssh-002dremote-002b118-002e138-002e233-002e9.vscode-resource.vscode-cdn.net/usr/local/cuda/lib64):/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)

##########################################################################

I tried following the steps provided in the installation instructions and compiling from source.
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
Python 3.11.6
micromamba Version: 1.5.1

The following is the message from python -m bitsandbytes:

##########################################################################

/mnt/software/bitsandbytes/bitsandbytes/cuda_setup/main.py:106: UserWarning: 

**================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=118
================================================================================**

  warn((f'\n\n{"="*80}\n'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/mnt/software/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda118.so
/mnt/software/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118.so
/mnt/software/pkgs/cudatoolkit-11.8.0-h4ba93d1_12/lib/libcudart.so
/mnt/software/pkgs/icu-73.2-h59595ed_0/lib/libicudata.so
/mnt/software/pkgs/bitsandbytes-0.41.0-py311he54c9da_0/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/mnt/software/pkgs/pytorch-2.1.0-py3.11_cuda11.8_cudnn8.7.0_0/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
/mnt/software/pkgs/pytorch-2.1.0-py3.11_cuda11.8_cudnn8.7.0_0/lib/python3.11/site-packages/torch/lib/libtorch_cuda_linalg.so
/mnt/software/pkgs/pytorch-2.1.0-py3.11_cuda11.8_cudnn8.7.0_0/lib/python3.11/site-packages/torch/lib/libc10_cuda.so
/mnt/software/pkgs/ucx-1.14.1-h64cca9d_5/lib/ucx/libucx_perftest_cuda.so
/mnt/software/pkgs/ucx-1.14.1-h64cca9d_5/lib/ucx/libucm_cuda.so
/mnt/software/pkgs/ucx-1.14.1-h64cca9d_5/lib/ucx/libuct_cuda.so
/mnt/software/lib/libcudart.so
/mnt/software/lib/libicudata.so
/mnt/software/lib/ucx/libucx_perftest_cuda.so
/mnt/software/lib/ucx/libucm_cuda.so
/mnt/software/lib/ucx/libuct_cuda.so
/mnt/software/lib/python3.11/site-packages/bitsandbytes-0.41.1-py3.11.egg/bitsandbytes/libbitsandbytes_cuda118.so
/mnt/software/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/mnt/software/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so
/mnt/software/lib/python3.11/site-packages/torch/lib/libtorch_cuda_linalg.so
/mnt/software/lib/python3.11/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/mnt/software/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda118.so
/mnt/software/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.6']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!

**Comment by vyaskaustubh** [comment]
Hey! I am having the same issue. Any updates?

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
