### ISSUE TITLE
getting this CUDA issue in Automatic1111

### ISSUE THREAD

**Issue by alenknight** [TimDettmers/bitsandbytes#803]
seems bitsandbytes was installed with A4.  i didn't seek  out the extension but seems it's been added to the main repo.  getting this error when i run  : 

```
===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\AI\stable-diffusion-webui_bak\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
```

**Comment by imthescott** [comment]
I am too.. I have to keep deleting the bitsandbytes folder in \Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\ and then 

git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
python setup.py install

every single time I close auto1111 and open it again.

**Comment by imthescott** [comment]
> > I am too.. I have to keep deleting the bitsandbytes folder in \Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\ and then
> > git clone https://github.com/TimDettmers/bitsandbytes.git cd bitsandbytes python setup.py install
> > every single time I close auto1111 and open it again.
> 
> could work as a temp fix. seems to be working? i think probably easy enough to python or powershell script something like this to automate. and then afterpython setup.py install .... you run the web gui after?

I still haven't figured out what the actual issue is, but it did start when I updated my extensions, this is the current work around..

@echo off

set FOLDER_PATH=D:\stable-diffusion-webui\venv\Lib\site-packages\bitsandbytes

if exist "%FOLDER_PATH%" (
    rmdir /s /q "%FOLDER_PATH%"
    echo Folder %FOLDER_PATH% deleted successfully.
) else (
    echo Folder %FOLDER_PATH% does not exist.
)

git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
python setup.py install

cd D:\stable-diffusion-webui

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --api --xformers

call webui.bat

**Comment by imthescott** [comment]
> > I am too.. I have to keep deleting the bitsandbytes folder in \Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages\ and then
> > git clone https://github.com/TimDettmers/bitsandbytes.git cd bitsandbytes python setup.py install
> > every single time I close auto1111 and open it again.
> 
> could work as a temp fix. seems to be working? i think probably easy enough to python or powershell script something like this to automate. and then afterpython setup.py install .... you run the web gui after?

Ok, so I disabled ALL of my extensions (not built in), removed the script I posted above. It started up fine. I went through and toggled extensions on one at a time and closed and restarted through almost the whole list, aside from a few that I really don't use or were redundant. So it may be one of those causing the issue.

I don't plan on testing the rest, but I can if it would help others.

This is what is disabled for extensions that I have not tested - 

StylePile
miaoshouai-assistant
rembg
sd-dynamic-prompts
sd-webui-lora-block-weight
sd-webui-openpose-editor
sd-webui-roop
sd_dreambooth_extension
stable-diffusion-webui-rembg

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
