### ISSUE TITLE
CUDA initialization fails with "CUDA not found" error on import

### ISSUE THREAD

**Issue by lmsanch** [TimDettmers/bitsandbytes#805]
I am trying to import and use bitsandbytes on my system but am encountering an issue with CUDA initialization.

System Details:

OS: Ubuntu 22.04
GPU: NVIDIA RTX 3090
CUDA version: 12.2
Python version: 3.10
bitsandbytes version: 0.40.0

Steps to reproduce:

Installation: pip install bitsandbytes
import test:
```
import bitsandbytes
try:
  bitsandbytes.cuda  
  print("CUDA initialized")
except AttributeError:
  print("CUDA not found") 
```
Output is "CUDA not found"
I have validated:

CUDA 12.2 is installed correctly
/usr/local/cuda/bin is in PATH
Basic CUDA operations like matrix multiplication work independently in PyTorch
However, bitsandbytes fails to initialize CUDA on import with just the "CUDA not found" error.

Could you please take a look? Providing any other debugging tips or minimal reproducible sample would also be appreciated.

Let me know if you need any other system details or logs to investigate further.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
