### ISSUE TITLE
更新数据后无法启动

### ISSUE THREAD

**Issue by smilingflyingpig** [TimDettmers/bitsandbytes#806]
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by stuser** [comment]
你可以先確認 bitsandbytes library 是否有安裝成功 (Could you please confirm whether the 'bitsandbytes' library has been installed successfully?)
