### ISSUE TITLE
Error when cudart found, but cuda not

### ISSUE THREAD

**Issue by TimDettmers** [TimDettmers/bitsandbytes#81]
#16 1.968 ===================================BUG REPORT===================================
#16 1.968 Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
#16 1.968 For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
#16 1.968 ================================================================================
#16 1.968 CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
#16 1.968 CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
#16 1.968 CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
#16 1.968     from .autograd._functions import (
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py:5: in <module>
#16 1.968     import bitsandbytes.functional as F
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py:13: in <module>
#16 1.968     from .cextension import COMPILED_WITH_CUDA, lib
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:41: in <module>
#16 1.968     lib = CUDALibrary_Singleton.get_instance().lib
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:37: in get_instance
#16 1.968     cls._instance.initialize()
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:15: in initialize
#16 1.968     binary_name = evaluate_cuda_setup()
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:132: in evaluate_cuda_setup
#16 1.968     cc = get_compute_capability(cuda)
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:105: in get_compute_capability
#16 1.968     ccs = get_compute_capabilities(cuda)
#16 1.968 /opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:83: in get_compute_capabilities
#16 1.968     check_cuda_result(cuda, cuda.cuDeviceGetCount(ctypes.byref(nGpus)))
#16 1.968 E   AttributeError: 'NoneType' object has no attribute 'cuDeviceGetCount'
#16 ERROR: process "/bin/sh -c PYTHONPATH=. pytest tests/ --durations=0 --durations-min=1.0 -v" did not complete successfully: exit code: 4

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
