### ISSUE TITLE
Problem with environment variables on Windows platform

### ISSUE THREAD

**Issue by levicki** [TimDettmers/bitsandbytes#811]
@TimDettmers 

This code:
https://github.com/TimDettmers/bitsandbytes/blob/18e827d666fa2b70a12d539ccedc17aa51b2c97c/bitsandbytes/cuda_setup/env_vars.py#L6

Does not take into account any of the environment variables that might contain paths on Windows but which should be ignored:

As a result, the following error is shown:

```
(venv) d:\AI\AUTOMATIC1111>python -m bitsandbytes
False

===================================BUG REPORT===================================
d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
The following directories listed in your path were found to be non-existent: {WindowsPath('/Windows/Symbols*/CORE/symbols*http'), WindowsPath('Srv*C'), WindowsPath('//msdl.microsoft.com/download/symbols')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\PROGRAMS\Python\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\PROGRAMS\Python\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\PROGRAMS\Python\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "d:\AI\AUTOMATIC1111\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

One example of an environment variable being picked up when it should be ignored is:

```
_NT_SYMBOL_PATH=Srv*C:\Windows\Symbols*\\CORE\symbols*http://msdl.microsoft.com/download/symbols
```

Another example is:

```
SD_WEBUI_RESTART=tmp/restart
```

This code makes unsafe platform-dependent assumptions on naming conventions and content of environment variables which IMO is really bad.

It is also worth noting that on Windows CUDA path is contained in (aptly named) `CUDA_PATH` variable:

```
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2
```

Actual libraries and executables (including `cudart64_12.dll`) are in the `%CUDA_PATH%\bin` folder.

Please fix.

**Comment by hozdenoren** [comment]
Per the readme file: "Windows is not supported at the moment."

**Comment by levicki** [comment]
> Per the readme file: "Windows is not supported at the moment."

There are several forks that support Windows, first one was this one:

https://github.com/acpopescu/bitsandbytes/tree/cmake_windows

How hard would be to pull the necessary bits from it and make it support both platforms?

**Comment by hozdenoren** [comment]
Yea, I think it would definitely be worth it. You can also give it a try using windows subsystem for linux (WSL).

**Comment by levicki** [comment]
> You can also give it a try using windows subsystem for linux (WSL).

Sadly not an option for using AUTOMATIC1111. Native CUDA stuff works better anyway and I can compile xformers with CUDA 12.x and 8.9 arch.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by levicki** [comment]
@swumagic I am aware that there is a Windows fork of bitsandbytes, my request is that the author of the package integrates Windows support into the original package if possible.

**Comment by levicki** [comment]
Activity.

**Comment by levicki** [comment]
Activity.

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗

**Comment by levicki** [comment]
@Titus-von-Koeller Great work, many thanks.
