### ISSUE TITLE
CUDA Setup failed despite GPU being available. Please run the following command to get more information

### ISSUE THREAD

**Issue by twers1** [TimDettmers/bitsandbytes#817]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
False
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were 
found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatool
kit package (anaconda)!
  warn(msg)
C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding 
to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\Admin\PycharmProjects\mcstudio-openai\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by Mercycany** [comment]
same
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/qiao/mambaforge/envs/llava/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git

**Comment by hozdenoren** [comment]
Hi all, I have the same issue,  

I am using wsl 2 with Ubuntu:

```
PS C:\Windows\System32> wsl -l -v
  NAME      STATE           VERSION
* Ubuntu    Running         2
```

Installed Cuda 

```
(.venv) hozdenoren@DESKTOP-MN4H4I4:~/local/cuda-11.8/lib64$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

Getting the same error as above; 

```
The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
The following directories listed in your path were found to be non-existent: {PosixPath('\n'), PosixPath('ELECTRON_RUN_AS_NODE/w')}
The following directories listed in your path were found to be non-existent: {PosixPath('vs/workbench/api/node/extensionHostProcess')}
The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /mnt/c/Users/Hakki/Desktop/LocalGPT/.venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
```

I have tried `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/hozdenoren/local/cuda-11.8` 

as when I go there I can see the files and I can find the libcudart.so in the directory but that also did not work.

<img width="949" alt="image" src="https://github.com/TimDettmers/bitsandbytes/assets/56940207/7ddd1cc6-704a-4d66-82ff-31e8a01cf6eb">

**Comment by twers1** [comment]
> same CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths... DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')} CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.0. CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md CUDA SETUP: Loading binary /home/qiao/mambaforge/envs/llava/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so... libcusparse.so.11: cannot open shared object file: No such file or directory CUDA SETUP: Something unexpected happened. Please compile from source: git clone https://github.com/TimDettmers/bitsandbytes.git

try it:

`python -m pip install bitsandbytes --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui`

or download another version

**Comment by twers1** [comment]
> Hi all, I have the same issue,
> 
> I am using wsl 2 with Ubuntu:
> 
> ```
> PS C:\Windows\System32> wsl -l -v
>   NAME      STATE           VERSION
> * Ubuntu    Running         2
> ```
> 
> Installed Cuda
> 
> ```
> (.venv) hozdenoren@DESKTOP-MN4H4I4:~/local/cuda-11.8/lib64$ nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Wed_Sep_21_10:33:58_PDT_2022
> Cuda compilation tools, release 11.8, V11.8.89
> Build cuda_11.8.r11.8/compiler.31833905_0
> ```
> 
> Getting the same error as above;
> 
> ```
> The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
> The following directories listed in your path were found to be non-existent: {PosixPath('\n'), PosixPath('ELECTRON_RUN_AS_NODE/w')}
> The following directories listed in your path were found to be non-existent: {PosixPath('vs/workbench/api/node/extensionHostProcess')}
> The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
> DEBUG: Possible options found for libcudart.so: set()
> CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
> CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
> CUDA SETUP: Loading binary /mnt/c/Users/Hakki/Desktop/LocalGPT/.venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
> libcusparse.so.11: cannot open shared object file: No such file or directory
> CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
> CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
> CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
> ```
> 
> I have tried `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/hozdenoren/local/cuda-11.8`
> 
> as when I go there I can see the files and I can find the libcudart.so in the directory but that also did not work.
> 
> <img alt="image" width="949" src="https://user-images.githubusercontent.com/56940207/274472911-7ddd1cc6-704a-4d66-82ff-31e8a01cf6eb.png">

sup, i have ubuntu, how to install now cuda nvidia? 
![image](https://github.com/TimDettmers/bitsandbytes/assets/102418053/2c2b86ef-05a9-43a9-b5bf-ea4011e63a57)

I just already downloaded nvidia cuda on windows and in the windows environment variables it is also set to "PATH"

![image](https://github.com/TimDettmers/bitsandbytes/assets/102418053/66b05b0f-46d7-4686-bd50-707bc1a1fa49)

**Comment by hozdenoren** [comment]
Ideally pytorch should already install cuda afaik. Below can select your config and it gives you the correct pip code:

https://pytorch.org/get-started/locally/

**Comment by hozdenoren** [comment]
> sup, i have ubuntu, how to install now cuda nvidia? ![image](https://user-images.githubusercontent.com/102418053/274514654-2c2b86ef-05a9-43a9-b5bf-ea4011e63a57.png)
> 
> I just already downloaded nvidia cuda on windows and in the windows environment variables it is also set to "PATH"
> 
> ![image](https://user-images.githubusercontent.com/102418053/274515041-66b05b0f-46d7-4686-bd50-707bc1a1fa49.png)

Ideally pytorch should already install cuda afaik. Below can select your config and it gives you the correct pip code:

https://pytorch.org/get-started/locally/

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by XixuHu** [comment]
> Hi all, I have the same issue,
> 
> I am using wsl 2 with Ubuntu:
> 
> ```
> PS C:\Windows\System32> wsl -l -v
>   NAME      STATE           VERSION
> * Ubuntu    Running         2
> ```
> 
> Installed Cuda
> 
> ```
> (.venv) hozdenoren@DESKTOP-MN4H4I4:~/local/cuda-11.8/lib64$ nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Wed_Sep_21_10:33:58_PDT_2022
> Cuda compilation tools, release 11.8, V11.8.89
> Build cuda_11.8.r11.8/compiler.31833905_0
> ```
> 
> Getting the same error as above;
> 
> ```
> The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
> The following directories listed in your path were found to be non-existent: {PosixPath('\n'), PosixPath('ELECTRON_RUN_AS_NODE/w')}
> The following directories listed in your path were found to be non-existent: {PosixPath('vs/workbench/api/node/extensionHostProcess')}
> The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
> The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
> DEBUG: Possible options found for libcudart.so: set()
> CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.6.
> CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
> CUDA SETUP: Loading binary /mnt/c/Users/Hakki/Desktop/LocalGPT/.venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
> libcusparse.so.11: cannot open shared object file: No such file or directory
> CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
> CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
> CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
> ```
> 
> I have tried `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/hozdenoren/local/cuda-11.8`
> 
> as when I go there I can see the files and I can find the libcudart.so in the directory but that also did not work.
> 
> <img alt="image" width="949" src="https://private-user-images.githubusercontent.com/56940207/274472911-7ddd1cc6-704a-4d66-82ff-31e8a01cf6eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODE5MTksIm5iZiI6MTcwNDg4MTYxOSwicGF0aCI6Ii81Njk0MDIwNy8yNzQ0NzI5MTEtN2RkZDFjYzYtNzA0YS00ZDY2LTgyZmYtMzFlOGEwMWNmNmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDVlNGRkYThlYTlhN2Y5ZTg4NjQwOThmZGZjYTNhMjM3NTAwNDU5ZTNkZWRhMmVkMDIxZjNhOTUyMDQwNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZCZKkJOCoirUjV4-PkloXgsOvV_3fnpTm544dK-fOAg">

Have you found the solution? I came across exactly the same problem on WSL2. My cuda is 11.6.
