### ISSUE TITLE
KeyError: 'LD_LIBRARY_PATH'

### ISSUE THREAD

**Issue by xiaodou2021** [TimDettmers/bitsandbytes#819]
在执行accelerate launch --num_processes 1 --num_machines 1 --machine_rank 0  --mixed_precision fp16 --num_cpu_threads_per_process 1 train.py --config configs/train/finetune_test.yaml时，报如下错误：

================================================================================
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda_linalg.so
/usr/local/lib/python3.10/dist-packages/torch/lib/libc10_cuda.so
/usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda111.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda121.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda122.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda110.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda120.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda114.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda117.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda115.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/opt/gpt4all/gpt4all-main1/gpt4all-training/.env/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'

**Comment by righere** [comment]
pip uninstall bitsandbytes
python -m pip install bitsandbytes --prefer-binary --extra-index-url=https://jllllll.github.io/bitsandbytes-windows-webui

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
