### ISSUE TITLE
Trainer class impossible to use when installed via pip on Windows

### ISSUE THREAD

**Issue by celsowm** [TimDettmers/bitsandbytes#824]
I am trying to use the Trainer class from transformers module on Windows 10, python 3.10 and CUDA 12.1 and *all modules installed using* **pip**.

nvcc --version :

    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2023 NVIDIA Corporation
    Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
    Cuda compilation tools, release 12.1, V12.1.66
    Build cuda_12.1.r12.1/compiler.32415258_0

cuda available:

    torch.cuda.is_available() #True

But when I tried to import Trainer:

    from transformers import Trainer

I got a huge log error:

    CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
    The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
    DEBUG: Possible options found for libcudart.so: set()
    CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.6.
    CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
    CUDA SETUP: Loading binary D:\Program Files\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
    argument of type 'WindowsPath' is not iterable
    CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
    CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
    CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
    CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
    CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
    CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
    CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
    CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
    CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local

and

    RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
    
            CUDA Setup failed despite GPU being available. Please run the following command to get more information:
    
            python -m bitsandbytes
    
            Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
            to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
            and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

Trying to debug the **bitsandbytes** *.py files, on cuda_setups, there is a module called "env_vars":

https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/cuda_setup/env_vars.py

Apparently it would only work with conda, is that right?

So is there any workaround to make this work?

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
