### ISSUE TITLE
Huge difference in llama2 parameter count after 4bit loading

### ISSUE THREAD

**Issue by akshayiyer2610** [TimDettmers/bitsandbytes#834]
After loading the llama2-7b-text model using 4-bit quantization, the total parameter count is reduced to ~3.5B. Is this a bug or the expected behavior.

Packages:
bitsandbytes => 0.41.1
transformers => 4.33.2
torch => 2.0.1

Code:
```
bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16
    )
model_name = "local_llama2/llama2-7b-hf" # this contains the llama2 model downloaded from huggingface; sitting on my local machine

model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto"
    )

all_param = 0
for _, param in model.named_parameters():
    num_params = param.numel()
    all_param += num_params

print(f"all params: {all_param}")
```

The output of print statement is 3,540,389,888.

**Comment by akshayiyer2610** [comment]
Does that imply the other ~3.5B parameters are frozen during the quantization process?

**Comment by akshayiyer2610** [comment]
Thanks for the link to source code @OneCodeToRuleThemAll . Much appreciated.

**Comment by arvindpdmn** [comment]
Bot closed this issue even when it hasn't been resolved. Quantization reduces memory requirements but has no effect on parameter count. I see this as a bu.
