### ISSUE TITLE
bitsandbytes-cuda118 on pypi.org?

### ISSUE THREAD

**Issue by B0rner** [TimDettmers/bitsandbytes#866]
Is ist possible to publish bitsandbytes compiled for cuda118 on pypi.org?

I'm trying to use bitsandbytes on an windows system with cuda11.8, but bitsandbytes is only avalible for CUDA 11.0 - 11.7.

I know, that it could be possible to compile that locale, but I don't get this running. :-/

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
