### ISSUE TITLE
module 'bitsandbytes' has no attribute 'matmul_mixed'

### ISSUE THREAD

**Issue by FrostML** [TimDettmers/bitsandbytes#874]
hi, when I tried to test `SwitchBackLinearBnb` in order to verify the performance differences with the corresponding API in triton, I got this error message:

``` bash
AttributeError: module 'bitsandbytes' has no attribute 'matmul_mixed'
```

Is there any specific version I need to run `SwitchBackLinearBnb`?

Thanks ahead.

**Comment by DmitryRedko** [comment]
Hi @FrostML! Have you solved this problem?
