### ISSUE TITLE
Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0']

### ISSUE THREAD

**Issue by yogurt-sn** [TimDettmers/bitsandbytes#877]
I‘m Linux system
===================================BUG REPORT===================================                                                                                                                Welcome to bitsandbytes. For bug reports, please run                                                                                                                                            feb                                                                                                                                                                                             python -m bitsandbytes                                                                                                                                                                          /da                                                                                                                                                                                              and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues                                                                              ================================================================================                                                                                                                bin /conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda113.so                                                                                                       /conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/conda/envs/myenv/lib/libcudart.so'), PosixPath('/conda/envs/myenv/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.                                   Either way, this might cause trouble in the future:                                                                                                                                             If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.                                                                                                                                                         warn(msg)
CUDA SETUP: CUDA runtime path found: /conda/envs/myenv/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/conda/envs/myenv/lib/python3.7/site-packages/torch/lib/libc10_cuda.so
/conda/envs/myenv/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so
/conda/envs/myenv/lib/python3.7/site-packages/torch/lib/libtorch_cuda_cpp.so
/conda/envs/myenv/lib/python3.7/site-packages/torch/lib/libtorch_cuda_cu.so
/conda/envs/myenv/lib/libcudart.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.3/compat/libcuda.so
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.3/targets/x86_64-linux/lib/stubs/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/conda/envs/myenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/conda/envs/myenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/conda/envs/myenv/lib/python3.7/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/conda/envs/myenv/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'

**Comment by danielAdama** [comment]
I am also facing similar issue on "nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04" ace to: https://github.com/TimDettmers/bitsandbytes/issues
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  | ================================================================================================================================================================
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  | bin bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
jacq-chatbot-api_1  |   warn("The installed version of bitsandbytes was compiled without GPU support. "
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
jacq-chatbot-api_1  | CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so...
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
jacq-chatbot-api_1  |   warn("The installed version of bitsandbytes was compiled without GPU support. "
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
jacq-chatbot-api_1  | CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so...
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  | ===================================BUG REPORT===================================
jacq-chatbot-api_1  | Welcome to bitsandbytes. For bug reports, please run
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  | python -m bitsandbytes
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  |  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
jacq-chatbot-api_1  | ================================================================================
jacq-chatbot-api_1  | bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
jacq-chatbot-api_1  | CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so...
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
jacq-chatbot-api_1  |   warn("The installed version of bitsandbytes was compiled without GPU support. "
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  | ===================================BUG REPORT===================================
jacq-chatbot-api_1  | Welcome to bitsandbytes. For bug reports, please run
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  | python -m bitsandbytes
jacq-chatbot-api_1  | 
jacq-chatbot-api_1  |  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
jacq-chatbot-api_1  | ================================================================================
jacq-chatbot-api_1  | bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
jacq-chatbot-api_1  | CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cpu.so...
jacq-chatbot-api_1  | /usr/local/lib/python3.10/dist-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
jacq-chatbot-api_1  |   warn("The installed version of bitsandbytes was compiled without GPU support. "
