### ISSUE TITLE
help!OSError: Can't load tokenizer for 'decapoda-research/llama-2-7b-hf'.

### ISSUE THREAD

**Issue by liujing0922** [TimDettmers/bitsandbytes#878]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\test1\.conda\envs\bllama\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\test1\.conda\envs\bllama\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
cuda
**traceback (most recent call last):
  File "D:\lj\BLLAMA-main\generate.py", line 11, in <module>
    tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-2-7b-hf")
  File "C:\Users\test1\.conda\envs\bllama\lib\site-packages\transformers\tokenization_utils_base.py", line 2012, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'decapoda-research/llama-2-7b-hf'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'decapoda-research/llama-2-7b-hf' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.**

**Comment by BrownTan** [comment]
I have encountered this issue, too. Have you solved the problem?

**Comment by Audioanxet** [comment]
I have encountered this issue, too. Have you solved the problem?

**Comment by BrownTan** [comment]
> I have encountered this issue, too. Have you solved the problem?

May be the network.
