### ISSUE TITLE
Install of package in the python environment has an impact on unrelated trainings

### ISSUE THREAD

**Issue by christopher5106** [TimDettmers/bitsandbytes#888]
Hi,

I'm surprised that the simple 

`pip install bitsandbytes`

in the environment could lead to low quality diffusion training on stable diffusion xl. Results are more noisy.

How is it possible that the package has an impact on code without being activated ? Is it loaded somehow automatically in the transformers of the textencoder ? 

Trainings done without accelerate.

Thanks in advance

**Comment by sayakpaul** [comment]
Until and unless you specify `--use_8bit_adam` that shouldn't happen. Also, for most use cases, we find the use of 8bit Adam to be sufficient enough. If you can provide more info on how we can reproduce this, that'd be much appreciated.

**Comment by christopher5106** [comment]
I know that a  longer training will probably compensate the noise that
appears, but the thing is that this lib is not activated in your code !
That's totally surprising to me. There is a border effect.

Christopher Bourez
06 17 17 50 60

**Comment by christopher5106** [comment]
Hi,

Sorry for having bothered you, more runs proved the observed variations
couldn't justify a bug in bitsandbytes, it was a false alert. I'm very
sorry!

Christopher Bourez
06 17 17 50 60

**Comment by christopher5106** [comment]
False alert, I'm deeply sorry!
