### ISSUE TITLE
Does llm.int8() use calibration dataset?

### ISSUE THREAD

**Issue by YiFei1532** [TimDettmers/bitsandbytes#891]
Hi, when i read your paper about llm.int8() i find that you detect the outliers according to input of every linear, which means we need a calibration dataset. However, the codes seems just relying on weights of the linear to do quantization in bitsandbytes.functional.double_quant() and need no dataset. So i wonder if i misunderstood your method in paper, or if i accidentally neglect something important in codes? Thanks in advance!

**Comment by smpanaro** [comment]
Hi @YiFei1532, I actually have the same question as you. Did you find an answer?

I’m looking at the smallest GPT2 (huggingface’s, not OpenAI’s like in the paper), and I get one outlier by looking at the weights (using the method in the utils folder). When I look at the inputs to the linear layers as described in the paper (>6 magnitude,25% layers,6% seq) I get 4 total outliers, but they do include the one calculated by the weights. Interestingly the 4 outliers seem to not depend on the inputs. 

I could definitely be doing by something by wrong though.

**Comment by seanxwzhang** [comment]
Hi @smpanaro, I'm having the same question here, did you eventually come to a conclusion/answer?

**Comment by smpanaro** [comment]
@seanxwzhang I never found an answer to that exact question. But I think looking at the activations (inputs to the linear layers) is a valid approach ([AWQ](https://github.com/mit-han-lab/llm-awq) does something similar, see also [AutoAWQ](https://github.com/casper-hansen/AutoAWQ)). Another approach is the one from [SqueezeLLM](https://github.com/SqueezeAILab/SqueezeLLM) which gets per-weight element importance ([code](https://github.com/kssteven418/SqueezeLLM-gradients)).

**Comment by seanxwzhang** [comment]
Thanks @smpanaro! After some digging, my preliminary conclusion is that snb is able to avoid using a calibration dataset to detect outliers by using the following heuristics:

1. If dimension `h` of features in layer `l` are outliers (according to the paper, greater than 6), then it's likely that the corresponding dimension from the weight matrix in layer `l-1` is large as well, so we can detect the feature outlier in layer `l` by looking at the weight matrix in layer `l-1`
2. The above rule doesn't work for the first layer of a model, so snb actually does look at the input and detect outlier by checking the magnitude of input.

[Relevant code](https://github.com/TimDettmers/bitsandbytes/blob/706ec24d2f5717cf484191d2f09011432640a8e6/bitsandbytes/utils.py#L17-L36)

**Comment by smpanaro** [comment]
@seanxwzhang Thanks for following up! Your reasoning makes sense to me. Looking at the weights is certainly easier than the activations.
