### ISSUE TITLE
[RFC] .cuda() implementation not idempotent

### ISSUE THREAD

**Issue by WeixiongLin** [TimDettmers/bitsandbytes#906]
LLM generate special token `UNKNOWN` repetitively when used with `transformers.LlamaForCausalLM`.

Given user prompt `hello, how are you`, LLaMA2-7B would generate '\<unk\>\<unk\> ... \<unk\>'. Use the following code to reproduce the error:
```python
import torch
import transformers

# 1. Load Tokenizer, Model
model_path = 'Llama-2-7b-chat-hf'
tokenizer = transformers.LlamaTokenizer.from_pretrained(model_path)

quantization_config = transformers.BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_threshold=0.0
)
model = transformers.LlamaForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype=torch.float16,
    quantization_config=quantization_config,
)
model.cuda()


# 2. Generate Answer
input_str = ['hello can you help me']
model_inputs = tokenizer(
    input_str,
    return_tensors='pt',
    padding=True,
)
outputs = model(model_inputs.input_ids)
topk_output = model.generate(
    model_inputs.input_ids,
    max_new_tokens=500,
    top_k=50,
)
output_str = tokenizer.batch_decode(topk_output)

print(output_str[0])
```

**Comment by WeixiongLin** [comment]
The error is actually cause by multiple call of `model.cuda()`.
1. `transformers.LlamaForCausalLM.from_pretrained` would call `model.cuda()` by default.
2. The code snippet explicitly call `model.cuda()` again

So that `bitsandbytes.nn.modules.Int8Params` would execute `def cuda(self, device)` twice as defined in https://github.com/TimDettmers/bitsandbytes/blob/main/bitsandbytes/nn/modules.py#L299

Somehow, `Int8Params.cuda`'s implementation is **not idempotent** as general assumptions. 
```python
class Int8Params(torch.nn.Parameter):
...
    def cuda(self, device):
        if self.has_fp16_weights:
            return super().cuda(device)
        else:
            # we store the 8-bit rows-major weight
            # we convert this weight to the turning/ampere weight during the first inference pass
            B = self.data.contiguous().half().cuda(device)
            CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
            del CBt
            del SCBt
            self.data = CB
            setattr(self, "CB", CB)
            setattr(self, "SCB", SCB)

        return self
```

For example, if the initial state is `self.data = torch.tensor([[1.6, 3.2, 6.4]], dtype=torch.float16)`.

| Called Times | self.data | CB | SCB |
| --- | --- | --- | --- |
| 0 | `[[1.6, 3.2, 6.4]]` | `None` | `None`  |
| 1 | `[[ 32,  63, 127]]` | `[[ 32,  63, 127]]` | `[6.3984]` |
| 2 | `[[ 32,  63, 127]]` | `[[ 32,  63, 127]]` | `[127.]` |

As been observed, `SCB` reached a different state when called second time. So that there would be an error if the user mistakenly call `model.cuda()` extra times.

**Comment by WeixiongLin** [comment]
The quick fix to this issue is just comment out `model.cuda()`. Since overwriting the `cuda` method inherited from `torch.nn.Parameter` might cause unexpected errors, I suggest to simply rename the function.

**Comment by WeixiongLin** [comment]
I really appreciate your efforts on bitsandbytes and would love to hear your feedback on this issue.

And if you think it's necessary to change the code behaviour, I would love to help with that and raise a PR.

**Comment by younesbelkada** [comment]
Hi @WeixiongLin 
Thanks a lot for your issue and for the clean reproducer. In fact, you should not call `cuda()` if your model has been already loaded with HF transformers through `device_map="auto"`

```diff
import torch
import transformers

# 1. Load Tokenizer, Model
model_path = 'Llama-2-7b-chat-hf'
tokenizer = transformers.LlamaTokenizer.from_pretrained(model_path)

quantization_config = transformers.BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_threshold=0.0
)
model = transformers.LlamaForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    torch_dtype=torch.float16,
    quantization_config=quantization_config,
)
- model.cuda()

# 2. Generate Answer
input_str = ['hello can you help me']
model_inputs = tokenizer(
    input_str,
    return_tensors='pt',
    padding=True,
)
outputs = model(model_inputs.input_ids)
topk_output = model.generate(
    model_inputs.input_ids,
    max_new_tokens=500,
    top_k=50,
)
output_str = tokenizer.batch_decode(topk_output)

print(output_str[0])
```
`device_map="auto"` already dispatches the models into the correct devices and available GPUs, calling cuda() again will recursively call `cuda()` on all submodules, causing the int8 modules to be quantized twice. Currently the fix is to remove the cuda() call as you pointed out above. Again there is no need to set a new device once you loaded your model with device_map="auto"

**Comment by WeixiongLin** [comment]
Thanks for your reply. Since it's an expected feature I am going to close this issue.
