### ISSUE TITLE
CUDA ooM ( Reserved Memory > than Allocated Memory 

### ISSUE THREAD

**Issue by giblfiz** [TimDettmers/bitsandbytes#94]
Thanks so much for all your work on this tool. It's amazing!

I'm running a GeForce RTX 3060 with 12 gigs of vRam
I installed via the automatic1111 web UI and extension

I used the following settings:
````
Total Number classification images: 1500
Training Steps: 1200
Learning Rate: 0.000001
Save a checkpoint every: 50000 (effectively no checkpoints)
Generate a preview every: 50000

Advanced: 
checked use8bitAdam
mixed precision fp16
````

I'm getting the following error:

```
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


==BUG REPORT==
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link


CUDA SETUP: Loading binary C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Scheduler Loaded
 Allocated: 0.2GB
 Reserved: 0.2GB

Steps:   0%|                                                                                  | 0/1200 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.67 GiB already allocated; 0 bytes free; 10.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 8.1GB
 Reserved: 10.4GB

Traceback (most recent call last):
  File "C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 920, in main
    accelerator.backward(loss)
  File "C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 882, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\venv\lib\site-packages\torch\_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 253, in apply
    return user_fn(self, *args)
  File "C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\venv\lib\site-packages\torch\utils\checkpoint.py", line 146, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "C:\Users\giblf\StableDiffusion\SD-gitclone\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.67 GiB already allocated; 0 bytes free; 10.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 7.1GB
 Reserved: 10.4GB

 Cleanup Complete.
 Allocated: 6.9GB
 Reserved: 7.7GB

Steps:   0%|                                                                                  | 0/1200 [00:19<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 7.7GB

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Training completed, reloading SD Model.': '0.0/7.7GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 1
```

**Comment by vixound** [comment]
i got the same problem and the same config

**Comment by RomixERR** [comment]
`venv "C:\Stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0b5dcb3d7ce397ad38312dbfc70febe7bb42dcc3
Installing requirements for Web UI
Checking Dreambooth requirements...
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is 1d7d34110005e7930b589546ff5d82ce16cdcadd
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.8.1 installed.
[+] transformers version 4.21.0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
[ ] xformers version 0.0.14.dev0 installed.

Launching Web UI with arguments: --deepdanbooru --xformers
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [81761151] from C:\Stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 12 textual inversion embeddings.
Embeddings: accurate-angel, dark-forest, depthmap, doose-realistic, Emma, HHHSofiko, ingmar-bergman, m-geo, nixeu, party-girl, ruan-jia, tcircle
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Replace CrossAttention.forward to use xformers
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
 Cleanup completed.
 Allocated: 0.2GB
 Reserved: 0.2GB

 Scheduler, EMA Loaded.
 Allocated: 3.8GB
 Reserved: 3.9GB

***** Running training *****
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:***** Running training *****
  Num examples = 62
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Num examples = 62
  Num batches each epoch = 62
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Num batches each epoch = 62
  Num Epochs = 17
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Num Epochs = 17
  Instantaneous batch size per device = 1
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Gradient Accumulation steps = 1
  Total optimization steps = 1000
INFO:extensions.sd_dreambooth_extension.dreambooth.train_dreambooth:  Total optimization steps = 1000
   Training settings: CPU: False Adam: True, Prec: fp16, Grad: True, TextTr: True EM: False, LR: 1.72e-06
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                  | 0/1000 [00:00<?, ?it/s] Exception while training: CUDA out of memory. Tried to allocate 9.00 GiB (GPU 0; 24.00 GiB total capacity; 4.03 GiB already allocated; 14.50 GiB free; 4.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 Allocated: 4.0GB
 Reserved: 4.1GB

Traceback (most recent call last):
  File "C:\Stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 990, in main
    latent_dist = vae.encode(batch["pixel_values"].to(dtype=weight_dtype)).latent_dist
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 570, in encode
    h = self.encoder(x)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\diffusers\models\vae.py", line 134, in forward
    sample = down_block(sample)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 771, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\diffusers\models\resnet.py", line 464, in forward
    hidden_states = self.conv1(hidden_states)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 9.00 GiB (GPU 0; 24.00 GiB total capacity; 4.03 GiB already allocated; 14.50 GiB free; 4.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
 CLEANUP:
 Allocated: 3.8GB
 Reserved: 4.1GB

 Cleanup completed.
 Allocated: 3.8GB
 Reserved: 3.9GB

 Cleanup Complete.
 Allocated: 3.8GB
 Reserved: 3.9GB

Steps:   0%|                                                                                  | 0/1000 [00:03<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.8GB

Memory output: {'Training completed, reloading SD Model.': '0.0/3.8GB'}
 Restored system models.
 Allocated: 2.0GB
 Reserved: 3.8GB

Returning result: Training finished. Total lifetime steps: 0`

The problems with memory allocation and allocation are the same as yours, but I have 24 GB available. But CUDA refuses to work. The settings are similar to yours. What could be the problem?

**Comment by EiderFC** [comment]
I have the same problem

**Comment by TimDettmers** [comment]
This happens in particular with convolutional architectures if your inputs are too large. @RomixERR I think in that case in particular you fed a very large image into the model. Try downsampling the image to make it smaller before feeding it into the model.

This issue does not seem like a bitsandbytes issue, but I will keep it open for now so that you have a space in which you night find a solution to this problem. Its also a useful reference for other people running into this problem.
