### ISSUE TITLE
python -m bitsandbytes

### ISSUE THREAD

**Issue by AishwaryaRao19** [TimDettmers/bitsandbytes#942]
### System Info

CUDA: 12.1
Python: 3.10
OS: Windows

### Reproduction

>>>> python -m bitsandbytes
bin C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\bin\cudart64_12.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda111_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda112.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda112_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda113.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda113_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda114.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda114_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda115.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda115_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda120.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda120_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\bitsandbytes\libbitsandbytes_cuda122_nocublaslt.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\torch\lib\c10_cuda.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\torch\lib\torch_cuda.dll

++++++++++++++++++++ PYTORCH CUDA PATHS ++++++++++++++++++++
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\torch\lib\c10_cuda.dll
C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\lib\site-packages\torch\lib\torch_cuda.dll

+++++++++++++++++++ CUDA_PATH CUDA PATHS +++++++++++++++++++
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin\cudart64_12.dll
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\extras\visual_studio_integration\MSBuildExtensions\Nvda.Build.CudaTasks.v12.0.dll

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\site-packages\bitsandbytes\__main__.py", line 121, in <module>
    generate_bug_report_information()
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\site-packages\bitsandbytes\__main__.py", line 85, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*' + SHARED_LIB_EXTENSION)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\site-packages\bitsandbytes\__main__.py", line 39, in find_file_recursive
    out, err = execute_and_return(cmd)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\site-packages\bitsandbytes\__main__.py", line 34, in execute_and_return
    std_out, std_err = execute_and_return_decoded_std_streams(command_string)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\site-packages\bitsandbytes\__main__.py", line 28, in execute_and_return_decoded_std_streams
    shlex.split(command_string),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\shlex.py", line 315, in split
    return list(lex)
           ^^^^^^^^^
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\shlex.py", line 300, in __next__
    token = self.get_token()
            ^^^^^^^^^^^^^^^^
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\shlex.py", line 109, in get_token
    raw = self.read_token()
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\ais81034\AppData\Local\anaconda3\envs\Thesis\Lib\shlex.py", line 191, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

### Expected behavior

bitsandbytes is giving me the above error and I need it to run, so that I can run my LLM models. I am very new to CUDA, it would be great if I could get some assistance. I have already tried to uninstall and reinstall bitsandbytes, and add to the python folder too.

**Comment by AidanShipperley** [comment]
Bitsandbytes [does not work natively on Windows](https://github.com/TimDettmers/bitsandbytes/issues/30). You need a version compiled specifically for Windows. Uninstall your bitsandbytes and install this one:

```
pip uninstall bitsandbytes
```

```
pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl
```

**Comment by aelyoussfi** [comment]
@AidanShipperley thanks man, you saved my day!

**Comment by motoko33** [comment]
@AidanShipperley It works! Thanks a lot~

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
