### ISSUE TITLE
both libbitsandbytes_cuda113.so and libbitsandbytes_cuda113_nocublaslt.so are not generated

### ISSUE THREAD

**Issue by wushandinghua** [TimDettmers/bitsandbytes#973]
### System Info

I want to generate these two files by compiling from source. Here is what i did.
"""
cd bitsandbytes
CUDA_VERSION=113 make cuda11x
CUDA_VERSION=113 make cuda11x_nomatmul
python setup.py install
"""
But i neither found libbitsandbytes_cuda113.so nor libbitsandbytes_cuda113_nocublaslt.so under fold 'bitsandbytes'.

### Reproduction

my bashrc is below:
export BNB_CUDA_VERSION=113
export LD_LIBRARY_PATH=/lib64/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.3
export PATH=/usr/local/cuda-11.3/bin:$PATH
source /opt/rh/devtoolset-6/enable

some result of execute  is below:
ENVIRONMENT
CUDA_VERSION: 113
NVCC path: /usr/local/cuda-11.3/bin/nvcc
GPP path: g++ VERSION: g++ (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)
CUDA_HOME: /usr/local/cuda-11.3
CONDA_PREFIX: /conda/envs/py39

### Expected behavior

it make me crazy for a long time. Please help

**Comment by kanishk-verma-dotcom** [comment]
Hi @wushandinghua, how did you sort it out?
